// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: chainsync.proto

package chainsync

import (
	"context"

	"internalwallet/proto/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAddressMonitorReq           = pb.AddAddressMonitorReq
	AddAddressMonitorResp          = pb.AddAddressMonitorResp
	AddressBalanceInfo             = pb.AddressBalanceInfo
	AddressMonitor                 = pb.AddressMonitor
	AddressMonitorChainStats       = pb.AddressMonitorChainStats
	AddressMonitorStatsData        = pb.AddressMonitorStatsData
	BalanceValidationStatus        = pb.BalanceValidationStatus
	ChainBlockInfo                 = pb.ChainBlockInfo
	DataPoint                      = pb.DataPoint
	ErrorStats                     = pb.ErrorStats
	GetAddressBalanceReq           = pb.GetAddressBalanceReq
	GetAddressBalanceResp          = pb.GetAddressBalanceResp
	GetAddressMonitorStatsReq      = pb.GetAddressMonitorStatsReq
	GetAddressMonitorStatsResp     = pb.GetAddressMonitorStatsResp
	GetAddressTransactionsReq      = pb.GetAddressTransactionsReq
	GetAddressTransactionsResp     = pb.GetAddressTransactionsResp
	GetBalanceValidationStatusReq  = pb.GetBalanceValidationStatusReq
	GetBalanceValidationStatusResp = pb.GetBalanceValidationStatusResp
	GetBlockTransactionsReq        = pb.GetBlockTransactionsReq
	GetBlockTransactionsResp       = pb.GetBlockTransactionsResp
	GetChainTransactionReq         = pb.GetChainTransactionReq
	GetChainTransactionResp        = pb.GetChainTransactionResp
	GetMonitoredAddressesReq       = pb.GetMonitoredAddressesReq
	GetMonitoredAddressesResp      = pb.GetMonitoredAddressesResp
	GetMultiAddressBalanceReq      = pb.GetMultiAddressBalanceReq
	GetMultiAddressBalanceResp     = pb.GetMultiAddressBalanceResp
	GetPerformanceMetricsReq       = pb.GetPerformanceMetricsReq
	GetPerformanceMetricsResp      = pb.GetPerformanceMetricsResp
	GetProviderStatusReq           = pb.GetProviderStatusReq
	GetProviderStatusResp          = pb.GetProviderStatusResp
	GetSyncStatsReq                = pb.GetSyncStatsReq
	GetSyncStatsResp               = pb.GetSyncStatsResp
	GetSyncStatusReq               = pb.GetSyncStatusReq
	GetSyncStatusResp              = pb.GetSyncStatusResp
	InternalTransaction            = pb.InternalTransaction
	IsInternalAddressReq           = pb.IsInternalAddressReq
	IsInternalAddressResp          = pb.IsInternalAddressResp
	PerformanceMetrics             = pb.PerformanceMetrics
	ProviderInfo                   = pb.ProviderInfo
	RemoveAddressMonitorReq        = pb.RemoveAddressMonitorReq
	RemoveAddressMonitorResp       = pb.RemoveAddressMonitorResp
	ResetSyncReq                   = pb.ResetSyncReq
	ResetSyncResp                  = pb.ResetSyncResp
	StartSyncReq                   = pb.StartSyncReq
	StartSyncResp                  = pb.StartSyncResp
	StopSyncReq                    = pb.StopSyncReq
	StopSyncResp                   = pb.StopSyncResp
	SwitchProviderReq              = pb.SwitchProviderReq
	SwitchProviderResp             = pb.SwitchProviderResp
	SyncInfo                       = pb.SyncInfo
	SyncStats                      = pb.SyncStats
	TestProviderReq                = pb.TestProviderReq
	TestProviderResp               = pb.TestProviderResp
	TokenBalance                   = pb.TokenBalance
	Transaction                    = pb.Transaction
	TransactionLog                 = pb.TransactionLog

	ChainSync interface {
		// ==================== 区块链状态管理 ====================
		StartSync(ctx context.Context, in *StartSyncReq, opts ...grpc.CallOption) (*StartSyncResp, error)
		// 停止区块链同步
		StopSync(ctx context.Context, in *StopSyncReq, opts ...grpc.CallOption) (*StopSyncResp, error)
		// 获取同步状态
		GetSyncStatus(ctx context.Context, in *GetSyncStatusReq, opts ...grpc.CallOption) (*GetSyncStatusResp, error)
		// 重置同步位置
		ResetSync(ctx context.Context, in *ResetSyncReq, opts ...grpc.CallOption) (*ResetSyncResp, error)
		// ==================== 地址监控 ====================
		AddAddressMonitor(ctx context.Context, in *AddAddressMonitorReq, opts ...grpc.CallOption) (*AddAddressMonitorResp, error)
		// 移除地址监控
		RemoveAddressMonitor(ctx context.Context, in *RemoveAddressMonitorReq, opts ...grpc.CallOption) (*RemoveAddressMonitorResp, error)
		// 获取监控地址列表
		GetMonitoredAddresses(ctx context.Context, in *GetMonitoredAddressesReq, opts ...grpc.CallOption) (*GetMonitoredAddressesResp, error)
		// 查询地址是否为内部地址（充值地址/公司钱包/Vault 地址）
		IsInternalAddress(ctx context.Context, in *IsInternalAddressReq, opts ...grpc.CallOption) (*IsInternalAddressResp, error)
		// 获取地址监控统计信息（含全量刷新与事件增量状态）
		GetAddressMonitorStats(ctx context.Context, in *GetAddressMonitorStatsReq, opts ...grpc.CallOption) (*GetAddressMonitorStatsResp, error)
		// ==================== 交易监控 ====================
		GetTransaction(ctx context.Context, in *GetChainTransactionReq, opts ...grpc.CallOption) (*GetChainTransactionResp, error)
		// 获取地址交易历史
		GetAddressTransactions(ctx context.Context, in *GetAddressTransactionsReq, opts ...grpc.CallOption) (*GetAddressTransactionsResp, error)
		// 查询特定区块的交易
		GetBlockTransactions(ctx context.Context, in *GetBlockTransactionsReq, opts ...grpc.CallOption) (*GetBlockTransactionsResp, error)
		// ==================== 余额监控 ====================
		GetAddressBalance(ctx context.Context, in *GetAddressBalanceReq, opts ...grpc.CallOption) (*GetAddressBalanceResp, error)
		// 获取多地址余额
		GetMultiAddressBalance(ctx context.Context, in *GetMultiAddressBalanceReq, opts ...grpc.CallOption) (*GetMultiAddressBalanceResp, error)
		// ==================== 服务商管理 ====================
		GetProviderStatus(ctx context.Context, in *GetProviderStatusReq, opts ...grpc.CallOption) (*GetProviderStatusResp, error)
		// 切换服务商
		SwitchProvider(ctx context.Context, in *SwitchProviderReq, opts ...grpc.CallOption) (*SwitchProviderResp, error)
		// 测试服务商连接
		TestProvider(ctx context.Context, in *TestProviderReq, opts ...grpc.CallOption) (*TestProviderResp, error)
		// ==================== 数据统计 ====================
		GetSyncStats(ctx context.Context, in *GetSyncStatsReq, opts ...grpc.CallOption) (*GetSyncStatsResp, error)
		// 获取性能指标
		GetPerformanceMetrics(ctx context.Context, in *GetPerformanceMetricsReq, opts ...grpc.CallOption) (*GetPerformanceMetricsResp, error)
		// ==================== 余额校验 ====================
		GetBalanceValidationStatus(ctx context.Context, in *GetBalanceValidationStatusReq, opts ...grpc.CallOption) (*GetBalanceValidationStatusResp, error)
	}

	defaultChainSync struct {
		cli zrpc.Client
	}
)

func NewChainSync(cli zrpc.Client) ChainSync {
	return &defaultChainSync{
		cli: cli,
	}
}

// ==================== 区块链状态管理 ====================
func (m *defaultChainSync) StartSync(ctx context.Context, in *StartSyncReq, opts ...grpc.CallOption) (*StartSyncResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.StartSync(ctx, in, opts...)
}

// 停止区块链同步
func (m *defaultChainSync) StopSync(ctx context.Context, in *StopSyncReq, opts ...grpc.CallOption) (*StopSyncResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.StopSync(ctx, in, opts...)
}

// 获取同步状态
func (m *defaultChainSync) GetSyncStatus(ctx context.Context, in *GetSyncStatusReq, opts ...grpc.CallOption) (*GetSyncStatusResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.GetSyncStatus(ctx, in, opts...)
}

// 重置同步位置
func (m *defaultChainSync) ResetSync(ctx context.Context, in *ResetSyncReq, opts ...grpc.CallOption) (*ResetSyncResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.ResetSync(ctx, in, opts...)
}

// ==================== 地址监控 ====================
func (m *defaultChainSync) AddAddressMonitor(ctx context.Context, in *AddAddressMonitorReq, opts ...grpc.CallOption) (*AddAddressMonitorResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.AddAddressMonitor(ctx, in, opts...)
}

// 移除地址监控
func (m *defaultChainSync) RemoveAddressMonitor(ctx context.Context, in *RemoveAddressMonitorReq, opts ...grpc.CallOption) (*RemoveAddressMonitorResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.RemoveAddressMonitor(ctx, in, opts...)
}

// 获取监控地址列表
func (m *defaultChainSync) GetMonitoredAddresses(ctx context.Context, in *GetMonitoredAddressesReq, opts ...grpc.CallOption) (*GetMonitoredAddressesResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.GetMonitoredAddresses(ctx, in, opts...)
}

// 查询地址是否为内部地址（充值地址/公司钱包/Vault 地址）
func (m *defaultChainSync) IsInternalAddress(ctx context.Context, in *IsInternalAddressReq, opts ...grpc.CallOption) (*IsInternalAddressResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.IsInternalAddress(ctx, in, opts...)
}

// 获取地址监控统计信息（含全量刷新与事件增量状态）
func (m *defaultChainSync) GetAddressMonitorStats(ctx context.Context, in *GetAddressMonitorStatsReq, opts ...grpc.CallOption) (*GetAddressMonitorStatsResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.GetAddressMonitorStats(ctx, in, opts...)
}

// ==================== 交易监控 ====================
func (m *defaultChainSync) GetTransaction(ctx context.Context, in *GetChainTransactionReq, opts ...grpc.CallOption) (*GetChainTransactionResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.GetTransaction(ctx, in, opts...)
}

// 获取地址交易历史
func (m *defaultChainSync) GetAddressTransactions(ctx context.Context, in *GetAddressTransactionsReq, opts ...grpc.CallOption) (*GetAddressTransactionsResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.GetAddressTransactions(ctx, in, opts...)
}

// 查询特定区块的交易
func (m *defaultChainSync) GetBlockTransactions(ctx context.Context, in *GetBlockTransactionsReq, opts ...grpc.CallOption) (*GetBlockTransactionsResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.GetBlockTransactions(ctx, in, opts...)
}

// ==================== 余额监控 ====================
func (m *defaultChainSync) GetAddressBalance(ctx context.Context, in *GetAddressBalanceReq, opts ...grpc.CallOption) (*GetAddressBalanceResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.GetAddressBalance(ctx, in, opts...)
}

// 获取多地址余额
func (m *defaultChainSync) GetMultiAddressBalance(ctx context.Context, in *GetMultiAddressBalanceReq, opts ...grpc.CallOption) (*GetMultiAddressBalanceResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.GetMultiAddressBalance(ctx, in, opts...)
}

// ==================== 服务商管理 ====================
func (m *defaultChainSync) GetProviderStatus(ctx context.Context, in *GetProviderStatusReq, opts ...grpc.CallOption) (*GetProviderStatusResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.GetProviderStatus(ctx, in, opts...)
}

// 切换服务商
func (m *defaultChainSync) SwitchProvider(ctx context.Context, in *SwitchProviderReq, opts ...grpc.CallOption) (*SwitchProviderResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.SwitchProvider(ctx, in, opts...)
}

// 测试服务商连接
func (m *defaultChainSync) TestProvider(ctx context.Context, in *TestProviderReq, opts ...grpc.CallOption) (*TestProviderResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.TestProvider(ctx, in, opts...)
}

// ==================== 数据统计 ====================
func (m *defaultChainSync) GetSyncStats(ctx context.Context, in *GetSyncStatsReq, opts ...grpc.CallOption) (*GetSyncStatsResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.GetSyncStats(ctx, in, opts...)
}

// 获取性能指标
func (m *defaultChainSync) GetPerformanceMetrics(ctx context.Context, in *GetPerformanceMetricsReq, opts ...grpc.CallOption) (*GetPerformanceMetricsResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.GetPerformanceMetrics(ctx, in, opts...)
}

// ==================== 余额校验 ====================
func (m *defaultChainSync) GetBalanceValidationStatus(ctx context.Context, in *GetBalanceValidationStatusReq, opts ...grpc.CallOption) (*GetBalanceValidationStatusResp, error) {
	client := pb.NewChainSyncClient(m.cli.Conn())
	return client.GetBalanceValidationStatus(ctx, in, opts...)
}
