// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: swap.proto

package server

import (
	"context"

	"internalwallet/proto/pb"
	"internalwallet/services/swap/rpc/internal/logic"
	"internalwallet/services/swap/rpc/internal/svc"
)

type SwapServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSwapServer
}

func NewSwapServer(svcCtx *svc.ServiceContext) *SwapServer {
	return &SwapServer{
		svcCtx: svcCtx,
	}
}

// ==================== Swap APIs ====================
func (s *SwapServer) GetQuote(ctx context.Context, in *pb.GetQuoteRequest) (*pb.GetQuoteResponse, error) {
	l := logic.NewGetQuoteLogic(ctx, s.svcCtx)
	return l.GetQuote(in)
}

func (s *SwapServer) ExecuteSwap(ctx context.Context, in *pb.ExecuteSwapRequest) (*pb.ExecuteSwapResponse, error) {
	l := logic.NewExecuteSwapLogic(ctx, s.svcCtx)
	return l.ExecuteSwap(in)
}

func (s *SwapServer) GetApprovalTransaction(ctx context.Context, in *pb.GetApprovalTransactionRequest) (*pb.GetApprovalTransactionResponse, error) {
	l := logic.NewGetApprovalTransactionLogic(ctx, s.svcCtx)
	return l.GetApprovalTransaction(in)
}

func (s *SwapServer) ResetApproval(ctx context.Context, in *pb.ResetApprovalRequest) (*pb.ResetApprovalResponse, error) {
	l := logic.NewResetApprovalLogic(ctx, s.svcCtx)
	return l.ResetApproval(in)
}

func (s *SwapServer) GetSwapStatus(ctx context.Context, in *pb.GetSwapStatusRequest) (*pb.GetSwapStatusResponse, error) {
	l := logic.NewGetSwapStatusLogic(ctx, s.svcCtx)
	return l.GetSwapStatus(in)
}

func (s *SwapServer) GetSwapHistory(ctx context.Context, in *pb.GetSwapHistoryRequest) (*pb.GetSwapHistoryResponse, error) {
	l := logic.NewGetSwapHistoryLogic(ctx, s.svcCtx)
	return l.GetSwapHistory(in)
}

// GetSwapDetail returns a swap transaction record stored in swap_svc_transactions.
func (s *SwapServer) GetSwapDetail(ctx context.Context, in *pb.GetSwapDetailRequest) (*pb.GetSwapDetailResponse, error) {
	l := logic.NewGetSwapDetailLogic(ctx, s.svcCtx)
	return l.GetSwapDetail(in)
}

func (s *SwapServer) GetSupportedTokens(ctx context.Context, in *pb.GetSupportedTokensRequest) (*pb.GetSupportedTokensResponse, error) {
	l := logic.NewGetSupportedTokensLogic(ctx, s.svcCtx)
	return l.GetSupportedTokens(in)
}

func (s *SwapServer) GetSupportedChains(ctx context.Context, in *pb.GetSupportedChainsRequest) (*pb.GetSupportedChainsResponse, error) {
	l := logic.NewGetSupportedChainsLogic(ctx, s.svcCtx)
	return l.GetSupportedChains(in)
}

func (s *SwapServer) BroadcastSwap(ctx context.Context, in *pb.BroadcastSwapRequest) (*pb.BroadcastSwapResponse, error) {
	l := logic.NewBroadcastSwapLogic(ctx, s.svcCtx)
	return l.BroadcastSwap(in)
}

// UpdateSwapBroadcastResult updates swap_svc_transactions after an external broadcast (e.g. client broadcast via /web3/transaction/broadcast).
func (s *SwapServer) UpdateSwapBroadcastResult(ctx context.Context, in *pb.UpdateSwapBroadcastResultRequest) (*pb.UpdateSwapBroadcastResultResponse, error) {
	l := logic.NewUpdateSwapBroadcastResultLogic(ctx, s.svcCtx)
	return l.UpdateSwapBroadcastResult(in)
}

// ==================== OKX DEX Specific APIs ====================
func (s *SwapServer) GetLiquiditySources(ctx context.Context, in *pb.GetLiquiditySourcesRequest) (*pb.GetLiquiditySourcesResponse, error) {
	l := logic.NewGetLiquiditySourcesLogic(ctx, s.svcCtx)
	return l.GetLiquiditySources(in)
}

func (s *SwapServer) GetExternalSwapStatus(ctx context.Context, in *pb.GetExternalSwapStatusRequest) (*pb.GetExternalSwapStatusResponse, error) {
	l := logic.NewGetExternalSwapStatusLogic(ctx, s.svcCtx)
	return l.GetExternalSwapStatus(in)
}

// ==================== API Key Management (admin-protected) ====================
func (s *SwapServer) CreateSwapApiKey(ctx context.Context, in *pb.CreateSwapApiKeyRequest) (*pb.CreateSwapApiKeyResponse, error) {
	l := logic.NewCreateSwapApiKeyLogic(ctx, s.svcCtx)
	return l.CreateSwapApiKey(in)
}

func (s *SwapServer) RevokeSwapApiKey(ctx context.Context, in *pb.RevokeSwapApiKeyRequest) (*pb.RevokeSwapApiKeyResponse, error) {
	l := logic.NewRevokeSwapApiKeyLogic(ctx, s.svcCtx)
	return l.RevokeSwapApiKey(in)
}

func (s *SwapServer) ListSwapApiKeys(ctx context.Context, in *pb.ListSwapApiKeysRequest) (*pb.ListSwapApiKeysResponse, error) {
	l := logic.NewListSwapApiKeysLogic(ctx, s.svcCtx)
	return l.ListSwapApiKeys(in)
}

// ==================== Provider管理 (Provider Management - Admin-protected) ====================
func (s *SwapServer) CreateSwapProvider(ctx context.Context, in *pb.SwapCreateProviderRequest) (*pb.SwapCreateProviderResponse, error) {
	l := logic.NewCreateSwapProviderLogic(ctx, s.svcCtx)
	return l.CreateSwapProvider(in)
}

func (s *SwapServer) UpdateSwapProvider(ctx context.Context, in *pb.SwapUpdateProviderRequest) (*pb.SwapUpdateProviderResponse, error) {
	l := logic.NewUpdateSwapProviderLogic(ctx, s.svcCtx)
	return l.UpdateSwapProvider(in)
}

func (s *SwapServer) ListSwapProviders(ctx context.Context, in *pb.SwapListProvidersRequest) (*pb.SwapListProvidersResponse, error) {
	l := logic.NewListSwapProvidersLogic(ctx, s.svcCtx)
	return l.ListSwapProviders(in)
}

func (s *SwapServer) GetSwapProviderDetail(ctx context.Context, in *pb.SwapGetProviderDetailRequest) (*pb.SwapGetProviderDetailResponse, error) {
	l := logic.NewGetSwapProviderDetailLogic(ctx, s.svcCtx)
	return l.GetSwapProviderDetail(in)
}

func (s *SwapServer) DeleteSwapProvider(ctx context.Context, in *pb.SwapDeleteProviderRequest) (*pb.SwapDeleteProviderResponse, error) {
	l := logic.NewDeleteSwapProviderLogic(ctx, s.svcCtx)
	return l.DeleteSwapProvider(in)
}

func (s *SwapServer) EnableSwapProvider(ctx context.Context, in *pb.SwapEnableProviderRequest) (*pb.SwapEnableProviderResponse, error) {
	l := logic.NewEnableSwapProviderLogic(ctx, s.svcCtx)
	return l.EnableSwapProvider(in)
}

func (s *SwapServer) DisableSwapProvider(ctx context.Context, in *pb.SwapDisableProviderRequest) (*pb.SwapDisableProviderResponse, error) {
	l := logic.NewDisableSwapProviderLogic(ctx, s.svcCtx)
	return l.DisableSwapProvider(in)
}

func (s *SwapServer) ListSwapProvidersForDropdown(ctx context.Context, in *pb.SwapListProvidersForDropdownRequest) (*pb.SwapListProvidersForDropdownResponse, error) {
	l := logic.NewListSwapProvidersForDropdownLogic(ctx, s.svcCtx)
	return l.ListSwapProvidersForDropdown(in)
}

// ==================== 简化配置管理 (Simplified Config Management - Admin-protected) ====================
func (s *SwapServer) ListSwapConfigs(ctx context.Context, in *pb.SwapListSwapConfigsRequest) (*pb.SwapListSwapConfigsResponse, error) {
	l := logic.NewListSwapConfigsLogic(ctx, s.svcCtx)
	return l.ListSwapConfigs(in)
}

func (s *SwapServer) GetSwapConfigDetail(ctx context.Context, in *pb.SwapGetSwapConfigDetailRequest) (*pb.SwapGetSwapConfigDetailResponse, error) {
	l := logic.NewGetSwapConfigDetailLogic(ctx, s.svcCtx)
	return l.GetSwapConfigDetail(in)
}

func (s *SwapServer) CreateSwapConfig(ctx context.Context, in *pb.SwapCreateSwapConfigRequest) (*pb.SwapCreateSwapConfigResponse, error) {
	l := logic.NewCreateSwapConfigLogic(ctx, s.svcCtx)
	return l.CreateSwapConfig(in)
}

func (s *SwapServer) UpdateSwapConfigDetail(ctx context.Context, in *pb.SwapUpdateSwapConfigDetailRequest) (*pb.SwapUpdateSwapConfigDetailResponse, error) {
	l := logic.NewUpdateSwapConfigDetailLogic(ctx, s.svcCtx)
	return l.UpdateSwapConfigDetail(in)
}

func (s *SwapServer) DeleteSwapConfig(ctx context.Context, in *pb.SwapDeleteSwapConfigRequest) (*pb.SwapDeleteSwapConfigResponse, error) {
	l := logic.NewDeleteSwapConfigLogic(ctx, s.svcCtx)
	return l.DeleteSwapConfig(in)
}

// 项目配置管理（启用/禁用开关）
func (s *SwapServer) ListProjectSwapConfigs(ctx context.Context, in *pb.SwapListProjectSwapConfigsRequest) (*pb.SwapListProjectSwapConfigsResponse, error) {
	l := logic.NewListProjectSwapConfigsLogic(ctx, s.svcCtx)
	return l.ListProjectSwapConfigs(in)
}

func (s *SwapServer) EnableSwapConfigForProject(ctx context.Context, in *pb.SwapEnableSwapConfigForProjectRequest) (*pb.SwapEnableSwapConfigForProjectResponse, error) {
	l := logic.NewEnableSwapConfigForProjectLogic(ctx, s.svcCtx)
	return l.EnableSwapConfigForProject(in)
}

func (s *SwapServer) DisableSwapConfigForProject(ctx context.Context, in *pb.SwapDisableSwapConfigForProjectRequest) (*pb.SwapDisableSwapConfigForProjectResponse, error) {
	l := logic.NewDisableSwapConfigForProjectLogic(ctx, s.svcCtx)
	return l.DisableSwapConfigForProject(in)
}

// ==================== 业务端配置查询 (Business API - API Key authenticated) ====================
func (s *SwapServer) GetMySwapConfigs(ctx context.Context, in *pb.SwapGetMySwapConfigsRequest) (*pb.SwapGetMySwapConfigsResponse, error) {
	l := logic.NewGetMySwapConfigsLogic(ctx, s.svcCtx)
	return l.GetMySwapConfigs(in)
}

// ==================== 统计与查询 (API Key authenticated) ====================
func (s *SwapServer) ListSwapTransactions(ctx context.Context, in *pb.SwapListSwapTransactionsRequest) (*pb.SwapListSwapTransactionsResponse, error) {
	l := logic.NewListSwapTransactionsLogic(ctx, s.svcCtx)
	return l.ListSwapTransactions(in)
}
