// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: chainrpc.proto

package chainrpc

import (
	"context"

	"internalwallet/proto/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BalanceInfo                      = pb.BalanceInfo
	BatchTransferReq                 = pb.BatchTransferReq
	BatchTransferResp                = pb.BatchTransferResp
	BlockInfo                        = pb.BlockInfo
	BroadcastTransactionReq          = pb.BroadcastTransactionReq
	BroadcastTransactionResp         = pb.BroadcastTransactionResp
	BuildTransactionReq              = pb.BuildTransactionReq
	BuildTransactionResp             = pb.BuildTransactionResp
	CancelTransactionReq             = pb.CancelTransactionReq
	CancelTransactionResp            = pb.CancelTransactionResp
	ChainHealth                      = pb.ChainHealth
	ChainRpcBuildTronTransactionReq  = pb.ChainRpcBuildTronTransactionReq
	ChainRpcBuildTronTransactionResp = pb.ChainRpcBuildTronTransactionResp
	EstimateGasReq                   = pb.EstimateGasReq
	EstimateGasResp                  = pb.EstimateGasResp
	EstimateTronFeeReq               = pb.EstimateTronFeeReq
	EstimateTronFeeResp              = pb.EstimateTronFeeResp
	EventLog                         = pb.EventLog
	GasPriceInfo                     = pb.GasPriceInfo
	GetBalanceReq                    = pb.GetBalanceReq
	GetBalanceResp                   = pb.GetBalanceResp
	GetBlockHeightReq                = pb.GetBlockHeightReq
	GetBlockHeightResp               = pb.GetBlockHeightResp
	GetBlockReq                      = pb.GetBlockReq
	GetBlockResp                     = pb.GetBlockResp
	GetGasPriceReq                   = pb.GetGasPriceReq
	GetGasPriceResp                  = pb.GetGasPriceResp
	GetMultiBalanceReq               = pb.GetMultiBalanceReq
	GetMultiBalanceResp              = pb.GetMultiBalanceResp
	GetNodeStatusReq                 = pb.GetNodeStatusReq
	GetNodeStatusResp                = pb.GetNodeStatusResp
	GetNonceReq                      = pb.GetNonceReq
	GetNonceResp                     = pb.GetNonceResp
	GetTokenBalanceReq               = pb.GetTokenBalanceReq
	GetTokenBalanceResp              = pb.GetTokenBalanceResp
	GetTokenInfoBatchReq             = pb.GetTokenInfoBatchReq
	GetTokenInfoBatchResp            = pb.GetTokenInfoBatchResp
	GetTokenInfoReq                  = pb.GetTokenInfoReq
	GetTokenInfoResp                 = pb.GetTokenInfoResp
	GetTransactionReceiptReq         = pb.GetTransactionReceiptReq
	GetTransactionReceiptResp        = pb.GetTransactionReceiptResp
	GetTransactionReq                = pb.GetTransactionReq
	GetTransactionResp               = pb.GetTransactionResp
	GetTransactionStatusReq          = pb.GetTransactionStatusReq
	GetTransactionStatusResp         = pb.GetTransactionStatusResp
	GetTronAccountResourcesReq       = pb.GetTronAccountResourcesReq
	GetTronAccountResourcesResp      = pb.GetTronAccountResourcesResp
	HealthCheckReq                   = pb.HealthCheckReq
	HealthCheckResp                  = pb.HealthCheckResp
	NativeTransferReq                = pb.NativeTransferReq
	NodeInfo                         = pb.NodeInfo
	SpeedUpTransactionReq            = pb.SpeedUpTransactionReq
	SpeedUpTransactionResp           = pb.SpeedUpTransactionResp
	SwitchNodeReq                    = pb.SwitchNodeReq
	SwitchNodeResp                   = pb.SwitchNodeResp
	TestNodeReq                      = pb.TestNodeReq
	TestNodeResp                     = pb.TestNodeResp
	TokenBalanceInfo                 = pb.TokenBalanceInfo
	TokenInfo                        = pb.TokenInfo
	TokenTransferReq                 = pb.TokenTransferReq
	TransactionDetail                = pb.TransactionDetail
	TransactionReceipt               = pb.TransactionReceipt
	TransactionResp                  = pb.TransactionResp
	TransferItem                     = pb.TransferItem

	ChainRPC interface {
		// ==================== 转账交易 ====================
		NativeTransfer(ctx context.Context, in *NativeTransferReq, opts ...grpc.CallOption) (*TransactionResp, error)
		// 代币转账交易
		TokenTransfer(ctx context.Context, in *TokenTransferReq, opts ...grpc.CallOption) (*TransactionResp, error)
		// 批量转账交易（归集用）
		BatchTransfer(ctx context.Context, in *BatchTransferReq, opts ...grpc.CallOption) (*BatchTransferResp, error)
		// 估算Gas费用
		EstimateGas(ctx context.Context, in *EstimateGasReq, opts ...grpc.CallOption) (*EstimateGasResp, error)
		// 获取推荐Gas价格
		GetGasPrice(ctx context.Context, in *GetGasPriceReq, opts ...grpc.CallOption) (*GetGasPriceResp, error)
		// ==================== TRON 资源/手续费 ====================
		EstimateTronFee(ctx context.Context, in *EstimateTronFeeReq, opts ...grpc.CallOption) (*EstimateTronFeeResp, error)
		// 查询 TRON 地址资源（Bandwidth/Energy/余额）
		GetTronAccountResources(ctx context.Context, in *GetTronAccountResourcesReq, opts ...grpc.CallOption) (*GetTronAccountResourcesResp, error)
		// ==================== 交易广播 ====================
		BroadcastTransaction(ctx context.Context, in *BroadcastTransactionReq, opts ...grpc.CallOption) (*BroadcastTransactionResp, error)
		// 加速交易（Replace-By-Fee）
		SpeedUpTransaction(ctx context.Context, in *SpeedUpTransactionReq, opts ...grpc.CallOption) (*SpeedUpTransactionResp, error)
		// 取消交易
		CancelTransaction(ctx context.Context, in *CancelTransactionReq, opts ...grpc.CallOption) (*CancelTransactionResp, error)
		// ==================== 链上查询 ====================
		GetBalance(ctx context.Context, in *GetBalanceReq, opts ...grpc.CallOption) (*GetBalanceResp, error)
		// 查询代币余额
		GetTokenBalance(ctx context.Context, in *GetTokenBalanceReq, opts ...grpc.CallOption) (*GetTokenBalanceResp, error)
		// 查询多地址余额
		GetMultiBalance(ctx context.Context, in *GetMultiBalanceReq, opts ...grpc.CallOption) (*GetMultiBalanceResp, error)
		// 查询交易详情
		GetTransaction(ctx context.Context, in *GetTransactionReq, opts ...grpc.CallOption) (*GetTransactionResp, error)
		// 查询交易状态
		GetTransactionStatus(ctx context.Context, in *GetTransactionStatusReq, opts ...grpc.CallOption) (*GetTransactionStatusResp, error)
		// 查询交易收据
		GetTransactionReceipt(ctx context.Context, in *GetTransactionReceiptReq, opts ...grpc.CallOption) (*GetTransactionReceiptResp, error)
		// 查询区块高度
		GetBlockHeight(ctx context.Context, in *GetBlockHeightReq, opts ...grpc.CallOption) (*GetBlockHeightResp, error)
		// 查询区块信息
		GetBlock(ctx context.Context, in *GetBlockReq, opts ...grpc.CallOption) (*GetBlockResp, error)
		// 查询Nonce
		GetNonce(ctx context.Context, in *GetNonceReq, opts ...grpc.CallOption) (*GetNonceResp, error)
		// 构建 EVM 交易（ETH/BSC，返回未签名 rawTx，供 Signer 签名）
		BuildTransaction(ctx context.Context, in *BuildTransactionReq, opts ...grpc.CallOption) (*BuildTransactionResp, error)
		// 构建 TRON 交易（返回未签名的 rawData，供客户端签名）
		BuildTronTransaction(ctx context.Context, in *ChainRpcBuildTronTransactionReq, opts ...grpc.CallOption) (*ChainRpcBuildTronTransactionResp, error)
		// ==================== 代币信息 ====================
		GetTokenInfo(ctx context.Context, in *GetTokenInfoReq, opts ...grpc.CallOption) (*GetTokenInfoResp, error)
		// 批量查询代币信息
		GetTokenInfoBatch(ctx context.Context, in *GetTokenInfoBatchReq, opts ...grpc.CallOption) (*GetTokenInfoBatchResp, error)
		// ==================== 节点管理 ====================
		HealthCheck(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckResp, error)
		// 获取节点状态
		GetNodeStatus(ctx context.Context, in *GetNodeStatusReq, opts ...grpc.CallOption) (*GetNodeStatusResp, error)
		// 切换节点
		SwitchNode(ctx context.Context, in *SwitchNodeReq, opts ...grpc.CallOption) (*SwitchNodeResp, error)
		// 测试节点连接
		TestNode(ctx context.Context, in *TestNodeReq, opts ...grpc.CallOption) (*TestNodeResp, error)
	}

	defaultChainRPC struct {
		cli zrpc.Client
	}
)

func NewChainRPC(cli zrpc.Client) ChainRPC {
	return &defaultChainRPC{
		cli: cli,
	}
}

// ==================== 转账交易 ====================
func (m *defaultChainRPC) NativeTransfer(ctx context.Context, in *NativeTransferReq, opts ...grpc.CallOption) (*TransactionResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.NativeTransfer(ctx, in, opts...)
}

// 代币转账交易
func (m *defaultChainRPC) TokenTransfer(ctx context.Context, in *TokenTransferReq, opts ...grpc.CallOption) (*TransactionResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.TokenTransfer(ctx, in, opts...)
}

// 批量转账交易（归集用）
func (m *defaultChainRPC) BatchTransfer(ctx context.Context, in *BatchTransferReq, opts ...grpc.CallOption) (*BatchTransferResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.BatchTransfer(ctx, in, opts...)
}

// 估算Gas费用
func (m *defaultChainRPC) EstimateGas(ctx context.Context, in *EstimateGasReq, opts ...grpc.CallOption) (*EstimateGasResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.EstimateGas(ctx, in, opts...)
}

// 获取推荐Gas价格
func (m *defaultChainRPC) GetGasPrice(ctx context.Context, in *GetGasPriceReq, opts ...grpc.CallOption) (*GetGasPriceResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.GetGasPrice(ctx, in, opts...)
}

// ==================== TRON 资源/手续费 ====================
func (m *defaultChainRPC) EstimateTronFee(ctx context.Context, in *EstimateTronFeeReq, opts ...grpc.CallOption) (*EstimateTronFeeResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.EstimateTronFee(ctx, in, opts...)
}

// 查询 TRON 地址资源（Bandwidth/Energy/余额）
func (m *defaultChainRPC) GetTronAccountResources(ctx context.Context, in *GetTronAccountResourcesReq, opts ...grpc.CallOption) (*GetTronAccountResourcesResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.GetTronAccountResources(ctx, in, opts...)
}

// ==================== 交易广播 ====================
func (m *defaultChainRPC) BroadcastTransaction(ctx context.Context, in *BroadcastTransactionReq, opts ...grpc.CallOption) (*BroadcastTransactionResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.BroadcastTransaction(ctx, in, opts...)
}

// 加速交易（Replace-By-Fee）
func (m *defaultChainRPC) SpeedUpTransaction(ctx context.Context, in *SpeedUpTransactionReq, opts ...grpc.CallOption) (*SpeedUpTransactionResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.SpeedUpTransaction(ctx, in, opts...)
}

// 取消交易
func (m *defaultChainRPC) CancelTransaction(ctx context.Context, in *CancelTransactionReq, opts ...grpc.CallOption) (*CancelTransactionResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.CancelTransaction(ctx, in, opts...)
}

// ==================== 链上查询 ====================
func (m *defaultChainRPC) GetBalance(ctx context.Context, in *GetBalanceReq, opts ...grpc.CallOption) (*GetBalanceResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.GetBalance(ctx, in, opts...)
}

// 查询代币余额
func (m *defaultChainRPC) GetTokenBalance(ctx context.Context, in *GetTokenBalanceReq, opts ...grpc.CallOption) (*GetTokenBalanceResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.GetTokenBalance(ctx, in, opts...)
}

// 查询多地址余额
func (m *defaultChainRPC) GetMultiBalance(ctx context.Context, in *GetMultiBalanceReq, opts ...grpc.CallOption) (*GetMultiBalanceResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.GetMultiBalance(ctx, in, opts...)
}

// 查询交易详情
func (m *defaultChainRPC) GetTransaction(ctx context.Context, in *GetTransactionReq, opts ...grpc.CallOption) (*GetTransactionResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.GetTransaction(ctx, in, opts...)
}

// 查询交易状态
func (m *defaultChainRPC) GetTransactionStatus(ctx context.Context, in *GetTransactionStatusReq, opts ...grpc.CallOption) (*GetTransactionStatusResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.GetTransactionStatus(ctx, in, opts...)
}

// 查询交易收据
func (m *defaultChainRPC) GetTransactionReceipt(ctx context.Context, in *GetTransactionReceiptReq, opts ...grpc.CallOption) (*GetTransactionReceiptResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.GetTransactionReceipt(ctx, in, opts...)
}

// 查询区块高度
func (m *defaultChainRPC) GetBlockHeight(ctx context.Context, in *GetBlockHeightReq, opts ...grpc.CallOption) (*GetBlockHeightResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.GetBlockHeight(ctx, in, opts...)
}

// 查询区块信息
func (m *defaultChainRPC) GetBlock(ctx context.Context, in *GetBlockReq, opts ...grpc.CallOption) (*GetBlockResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.GetBlock(ctx, in, opts...)
}

// 查询Nonce
func (m *defaultChainRPC) GetNonce(ctx context.Context, in *GetNonceReq, opts ...grpc.CallOption) (*GetNonceResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.GetNonce(ctx, in, opts...)
}

// 构建 EVM 交易（ETH/BSC，返回未签名 rawTx，供 Signer 签名）
func (m *defaultChainRPC) BuildTransaction(ctx context.Context, in *BuildTransactionReq, opts ...grpc.CallOption) (*BuildTransactionResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.BuildTransaction(ctx, in, opts...)
}

// 构建 TRON 交易（返回未签名的 rawData，供客户端签名）
func (m *defaultChainRPC) BuildTronTransaction(ctx context.Context, in *ChainRpcBuildTronTransactionReq, opts ...grpc.CallOption) (*ChainRpcBuildTronTransactionResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.BuildTronTransaction(ctx, in, opts...)
}

// ==================== 代币信息 ====================
func (m *defaultChainRPC) GetTokenInfo(ctx context.Context, in *GetTokenInfoReq, opts ...grpc.CallOption) (*GetTokenInfoResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.GetTokenInfo(ctx, in, opts...)
}

// 批量查询代币信息
func (m *defaultChainRPC) GetTokenInfoBatch(ctx context.Context, in *GetTokenInfoBatchReq, opts ...grpc.CallOption) (*GetTokenInfoBatchResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.GetTokenInfoBatch(ctx, in, opts...)
}

// ==================== 节点管理 ====================
func (m *defaultChainRPC) HealthCheck(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.HealthCheck(ctx, in, opts...)
}

// 获取节点状态
func (m *defaultChainRPC) GetNodeStatus(ctx context.Context, in *GetNodeStatusReq, opts ...grpc.CallOption) (*GetNodeStatusResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.GetNodeStatus(ctx, in, opts...)
}

// 切换节点
func (m *defaultChainRPC) SwitchNode(ctx context.Context, in *SwitchNodeReq, opts ...grpc.CallOption) (*SwitchNodeResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.SwitchNode(ctx, in, opts...)
}

// 测试节点连接
func (m *defaultChainRPC) TestNode(ctx context.Context, in *TestNodeReq, opts ...grpc.CallOption) (*TestNodeResp, error) {
	client := pb.NewChainRPCClient(m.cli.Conn())
	return client.TestNode(ctx, in, opts...)
}
