// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: accounting.proto

package server

import (
	"context"

	"internalwallet/proto/pb"
	"internalwallet/services/accounting/rpc/internal/logic"
	"internalwallet/services/accounting/rpc/internal/svc"
)

type AccountingServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAccountingServer
}

func NewAccountingServer(svcCtx *svc.ServiceContext) *AccountingServer {
	return &AccountingServer{
		svcCtx: svcCtx,
	}
}

// ==================== Setup ====================
func (s *AccountingServer) EnsureUserAccountingSetup(ctx context.Context, in *pb.EnsureUserAccountingSetupRequest) (*pb.EnsureUserAccountingSetupResponse, error) {
	l := logic.NewEnsureUserAccountingSetupLogic(ctx, s.svcCtx)
	return l.EnsureUserAccountingSetup(in)
}

func (s *AccountingServer) EnsureSystemAccounts(ctx context.Context, in *pb.EnsureSystemAccountsRequest) (*pb.EnsureSystemAccountsResponse, error) {
	l := logic.NewEnsureSystemAccountsLogic(ctx, s.svcCtx)
	return l.EnsureSystemAccounts(in)
}

// ==================== Assets (source of truth) ====================
func (s *AccountingServer) GetAssetOverview(ctx context.Context, in *pb.Empty) (*pb.AcctAssetOverviewResponse, error) {
	l := logic.NewGetAssetOverviewLogic(ctx, s.svcCtx)
	return l.GetAssetOverview(in)
}

func (s *AccountingServer) ListAssets(ctx context.Context, in *pb.ListAssetsRequest) (*pb.ListAssetsResponse, error) {
	l := logic.NewListAssetsLogic(ctx, s.svcCtx)
	return l.ListAssets(in)
}

func (s *AccountingServer) GetAsset(ctx context.Context, in *pb.GetAssetRequest) (*pb.AcctAssetResponse, error) {
	l := logic.NewGetAssetLogic(ctx, s.svcCtx)
	return l.GetAsset(in)
}

func (s *AccountingServer) CreateAsset(ctx context.Context, in *pb.CreateAssetRequest) (*pb.AcctAssetResponse, error) {
	l := logic.NewCreateAssetLogic(ctx, s.svcCtx)
	return l.CreateAsset(in)
}

func (s *AccountingServer) UpdateAsset(ctx context.Context, in *pb.UpdateAssetRequest) (*pb.AcctAssetResponse, error) {
	l := logic.NewUpdateAssetLogic(ctx, s.svcCtx)
	return l.UpdateAsset(in)
}

func (s *AccountingServer) UpdateAssetStatus(ctx context.Context, in *pb.UpdateAssetStatusRequest) (*pb.AcctAssetResponse, error) {
	l := logic.NewUpdateAssetStatusLogic(ctx, s.svcCtx)
	return l.UpdateAssetStatus(in)
}

func (s *AccountingServer) UpdateAssetIcon(ctx context.Context, in *pb.UpdateAssetIconRequest) (*pb.AcctAssetResponse, error) {
	l := logic.NewUpdateAssetIconLogic(ctx, s.svcCtx)
	return l.UpdateAssetIcon(in)
}

// ==================== Account Types ====================
func (s *AccountingServer) CreateAccountType(ctx context.Context, in *pb.CreateAccountTypeRequest) (*pb.AcctAccountTypeResponse, error) {
	l := logic.NewCreateAccountTypeLogic(ctx, s.svcCtx)
	return l.CreateAccountType(in)
}

func (s *AccountingServer) UpdateAccountType(ctx context.Context, in *pb.UpdateAccountTypeRequest) (*pb.AcctAccountTypeResponse, error) {
	l := logic.NewUpdateAccountTypeLogic(ctx, s.svcCtx)
	return l.UpdateAccountType(in)
}

func (s *AccountingServer) DeleteAccountType(ctx context.Context, in *pb.DeleteAccountTypeRequest) (*pb.Empty, error) {
	l := logic.NewDeleteAccountTypeLogic(ctx, s.svcCtx)
	return l.DeleteAccountType(in)
}

func (s *AccountingServer) GetAccountType(ctx context.Context, in *pb.GetAccountTypeRequest) (*pb.AcctAccountTypeResponse, error) {
	l := logic.NewGetAccountTypeLogic(ctx, s.svcCtx)
	return l.GetAccountType(in)
}

func (s *AccountingServer) ListAccountTypes(ctx context.Context, in *pb.ListAccountTypesRequest) (*pb.ListAccountTypesResponse, error) {
	l := logic.NewListAccountTypesLogic(ctx, s.svcCtx)
	return l.ListAccountTypes(in)
}

func (s *AccountingServer) SetAccountTypeAssets(ctx context.Context, in *pb.SetAccountTypeAssetsRequest) (*pb.Empty, error) {
	l := logic.NewSetAccountTypeAssetsLogic(ctx, s.svcCtx)
	return l.SetAccountTypeAssets(in)
}

// ==================== Read APIs ====================
func (s *AccountingServer) GetUserBalances(ctx context.Context, in *pb.GetUserBalancesRequest) (*pb.GetUserBalancesResponse, error) {
	l := logic.NewGetUserBalancesLogic(ctx, s.svcCtx)
	return l.GetUserBalances(in)
}

func (s *AccountingServer) ListLedgerTx(ctx context.Context, in *pb.ListLedgerTxRequest) (*pb.ListLedgerTxResponse, error) {
	l := logic.NewListLedgerTxLogic(ctx, s.svcCtx)
	return l.ListLedgerTx(in)
}

func (s *AccountingServer) GetLedgerTxDetail(ctx context.Context, in *pb.GetLedgerTxDetailRequest) (*pb.GetLedgerTxDetailResponse, error) {
	l := logic.NewGetLedgerTxDetailLogic(ctx, s.svcCtx)
	return l.GetLedgerTxDetail(in)
}

func (s *AccountingServer) ListUserTransactionRecords(ctx context.Context, in *pb.ListUserTransactionRecordsRequest) (*pb.ListUserTransactionRecordsResponse, error) {
	l := logic.NewListUserTransactionRecordsLogic(ctx, s.svcCtx)
	return l.ListUserTransactionRecords(in)
}

func (s *AccountingServer) GetUserTransactionRecordDetail(ctx context.Context, in *pb.GetUserTransactionRecordDetailRequest) (*pb.GetUserTransactionRecordDetailResponse, error) {
	l := logic.NewGetUserTransactionRecordDetailLogic(ctx, s.svcCtx)
	return l.GetUserTransactionRecordDetail(in)
}

func (s *AccountingServer) UpsertUserTransactionRecordMeta(ctx context.Context, in *pb.UpsertUserTransactionRecordMetaRequest) (*pb.UpsertUserTransactionRecordMetaResponse, error) {
	l := logic.NewUpsertUserTransactionRecordMetaLogic(ctx, s.svcCtx)
	return l.UpsertUserTransactionRecordMeta(in)
}

// ==================== Fixed double-entry templates ====================
func (s *AccountingServer) FreezeWithdraw(ctx context.Context, in *pb.FreezeWithdrawRequest) (*pb.LedgerTxResponse, error) {
	l := logic.NewFreezeWithdrawLogic(ctx, s.svcCtx)
	return l.FreezeWithdraw(in)
}

func (s *AccountingServer) UnfreezeWithdraw(ctx context.Context, in *pb.UnfreezeWithdrawRequest) (*pb.LedgerTxResponse, error) {
	l := logic.NewUnfreezeWithdrawLogic(ctx, s.svcCtx)
	return l.UnfreezeWithdraw(in)
}

func (s *AccountingServer) SettleWithdraw(ctx context.Context, in *pb.SettleWithdrawRequest) (*pb.LedgerTxResponse, error) {
	l := logic.NewSettleWithdrawLogic(ctx, s.svcCtx)
	return l.SettleWithdraw(in)
}

func (s *AccountingServer) ConfirmDeposit(ctx context.Context, in *pb.ConfirmDepositRequest) (*pb.LedgerTxResponse, error) {
	l := logic.NewConfirmDepositLogic(ctx, s.svcCtx)
	return l.ConfirmDeposit(in)
}

func (s *AccountingServer) AdminAdjust(ctx context.Context, in *pb.AdminAdjustRequest) (*pb.LedgerTxResponse, error) {
	l := logic.NewAdminAdjustLogic(ctx, s.svcCtx)
	return l.AdminAdjust(in)
}

func (s *AccountingServer) Transfer(ctx context.Context, in *pb.TransferRequest) (*pb.LedgerTxResponse, error) {
	l := logic.NewTransferLogic(ctx, s.svcCtx)
	return l.Transfer(in)
}

func (s *AccountingServer) FundSystemWallet(ctx context.Context, in *pb.FundSystemWalletRequest) (*pb.LedgerTxResponse, error) {
	l := logic.NewFundSystemWalletLogic(ctx, s.svcCtx)
	return l.FundSystemWallet(in)
}

func (s *AccountingServer) FreezeUserAssets(ctx context.Context, in *pb.FreezeUserAssetsRequest) (*pb.LedgerTxResponse, error) {
	l := logic.NewFreezeUserAssetsLogic(ctx, s.svcCtx)
	return l.FreezeUserAssets(in)
}

func (s *AccountingServer) UnfreezeUserAssets(ctx context.Context, in *pb.UnfreezeUserAssetsRequest) (*pb.LedgerTxResponse, error) {
	l := logic.NewUnfreezeUserAssetsLogic(ctx, s.svcCtx)
	return l.UnfreezeUserAssets(in)
}
