// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: consolidation.proto

package consolidation

import (
	"context"

	"internalwallet/proto/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelConsolidationTaskRequest        = pb.CancelConsolidationTaskRequest
	CancelConsolidationTaskResponse       = pb.CancelConsolidationTaskResponse
	ConsolidationLog                      = pb.ConsolidationLog
	ConsolidationStats                    = pb.ConsolidationStats
	ConsolidationTask                     = pb.ConsolidationTask
	ConsolidationTopupRecord              = pb.ConsolidationTopupRecord
	EnergyRentalRecord                    = pb.EnergyRentalRecord
	GetConsolidationStatsRequest          = pb.GetConsolidationStatsRequest
	GetConsolidationStatsResponse         = pb.GetConsolidationStatsResponse
	GetConsolidationTaskRequest           = pb.GetConsolidationTaskRequest
	GetConsolidationTaskResponse          = pb.GetConsolidationTaskResponse
	GetEnergyRentalRecordRequest          = pb.GetEnergyRentalRecordRequest
	GetEnergyRentalRecordResponse         = pb.GetEnergyRentalRecordResponse
	ListConsolidationLogsRequest          = pb.ListConsolidationLogsRequest
	ListConsolidationLogsResponse         = pb.ListConsolidationLogsResponse
	ListConsolidationTasksRequest         = pb.ListConsolidationTasksRequest
	ListConsolidationTasksResponse        = pb.ListConsolidationTasksResponse
	ListConsolidationTopupRecordsRequest  = pb.ListConsolidationTopupRecordsRequest
	ListConsolidationTopupRecordsResponse = pb.ListConsolidationTopupRecordsResponse
	ListEnergyRentalRecordsRequest        = pb.ListEnergyRentalRecordsRequest
	ListEnergyRentalRecordsResponse       = pb.ListEnergyRentalRecordsResponse
	RetryConsolidationTaskRequest         = pb.RetryConsolidationTaskRequest
	RetryConsolidationTaskResponse        = pb.RetryConsolidationTaskResponse
	TriggerConsolidationRequest           = pb.TriggerConsolidationRequest
	TriggerConsolidationResponse          = pb.TriggerConsolidationResponse

	Consolidation interface {
		// Manually trigger discovery/execution for a specific chain/asset (best-effort).
		TriggerConsolidation(ctx context.Context, in *TriggerConsolidationRequest, opts ...grpc.CallOption) (*TriggerConsolidationResponse, error)
		// Query task by task_id.
		GetConsolidationTask(ctx context.Context, in *GetConsolidationTaskRequest, opts ...grpc.CallOption) (*GetConsolidationTaskResponse, error)
		// List tasks with filters.
		ListConsolidationTasks(ctx context.Context, in *ListConsolidationTasksRequest, opts ...grpc.CallOption) (*ListConsolidationTasksResponse, error)
		// Aggregated stats.
		GetConsolidationStats(ctx context.Context, in *GetConsolidationStatsRequest, opts ...grpc.CallOption) (*GetConsolidationStatsResponse, error)
		// Cancel a pending task.
		CancelConsolidationTask(ctx context.Context, in *CancelConsolidationTaskRequest, opts ...grpc.CallOption) (*CancelConsolidationTaskResponse, error)
		// Retry a failed/permanent-failed task (subject to max retry policy).
		RetryConsolidationTask(ctx context.Context, in *RetryConsolidationTaskRequest, opts ...grpc.CallOption) (*RetryConsolidationTaskResponse, error)
		// List logs with filters.
		ListConsolidationLogs(ctx context.Context, in *ListConsolidationLogsRequest, opts ...grpc.CallOption) (*ListConsolidationLogsResponse, error)
		// List top-up records with filters.
		ListConsolidationTopupRecords(ctx context.Context, in *ListConsolidationTopupRecordsRequest, opts ...grpc.CallOption) (*ListConsolidationTopupRecordsResponse, error)
		// List energy rental records with filters.
		ListEnergyRentalRecords(ctx context.Context, in *ListEnergyRentalRecordsRequest, opts ...grpc.CallOption) (*ListEnergyRentalRecordsResponse, error)
		// Get energy rental record by ID.
		GetEnergyRentalRecord(ctx context.Context, in *GetEnergyRentalRecordRequest, opts ...grpc.CallOption) (*GetEnergyRentalRecordResponse, error)
	}

	defaultConsolidation struct {
		cli zrpc.Client
	}
)

func NewConsolidation(cli zrpc.Client) Consolidation {
	return &defaultConsolidation{
		cli: cli,
	}
}

// Manually trigger discovery/execution for a specific chain/asset (best-effort).
func (m *defaultConsolidation) TriggerConsolidation(ctx context.Context, in *TriggerConsolidationRequest, opts ...grpc.CallOption) (*TriggerConsolidationResponse, error) {
	client := pb.NewConsolidationClient(m.cli.Conn())
	return client.TriggerConsolidation(ctx, in, opts...)
}

// Query task by task_id.
func (m *defaultConsolidation) GetConsolidationTask(ctx context.Context, in *GetConsolidationTaskRequest, opts ...grpc.CallOption) (*GetConsolidationTaskResponse, error) {
	client := pb.NewConsolidationClient(m.cli.Conn())
	return client.GetConsolidationTask(ctx, in, opts...)
}

// List tasks with filters.
func (m *defaultConsolidation) ListConsolidationTasks(ctx context.Context, in *ListConsolidationTasksRequest, opts ...grpc.CallOption) (*ListConsolidationTasksResponse, error) {
	client := pb.NewConsolidationClient(m.cli.Conn())
	return client.ListConsolidationTasks(ctx, in, opts...)
}

// Aggregated stats.
func (m *defaultConsolidation) GetConsolidationStats(ctx context.Context, in *GetConsolidationStatsRequest, opts ...grpc.CallOption) (*GetConsolidationStatsResponse, error) {
	client := pb.NewConsolidationClient(m.cli.Conn())
	return client.GetConsolidationStats(ctx, in, opts...)
}

// Cancel a pending task.
func (m *defaultConsolidation) CancelConsolidationTask(ctx context.Context, in *CancelConsolidationTaskRequest, opts ...grpc.CallOption) (*CancelConsolidationTaskResponse, error) {
	client := pb.NewConsolidationClient(m.cli.Conn())
	return client.CancelConsolidationTask(ctx, in, opts...)
}

// Retry a failed/permanent-failed task (subject to max retry policy).
func (m *defaultConsolidation) RetryConsolidationTask(ctx context.Context, in *RetryConsolidationTaskRequest, opts ...grpc.CallOption) (*RetryConsolidationTaskResponse, error) {
	client := pb.NewConsolidationClient(m.cli.Conn())
	return client.RetryConsolidationTask(ctx, in, opts...)
}

// List logs with filters.
func (m *defaultConsolidation) ListConsolidationLogs(ctx context.Context, in *ListConsolidationLogsRequest, opts ...grpc.CallOption) (*ListConsolidationLogsResponse, error) {
	client := pb.NewConsolidationClient(m.cli.Conn())
	return client.ListConsolidationLogs(ctx, in, opts...)
}

// List top-up records with filters.
func (m *defaultConsolidation) ListConsolidationTopupRecords(ctx context.Context, in *ListConsolidationTopupRecordsRequest, opts ...grpc.CallOption) (*ListConsolidationTopupRecordsResponse, error) {
	client := pb.NewConsolidationClient(m.cli.Conn())
	return client.ListConsolidationTopupRecords(ctx, in, opts...)
}

// List energy rental records with filters.
func (m *defaultConsolidation) ListEnergyRentalRecords(ctx context.Context, in *ListEnergyRentalRecordsRequest, opts ...grpc.CallOption) (*ListEnergyRentalRecordsResponse, error) {
	client := pb.NewConsolidationClient(m.cli.Conn())
	return client.ListEnergyRentalRecords(ctx, in, opts...)
}

// Get energy rental record by ID.
func (m *defaultConsolidation) GetEnergyRentalRecord(ctx context.Context, in *GetEnergyRentalRecordRequest, opts ...grpc.CallOption) (*GetEnergyRentalRecordResponse, error) {
	client := pb.NewConsolidationClient(m.cli.Conn())
	return client.GetEnergyRentalRecord(ctx, in, opts...)
}
