// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: business.proto

package business

import (
	"context"

	"internalwallet/proto/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActionAssetItem                                          = pb.ActionAssetItem
	ActionNetworkItem                                        = pb.ActionNetworkItem
	AddInternalWalletAddressReq                              = pb.AddInternalWalletAddressReq
	AddInternalWalletAddressResp                             = pb.AddInternalWalletAddressResp
	AddWalletAddressReq                                      = pb.AddWalletAddressReq
	AddWalletAddressResp                                     = pb.AddWalletAddressResp
	AddWeb3UserAddressReq                                    = pb.AddWeb3UserAddressReq
	AddWeb3UserAddressResp                                   = pb.AddWeb3UserAddressResp
	AssetConfigItem                                          = pb.AssetConfigItem
	AssetItem                                                = pb.AssetItem
	AssetWithdrawFeeConfigItem                               = pb.AssetWithdrawFeeConfigItem
	AuditTimelineItem                                        = pb.AuditTimelineItem
	BatchAddWeb3UserAddressReq                               = pb.BatchAddWeb3UserAddressReq
	BatchAddWeb3UserAddressResp                              = pb.BatchAddWeb3UserAddressResp
	BatchAddressResult                                       = pb.BatchAddressResult
	BindEmailReq                                             = pb.BindEmailReq
	BindEmailResp                                            = pb.BindEmailResp
	BindGoogleAuthReq                                        = pb.BindGoogleAuthReq
	BindGoogleAuthResp                                       = pb.BindGoogleAuthResp
	BindPhoneReq                                             = pb.BindPhoneReq
	BindPhoneResp                                            = pb.BindPhoneResp
	BiometricProof                                           = pb.BiometricProof
	BroadcastWeb3TransactionReq                              = pb.BroadcastWeb3TransactionReq
	BroadcastWeb3TransactionResp                             = pb.BroadcastWeb3TransactionResp
	BuildTronTransactionReq                                  = pb.BuildTronTransactionReq
	BuildTronTransactionResp                                 = pb.BuildTronTransactionResp
	BusinessClientConfigData                                 = pb.BusinessClientConfigData
	BusinessSwapChainInfo                                    = pb.BusinessSwapChainInfo
	BusinessSwapChainSwapHistoryItem                         = pb.BusinessSwapChainSwapHistoryItem
	BusinessSwapDetailData                                   = pb.BusinessSwapDetailData
	BusinessSwapExecuteSwapData                              = pb.BusinessSwapExecuteSwapData
	BusinessSwapExecuteSwapRequest                           = pb.BusinessSwapExecuteSwapRequest
	BusinessSwapExecuteSwapResponse                          = pb.BusinessSwapExecuteSwapResponse
	BusinessSwapGetApprovalTransactionRequest                = pb.BusinessSwapGetApprovalTransactionRequest
	BusinessSwapGetApprovalTransactionResponse               = pb.BusinessSwapGetApprovalTransactionResponse
	BusinessSwapGetExternalSwapStatusRequest                 = pb.BusinessSwapGetExternalSwapStatusRequest
	BusinessSwapGetExternalSwapStatusResponse                = pb.BusinessSwapGetExternalSwapStatusResponse
	BusinessSwapGetQuoteRequest                              = pb.BusinessSwapGetQuoteRequest
	BusinessSwapGetQuoteResponse                             = pb.BusinessSwapGetQuoteResponse
	BusinessSwapGetSupportedChainsRequest                    = pb.BusinessSwapGetSupportedChainsRequest
	BusinessSwapGetSupportedChainsResponse                   = pb.BusinessSwapGetSupportedChainsResponse
	BusinessSwapGetSupportedTokensRequest                    = pb.BusinessSwapGetSupportedTokensRequest
	BusinessSwapGetSupportedTokensResponse                   = pb.BusinessSwapGetSupportedTokensResponse
	BusinessSwapGetSwapDetailRequest                         = pb.BusinessSwapGetSwapDetailRequest
	BusinessSwapGetSwapDetailResponse                        = pb.BusinessSwapGetSwapDetailResponse
	BusinessSwapGetSwapHistoryRequest                        = pb.BusinessSwapGetSwapHistoryRequest
	BusinessSwapGetSwapHistoryResponse                       = pb.BusinessSwapGetSwapHistoryResponse
	BusinessSwapGetSwapStatusRequest                         = pb.BusinessSwapGetSwapStatusRequest
	BusinessSwapGetSwapStatusResponse                        = pb.BusinessSwapGetSwapStatusResponse
	BusinessSwapHistoryItem                                  = pb.BusinessSwapHistoryItem
	BusinessSwapPagination                                   = pb.BusinessSwapPagination
	BusinessSwapQuoteData                                    = pb.BusinessSwapQuoteData
	BusinessSwapResetApprovalData                            = pb.BusinessSwapResetApprovalData
	BusinessSwapResetApprovalRequest                         = pb.BusinessSwapResetApprovalRequest
	BusinessSwapResetApprovalResponse                        = pb.BusinessSwapResetApprovalResponse
	BusinessSwapStatusData                                   = pb.BusinessSwapStatusData
	BusinessSwapTokenDetail                                  = pb.BusinessSwapTokenDetail
	BusinessSwapTokenInfo                                    = pb.BusinessSwapTokenInfo
	BusinessSwapUnsignedTransaction                          = pb.BusinessSwapUnsignedTransaction
	CalcWithdrawFeeReq                                       = pb.CalcWithdrawFeeReq
	CalcWithdrawFeeResp                                      = pb.CalcWithdrawFeeResp
	CancelInternalTransferReq                                = pb.CancelInternalTransferReq
	CancelInternalTransferResp                               = pb.CancelInternalTransferResp
	ChangeEmailReq                                           = pb.ChangeEmailReq
	ChangeEmailResp                                          = pb.ChangeEmailResp
	ChangePasswordReq                                        = pb.ChangePasswordReq
	ChangePasswordResp                                       = pb.ChangePasswordResp
	ChangePhoneReq                                           = pb.ChangePhoneReq
	ChangePhoneResp                                          = pb.ChangePhoneResp
	ClearAllNotificationsReq                                 = pb.ClearAllNotificationsReq
	ClearAllNotificationsResp                                = pb.ClearAllNotificationsResp
	CreateBiometricChallengeResp                             = pb.CreateBiometricChallengeResp
	CreateDepositAddressBookReq                              = pb.CreateDepositAddressBookReq
	CreateDepositAddressBookResp                             = pb.CreateDepositAddressBookResp
	CreateDepositReq                                         = pb.CreateDepositReq
	CreateDepositResp                                        = pb.CreateDepositResp
	CreateResetTradePasswordBiometricChallengeReq            = pb.CreateResetTradePasswordBiometricChallengeReq
	CreateUserNotificationReq                                = pb.CreateUserNotificationReq
	CreateUserNotificationResp                               = pb.CreateUserNotificationResp
	CreateWeb3UserReq                                        = pb.CreateWeb3UserReq
	CreateWeb3UserResp                                       = pb.CreateWeb3UserResp
	CreateWithdrawAuditWhitelistBindingBiometricChallengeReq = pb.CreateWithdrawAuditWhitelistBindingBiometricChallengeReq
	CreateWithdrawBiometricChallengeReq                      = pb.CreateWithdrawBiometricChallengeReq
	CreateWithdrawReq                                        = pb.CreateWithdrawReq
	CreateWithdrawResp                                       = pb.CreateWithdrawResp
	DeleteDepositAddressBookReq                              = pb.DeleteDepositAddressBookReq
	DeleteDepositAddressBookResp                             = pb.DeleteDepositAddressBookResp
	DeleteInternalWalletAddressReq                           = pb.DeleteInternalWalletAddressReq
	DeleteInternalWalletAddressResp                          = pb.DeleteInternalWalletAddressResp
	DeleteNotificationReq                                    = pb.DeleteNotificationReq
	DeleteNotificationResp                                   = pb.DeleteNotificationResp
	DeleteWalletAddressReq                                   = pb.DeleteWalletAddressReq
	DeleteWalletAddressResp                                  = pb.DeleteWalletAddressResp
	DepositAddressBookItem                                   = pb.DepositAddressBookItem
	DepositAddressItem                                       = pb.DepositAddressItem
	DepositRecordItem                                        = pb.DepositRecordItem
	Device                                                   = pb.Device
	DisableGoogleAuth2FAReq                                  = pb.DisableGoogleAuth2FAReq
	DisableGoogleAuth2FAResp                                 = pb.DisableGoogleAuth2FAResp
	DisableGoogleAuth2FAWithCodeReq                          = pb.DisableGoogleAuth2FAWithCodeReq
	DisableGoogleAuth2FAWithCodeResp                         = pb.DisableGoogleAuth2FAWithCodeResp
	EnableGoogleAuth2FAReq                                   = pb.EnableGoogleAuth2FAReq
	EnableGoogleAuth2FAResp                                  = pb.EnableGoogleAuth2FAResp
	EstimateWithdrawFeeReq                                   = pb.EstimateWithdrawFeeReq
	EstimateWithdrawFeeResp                                  = pb.EstimateWithdrawFeeResp
	FiatRateItem                                             = pb.FiatRateItem
	ForgotPasswordByEmailRequest                             = pb.ForgotPasswordByEmailRequest
	ForgotPasswordByEmailResponse                            = pb.ForgotPasswordByEmailResponse
	ForgotPasswordByPhoneRequest                             = pb.ForgotPasswordByPhoneRequest
	ForgotPasswordByPhoneResponse                            = pb.ForgotPasswordByPhoneResponse
	GetAssetConfigReq                                        = pb.GetAssetConfigReq
	GetAssetConfigResp                                       = pb.GetAssetConfigResp
	GetAssetDetailReq                                        = pb.GetAssetDetailReq
	GetAssetDetailResp                                       = pb.GetAssetDetailResp
	GetAssetOverviewReq                                      = pb.GetAssetOverviewReq
	GetAssetOverviewResp                                     = pb.GetAssetOverviewResp
	GetAssetWithdrawFeeConfigReq                             = pb.GetAssetWithdrawFeeConfigReq
	GetAssetWithdrawFeeConfigResp                            = pb.GetAssetWithdrawFeeConfigResp
	GetClientConfigReq                                       = pb.GetClientConfigReq
	GetClientConfigResp                                      = pb.GetClientConfigResp
	GetCountryCodesRequest                                   = pb.GetCountryCodesRequest
	GetCountryCodesResponse                                  = pb.GetCountryCodesResponse
	GetDepositAddressBookDetailReq                           = pb.GetDepositAddressBookDetailReq
	GetDepositAddressBookDetailResp                          = pb.GetDepositAddressBookDetailResp
	GetDepositDetailReq                                      = pb.GetDepositDetailReq
	GetDepositDetailResp                                     = pb.GetDepositDetailResp
	GetDepositInfoReq                                        = pb.GetDepositInfoReq
	GetDepositInfoResp                                       = pb.GetDepositInfoResp
	GetDevicesReq                                            = pb.GetDevicesReq
	GetDevicesResp                                           = pb.GetDevicesResp
	GetExchangeRateReq                                       = pb.GetExchangeRateReq
	GetExchangeRateResp                                      = pb.GetExchangeRateResp
	GetGoogleAuthSetupReq                                    = pb.GetGoogleAuthSetupReq
	GetGoogleAuthSetupResp                                   = pb.GetGoogleAuthSetupResp
	GetLinkedWalletAccountsReq                               = pb.GetLinkedWalletAccountsReq
	GetLinkedWalletAccountsResp                              = pb.GetLinkedWalletAccountsResp
	GetMyOverviewReq                                         = pb.GetMyOverviewReq
	GetMyOverviewResp                                        = pb.GetMyOverviewResp
	GetMyWithdrawAuditWhitelistBindingStatusReq              = pb.GetMyWithdrawAuditWhitelistBindingStatusReq
	GetMyWithdrawAuditWhitelistBindingStatusResp             = pb.GetMyWithdrawAuditWhitelistBindingStatusResp
	GetPreferencesReq                                        = pb.GetPreferencesReq
	GetPreferencesResp                                       = pb.GetPreferencesResp
	GetTransactionRecordDetailReq                            = pb.GetTransactionRecordDetailReq
	GetTransactionRecordDetailResp                           = pb.GetTransactionRecordDetailResp
	GetUserInfoReq                                           = pb.GetUserInfoReq
	GetUserInfoResp                                          = pb.GetUserInfoResp
	GetWeb3AssetOverviewReq                                  = pb.GetWeb3AssetOverviewReq
	GetWeb3AssetOverviewResp                                 = pb.GetWeb3AssetOverviewResp
	GetWeb3NonceReq                                          = pb.GetWeb3NonceReq
	GetWeb3NonceResp                                         = pb.GetWeb3NonceResp
	GetWeb3TokenDetailReq                                    = pb.GetWeb3TokenDetailReq
	GetWeb3TokenDetailResp                                   = pb.GetWeb3TokenDetailResp
	GetWeb3TransactionDetailReq                              = pb.GetWeb3TransactionDetailReq
	GetWeb3TransactionDetailResp                             = pb.GetWeb3TransactionDetailResp
	GetWeb3TransactionResultReq                              = pb.GetWeb3TransactionResultReq
	GetWeb3TransactionResultResp                             = pb.GetWeb3TransactionResultResp
	GetWeb3UserByDeviceIdReq                                 = pb.GetWeb3UserByDeviceIdReq
	GetWeb3UserByDeviceIdResp                                = pb.GetWeb3UserByDeviceIdResp
	GetWithdrawAuditStatusReq                                = pb.GetWithdrawAuditStatusReq
	GetWithdrawAuditStatusResp                               = pb.GetWithdrawAuditStatusResp
	GetWithdrawDetailReq                                     = pb.GetWithdrawDetailReq
	GetWithdrawDetailResp                                    = pb.GetWithdrawDetailResp
	GetWithdrawInfoReq                                       = pb.GetWithdrawInfoReq
	GetWithdrawInfoResp                                      = pb.GetWithdrawInfoResp
	InternalWalletAddressItem                                = pb.InternalWalletAddressItem
	LanguageItem                                             = pb.LanguageItem
	LinkWalletAccountReq                                     = pb.LinkWalletAccountReq
	LinkWalletAccountResp                                    = pb.LinkWalletAccountResp
	LinkedWalletAccountItem                                  = pb.LinkedWalletAccountItem
	ListActionAssetsReq                                      = pb.ListActionAssetsReq
	ListActionAssetsResp                                     = pb.ListActionAssetsResp
	ListActionNetworksReq                                    = pb.ListActionNetworksReq
	ListActionNetworksResp                                   = pb.ListActionNetworksResp
	ListDepositAddressBookDepositsReq                        = pb.ListDepositAddressBookDepositsReq
	ListDepositAddressBookDepositsResp                       = pb.ListDepositAddressBookDepositsResp
	ListDepositAddressBookReq                                = pb.ListDepositAddressBookReq
	ListDepositAddressBookResp                               = pb.ListDepositAddressBookResp
	ListDepositRecordsReq                                    = pb.ListDepositRecordsReq
	ListDepositRecordsResp                                   = pb.ListDepositRecordsResp
	ListFiatRatesReq                                         = pb.ListFiatRatesReq
	ListFiatRatesResp                                        = pb.ListFiatRatesResp
	ListInternalWalletAddressesReq                           = pb.ListInternalWalletAddressesReq
	ListInternalWalletAddressesResp                          = pb.ListInternalWalletAddressesResp
	ListLanguageOptionsReq                                   = pb.ListLanguageOptionsReq
	ListLanguageOptionsResp                                  = pb.ListLanguageOptionsResp
	ListLoginRecordsReq                                      = pb.ListLoginRecordsReq
	ListLoginRecordsResp                                     = pb.ListLoginRecordsResp
	ListNotificationsReq                                     = pb.ListNotificationsReq
	ListNotificationsResp                                    = pb.ListNotificationsResp
	ListPriceUnitOptionsReq                                  = pb.ListPriceUnitOptionsReq
	ListPriceUnitOptionsResp                                 = pb.ListPriceUnitOptionsResp
	ListProviderAccountsReq                                  = pb.ListProviderAccountsReq
	ListProviderAccountsResp                                 = pb.ListProviderAccountsResp
	ListTransactionRecordsReq                                = pb.ListTransactionRecordsReq
	ListTransactionRecordsResp                               = pb.ListTransactionRecordsResp
	ListWalletAddressesReq                                   = pb.ListWalletAddressesReq
	ListWalletAddressesResp                                  = pb.ListWalletAddressesResp
	ListWalletProvidersReq                                   = pb.ListWalletProvidersReq
	ListWalletProvidersResp                                  = pb.ListWalletProvidersResp
	ListWeb3ChainsReq                                        = pb.ListWeb3ChainsReq
	ListWeb3ChainsResp                                       = pb.ListWeb3ChainsResp
	ListWeb3SupportedAssetsReq                               = pb.ListWeb3SupportedAssetsReq
	ListWeb3SupportedAssetsResp                              = pb.ListWeb3SupportedAssetsResp
	ListWeb3TransactionsReq                                  = pb.ListWeb3TransactionsReq
	ListWeb3TransactionsResp                                 = pb.ListWeb3TransactionsResp
	ListWithdrawAuditWhitelistBindableNetworksReq            = pb.ListWithdrawAuditWhitelistBindableNetworksReq
	ListWithdrawAuditWhitelistBindableNetworksResp           = pb.ListWithdrawAuditWhitelistBindableNetworksResp
	ListWithdrawRecordsReq                                   = pb.ListWithdrawRecordsReq
	ListWithdrawRecordsResp                                  = pb.ListWithdrawRecordsResp
	LoginByEmailCodeRequest                                  = pb.LoginByEmailCodeRequest
	LoginByEmailCodeResponse                                 = pb.LoginByEmailCodeResponse
	LoginByGoogleRequest                                     = pb.LoginByGoogleRequest
	LoginByGoogleResponse                                    = pb.LoginByGoogleResponse
	LoginByPhoneCodeRequest                                  = pb.LoginByPhoneCodeRequest
	LoginByPhoneCodeResponse                                 = pb.LoginByPhoneCodeResponse
	LoginRecordItem                                          = pb.LoginRecordItem
	LogoutReq                                                = pb.LogoutReq
	LogoutResp                                               = pb.LogoutResp
	LookupInternalUserReq                                    = pb.LookupInternalUserReq
	LookupInternalUserResp                                   = pb.LookupInternalUserResp
	MarkAllNotificationsReadReq                              = pb.MarkAllNotificationsReadReq
	MarkAllNotificationsReadResp                             = pb.MarkAllNotificationsReadResp
	MarkNotificationReadReq                                  = pb.MarkNotificationReadReq
	MarkNotificationReadResp                                 = pb.MarkNotificationReadResp
	Notification                                             = pb.Notification
	PriceUnitItem                                            = pb.PriceUnitItem
	ProviderAccountItem                                      = pb.ProviderAccountItem
	RefreshTokenReq                                          = pb.RefreshTokenReq
	RefreshTokenResp                                         = pb.RefreshTokenResp
	RegisterBiometricKeyReq                                  = pb.RegisterBiometricKeyReq
	RegisterBiometricKeyResp                                 = pb.RegisterBiometricKeyResp
	RegisterDeviceReq                                        = pb.RegisterDeviceReq
	RegisterDeviceResp                                       = pb.RegisterDeviceResp
	ResetTradePasswordReq                                    = pb.ResetTradePasswordReq
	ResetTradePasswordResp                                   = pb.ResetTradePasswordResp
	SecurityTip                                              = pb.SecurityTip
	SendEmailCodeReq                                         = pb.SendEmailCodeReq
	SendEmailCodeResp                                        = pb.SendEmailCodeResp
	SendPushNotificationByAliasReq                           = pb.SendPushNotificationByAliasReq
	SendPushNotificationByAliasResp                          = pb.SendPushNotificationByAliasResp
	SendPushNotificationByDeviceTokenReq                     = pb.SendPushNotificationByDeviceTokenReq
	SendPushNotificationByDeviceTokenResp                    = pb.SendPushNotificationByDeviceTokenResp
	SendSMSCodeReq                                           = pb.SendSMSCodeReq
	SendSMSCodeResp                                          = pb.SendSMSCodeResp
	SetAntiPhishingCodeReq                                   = pb.SetAntiPhishingCodeReq
	SetAntiPhishingCodeResp                                  = pb.SetAntiPhishingCodeResp
	SetDefaultDepositAddressBookReq                          = pb.SetDefaultDepositAddressBookReq
	SetDefaultDepositAddressBookResp                         = pb.SetDefaultDepositAddressBookResp
	SetDefaultWalletAddressReq                               = pb.SetDefaultWalletAddressReq
	SetDefaultWalletAddressResp                              = pb.SetDefaultWalletAddressResp
	SetMyWithdrawAuditWhitelistBindingReq                    = pb.SetMyWithdrawAuditWhitelistBindingReq
	SetMyWithdrawAuditWhitelistBindingReqItem                = pb.SetMyWithdrawAuditWhitelistBindingReqItem
	SetMyWithdrawAuditWhitelistBindingResp                   = pb.SetMyWithdrawAuditWhitelistBindingResp
	SetPreferencesReq                                        = pb.SetPreferencesReq
	SetPreferencesResp                                       = pb.SetPreferencesResp
	SetPreferred2FAReq                                       = pb.SetPreferred2FAReq
	SetPreferred2FAResp                                      = pb.SetPreferred2FAResp
	SetPrimaryLinkedWalletReq                                = pb.SetPrimaryLinkedWalletReq
	SetPrimaryLinkedWalletResp                               = pb.SetPrimaryLinkedWalletResp
	SetTradePasswordReq                                      = pb.SetTradePasswordReq
	SetTradePasswordResp                                     = pb.SetTradePasswordResp
	SetWeb3TradePasswordReq                                  = pb.SetWeb3TradePasswordReq
	SetWeb3TradePasswordResp                                 = pb.SetWeb3TradePasswordResp
	SubmitInternalTransferReq                                = pb.SubmitInternalTransferReq
	SubmitInternalTransferResp                               = pb.SubmitInternalTransferResp
	TransactionRecordItem                                    = pb.TransactionRecordItem
	UnbindBiometricReq                                       = pb.UnbindBiometricReq
	UnbindBiometricResp                                      = pb.UnbindBiometricResp
	UnbindGoogleAuthReq                                      = pb.UnbindGoogleAuthReq
	UnbindGoogleAuthResp                                     = pb.UnbindGoogleAuthResp
	UnbindMyWithdrawAuditWhitelistBindingsReq                = pb.UnbindMyWithdrawAuditWhitelistBindingsReq
	UnbindMyWithdrawAuditWhitelistBindingsResp               = pb.UnbindMyWithdrawAuditWhitelistBindingsResp
	UnlinkWalletAccountReq                                   = pb.UnlinkWalletAccountReq
	UnlinkWalletAccountResp                                  = pb.UnlinkWalletAccountResp
	UpdateDepositAddressBookReq                              = pb.UpdateDepositAddressBookReq
	UpdateDepositAddressBookResp                             = pb.UpdateDepositAddressBookResp
	UpdateInternalWalletAddressReq                           = pb.UpdateInternalWalletAddressReq
	UpdateInternalWalletAddressResp                          = pb.UpdateInternalWalletAddressResp
	UpdateUserInfoReq                                        = pb.UpdateUserInfoReq
	UpdateUserInfoResp                                       = pb.UpdateUserInfoResp
	UpdateWalletAddressReq                                   = pb.UpdateWalletAddressReq
	UpdateWalletAddressResp                                  = pb.UpdateWalletAddressResp
	UpdateWeb3TradePasswordReq                               = pb.UpdateWeb3TradePasswordReq
	UpdateWeb3TradePasswordResp                              = pb.UpdateWeb3TradePasswordResp
	UploadAvatarReq                                          = pb.UploadAvatarReq
	UploadAvatarResp                                         = pb.UploadAvatarResp
	ValidateGeetestRequest                                   = pb.ValidateGeetestRequest
	ValidateGeetestResponse                                  = pb.ValidateGeetestResponse
	ValidateInternalTransferTargetReq                        = pb.ValidateInternalTransferTargetReq
	ValidateInternalTransferTargetResp                       = pb.ValidateInternalTransferTargetResp
	ValidateWalletAddressReq                                 = pb.ValidateWalletAddressReq
	ValidateWalletAddressResp                                = pb.ValidateWalletAddressResp
	Verify2FAReq                                             = pb.Verify2FAReq
	Verify2FAResp                                            = pb.Verify2FAResp
	VerifyGoogleAuthCodeReq                                  = pb.VerifyGoogleAuthCodeReq
	VerifyGoogleAuthCodeResp                                 = pb.VerifyGoogleAuthCodeResp
	VerifyTradePasswordReq                                   = pb.VerifyTradePasswordReq
	VerifyTradePasswordResp                                  = pb.VerifyTradePasswordResp
	VerifyWeb3TradePasswordReq                               = pb.VerifyWeb3TradePasswordReq
	VerifyWeb3TradePasswordResp                              = pb.VerifyWeb3TradePasswordResp
	WalletAddressItem                                        = pb.WalletAddressItem
	WalletProviderItem                                       = pb.WalletProviderItem
	Web3AddressItem                                          = pb.Web3AddressItem
	Web3AssetItem                                            = pb.Web3AssetItem
	Web3ChainItem                                            = pb.Web3ChainItem
	Web3SupportedAssetItem                                   = pb.Web3SupportedAssetItem
	Web3TransactionItem                                      = pb.Web3TransactionItem
	Web3UserInfo                                             = pb.Web3UserInfo
	WhitelistAddressItem                                     = pb.WhitelistAddressItem
	WithdrawAuditWhitelistBindingItem                        = pb.WithdrawAuditWhitelistBindingItem
	WithdrawAuditWhitelistBindingStatusItem                  = pb.WithdrawAuditWhitelistBindingStatusItem
	WithdrawRecordItem                                       = pb.WithdrawRecordItem

	Business interface {
		// ==================== Auth ====================
		LoginByEmailCode(ctx context.Context, in *LoginByEmailCodeRequest, opts ...grpc.CallOption) (*LoginByEmailCodeResponse, error)
		// 登录（手机+验证码）
		LoginByPhoneCode(ctx context.Context, in *LoginByPhoneCodeRequest, opts ...grpc.CallOption) (*LoginByPhoneCodeResponse, error)
		// 登录（Google OAuth）
		LoginByGoogle(ctx context.Context, in *LoginByGoogleRequest, opts ...grpc.CallOption) (*LoginByGoogleResponse, error)
		// 忘记密码（邮箱+验证码）
		ForgotPasswordByEmail(ctx context.Context, in *ForgotPasswordByEmailRequest, opts ...grpc.CallOption) (*ForgotPasswordByEmailResponse, error)
		// 忘记密码（手机+验证码）
		ForgotPasswordByPhone(ctx context.Context, in *ForgotPasswordByPhoneRequest, opts ...grpc.CallOption) (*ForgotPasswordByPhoneResponse, error)
		// Geetest 验证
		ValidateGeetest(ctx context.Context, in *ValidateGeetestRequest, opts ...grpc.CallOption) (*ValidateGeetestResponse, error)
		// 获取支持的国家/地区区号
		GetCountryCodes(ctx context.Context, in *GetCountryCodesRequest, opts ...grpc.CallOption) (*GetCountryCodesResponse, error)
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
		SendSMSCode(ctx context.Context, in *SendSMSCodeReq, opts ...grpc.CallOption) (*SendSMSCodeResp, error)
		SendEmailCode(ctx context.Context, in *SendEmailCodeReq, opts ...grpc.CallOption) (*SendEmailCodeResp, error)
		// 登出
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error)
		// 资产页
		GetAssetOverview(ctx context.Context, in *GetAssetOverviewReq, opts ...grpc.CallOption) (*GetAssetOverviewResp, error)
		GetAssetDetail(ctx context.Context, in *GetAssetDetailReq, opts ...grpc.CallOption) (*GetAssetDetailResp, error)
		// 获取所有资产配置（包含精度等信息）
		GetAssetConfig(ctx context.Context, in *GetAssetConfigReq, opts ...grpc.CallOption) (*GetAssetConfigResp, error)
		ListTransactionRecords(ctx context.Context, in *ListTransactionRecordsReq, opts ...grpc.CallOption) (*ListTransactionRecordsResp, error)
		GetTransactionRecordDetail(ctx context.Context, in *GetTransactionRecordDetailReq, opts ...grpc.CallOption) (*GetTransactionRecordDetailResp, error)
		GetDepositInfo(ctx context.Context, in *GetDepositInfoReq, opts ...grpc.CallOption) (*GetDepositInfoResp, error)
		CreateDeposit(ctx context.Context, in *CreateDepositReq, opts ...grpc.CallOption) (*CreateDepositResp, error)
		ListDepositRecords(ctx context.Context, in *ListDepositRecordsReq, opts ...grpc.CallOption) (*ListDepositRecordsResp, error)
		GetDepositDetail(ctx context.Context, in *GetDepositDetailReq, opts ...grpc.CallOption) (*GetDepositDetailResp, error)
		// 资产-充值地址簿（同链多地址）
		ListDepositAddressBook(ctx context.Context, in *ListDepositAddressBookReq, opts ...grpc.CallOption) (*ListDepositAddressBookResp, error)
		CreateDepositAddressBook(ctx context.Context, in *CreateDepositAddressBookReq, opts ...grpc.CallOption) (*CreateDepositAddressBookResp, error)
		GetDepositAddressBookDetail(ctx context.Context, in *GetDepositAddressBookDetailReq, opts ...grpc.CallOption) (*GetDepositAddressBookDetailResp, error)
		UpdateDepositAddressBook(ctx context.Context, in *UpdateDepositAddressBookReq, opts ...grpc.CallOption) (*UpdateDepositAddressBookResp, error)
		DeleteDepositAddressBook(ctx context.Context, in *DeleteDepositAddressBookReq, opts ...grpc.CallOption) (*DeleteDepositAddressBookResp, error)
		SetDefaultDepositAddressBook(ctx context.Context, in *SetDefaultDepositAddressBookReq, opts ...grpc.CallOption) (*SetDefaultDepositAddressBookResp, error)
		ListDepositAddressBookDeposits(ctx context.Context, in *ListDepositAddressBookDepositsReq, opts ...grpc.CallOption) (*ListDepositAddressBookDepositsResp, error)
		ListActionAssets(ctx context.Context, in *ListActionAssetsReq, opts ...grpc.CallOption) (*ListActionAssetsResp, error)
		ListActionNetworks(ctx context.Context, in *ListActionNetworksReq, opts ...grpc.CallOption) (*ListActionNetworksResp, error)
		// 资产页-币种提现手续费规则配置查询
		GetAssetWithdrawFeeConfig(ctx context.Context, in *GetAssetWithdrawFeeConfigReq, opts ...grpc.CallOption) (*GetAssetWithdrawFeeConfigResp, error)
		// 资产页-汇率查询
		GetExchangeRate(ctx context.Context, in *GetExchangeRateReq, opts ...grpc.CallOption) (*GetExchangeRateResp, error)
		// 资产页-法币汇率列表（1 USDT = n 法币）
		ListFiatRates(ctx context.Context, in *ListFiatRatesReq, opts ...grpc.CallOption) (*ListFiatRatesResp, error)
		GetWithdrawInfo(ctx context.Context, in *GetWithdrawInfoReq, opts ...grpc.CallOption) (*GetWithdrawInfoResp, error)
		// Web2 提币手续费预估（仅计算手续费规则，不构建链上交易，不使用 Web3 gas 接口）
		EstimateWithdrawFee(ctx context.Context, in *EstimateWithdrawFeeReq, opts ...grpc.CallOption) (*EstimateWithdrawFeeResp, error)
		// Web2 提币手续费计算（校验余额；返回 fee/min_withdraw_amount/required_amount）
		CalcWithdrawFee(ctx context.Context, in *CalcWithdrawFeeReq, opts ...grpc.CallOption) (*CalcWithdrawFeeResp, error)
		CreateWithdraw(ctx context.Context, in *CreateWithdrawReq, opts ...grpc.CallOption) (*CreateWithdrawResp, error)
		ListWithdrawRecords(ctx context.Context, in *ListWithdrawRecordsReq, opts ...grpc.CallOption) (*ListWithdrawRecordsResp, error)
		GetWithdrawAuditStatus(ctx context.Context, in *GetWithdrawAuditStatusReq, opts ...grpc.CallOption) (*GetWithdrawAuditStatusResp, error)
		GetWithdrawDetail(ctx context.Context, in *GetWithdrawDetailReq, opts ...grpc.CallOption) (*GetWithdrawDetailResp, error)
		// 资产页-消息通知（Web2 用户）
		ListNotifications(ctx context.Context, in *ListNotificationsReq, opts ...grpc.CallOption) (*ListNotificationsResp, error)
		MarkNotificationRead(ctx context.Context, in *MarkNotificationReadReq, opts ...grpc.CallOption) (*MarkNotificationReadResp, error)
		MarkAllNotificationsRead(ctx context.Context, in *MarkAllNotificationsReadReq, opts ...grpc.CallOption) (*MarkAllNotificationsReadResp, error)
		DeleteNotification(ctx context.Context, in *DeleteNotificationReq, opts ...grpc.CallOption) (*DeleteNotificationResp, error)
		ClearAllNotifications(ctx context.Context, in *ClearAllNotificationsReq, opts ...grpc.CallOption) (*ClearAllNotificationsResp, error)
		// 内部接口：创建消息通知（供业务逻辑调用）
		CreateUserNotification(ctx context.Context, in *CreateUserNotificationReq, opts ...grpc.CallOption) (*CreateUserNotificationResp, error)
		// 推送通知：通过别名发送推送（供业务逻辑调用）
		SendPushNotificationByAlias(ctx context.Context, in *SendPushNotificationByAliasReq, opts ...grpc.CallOption) (*SendPushNotificationByAliasResp, error)
		// 推送通知：通过设备ID发送推送（Web3用户专用）
		SendPushNotificationByDeviceToken(ctx context.Context, in *SendPushNotificationByDeviceTokenReq, opts ...grpc.CallOption) (*SendPushNotificationByDeviceTokenResp, error)
		// 设备管理：注册设备（Web3用户专用）
		RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceResp, error)
		GetMyOverview(ctx context.Context, in *GetMyOverviewReq, opts ...grpc.CallOption) (*GetMyOverviewResp, error)
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error)
		BindEmail(ctx context.Context, in *BindEmailReq, opts ...grpc.CallOption) (*BindEmailResp, error)
		ChangeEmail(ctx context.Context, in *ChangeEmailReq, opts ...grpc.CallOption) (*ChangeEmailResp, error)
		// 我的页-手机号
		BindPhone(ctx context.Context, in *BindPhoneReq, opts ...grpc.CallOption) (*BindPhoneResp, error)
		ChangePhone(ctx context.Context, in *ChangePhoneReq, opts ...grpc.CallOption) (*ChangePhoneResp, error)
		ListWalletProviders(ctx context.Context, in *ListWalletProvidersReq, opts ...grpc.CallOption) (*ListWalletProvidersResp, error)
		ListProviderAccounts(ctx context.Context, in *ListProviderAccountsReq, opts ...grpc.CallOption) (*ListProviderAccountsResp, error)
		LinkWalletAccount(ctx context.Context, in *LinkWalletAccountReq, opts ...grpc.CallOption) (*LinkWalletAccountResp, error)
		UnlinkWalletAccount(ctx context.Context, in *UnlinkWalletAccountReq, opts ...grpc.CallOption) (*UnlinkWalletAccountResp, error)
		SetPrimaryLinkedWallet(ctx context.Context, in *SetPrimaryLinkedWalletReq, opts ...grpc.CallOption) (*SetPrimaryLinkedWalletResp, error)
		GetLinkedWalletAccounts(ctx context.Context, in *GetLinkedWalletAccountsReq, opts ...grpc.CallOption) (*GetLinkedWalletAccountsResp, error)
		// 我的页-登录密码
		ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*ChangePasswordResp, error)
		SetTradePassword(ctx context.Context, in *SetTradePasswordReq, opts ...grpc.CallOption) (*SetTradePasswordResp, error)
		ResetTradePassword(ctx context.Context, in *ResetTradePasswordReq, opts ...grpc.CallOption) (*ResetTradePasswordResp, error)
		VerifyTradePassword(ctx context.Context, in *VerifyTradePasswordReq, opts ...grpc.CallOption) (*VerifyTradePasswordResp, error)
		// 我的页-Web3交易密码
		SetWeb3TradePassword(ctx context.Context, in *SetWeb3TradePasswordReq, opts ...grpc.CallOption) (*SetWeb3TradePasswordResp, error)
		VerifyWeb3TradePassword(ctx context.Context, in *VerifyWeb3TradePasswordReq, opts ...grpc.CallOption) (*VerifyWeb3TradePasswordResp, error)
		UpdateWeb3TradePassword(ctx context.Context, in *UpdateWeb3TradePasswordReq, opts ...grpc.CallOption) (*UpdateWeb3TradePasswordResp, error)
		// 我的页-使用设置-生物识别（Web2）
		RegisterBiometricKey(ctx context.Context, in *RegisterBiometricKeyReq, opts ...grpc.CallOption) (*RegisterBiometricKeyResp, error)
		// 创建提币生物识别挑战（用于签名）
		CreateWithdrawBiometricChallenge(ctx context.Context, in *CreateWithdrawBiometricChallengeReq, opts ...grpc.CallOption) (*CreateBiometricChallengeResp, error)
		// 创建提现免审白名单绑定生物识别挑战（用于签名）
		CreateWithdrawAuditWhitelistBindingBiometricChallenge(ctx context.Context, in *CreateWithdrawAuditWhitelistBindingBiometricChallengeReq, opts ...grpc.CallOption) (*CreateBiometricChallengeResp, error)
		// 创建重置交易密码生物识别挑战（用于签名）
		CreateResetTradePasswordBiometricChallenge(ctx context.Context, in *CreateResetTradePasswordBiometricChallengeReq, opts ...grpc.CallOption) (*CreateBiometricChallengeResp, error)
		// 解绑当前用户生物识别（仅交易密码）
		UnbindBiometric(ctx context.Context, in *UnbindBiometricReq, opts ...grpc.CallOption) (*UnbindBiometricResp, error)
		// 我的页-使用设置-双重认证
		GetGoogleAuthSetup(ctx context.Context, in *GetGoogleAuthSetupReq, opts ...grpc.CallOption) (*GetGoogleAuthSetupResp, error)
		// 绑定 Google 验证器
		BindGoogleAuth(ctx context.Context, in *BindGoogleAuthReq, opts ...grpc.CallOption) (*BindGoogleAuthResp, error)
		// 解绑 Google 验证器
		UnbindGoogleAuth(ctx context.Context, in *UnbindGoogleAuthReq, opts ...grpc.CallOption) (*UnbindGoogleAuthResp, error)
		// 关闭双重认证（不解绑 Google 验证器）
		DisableGoogleAuth2FA(ctx context.Context, in *DisableGoogleAuth2FAReq, opts ...grpc.CallOption) (*DisableGoogleAuth2FAResp, error)
		// 开启双重认证（已绑定GA，传验证码开启）
		EnableGoogleAuth2FA(ctx context.Context, in *EnableGoogleAuth2FAReq, opts ...grpc.CallOption) (*EnableGoogleAuth2FAResp, error)
		// 关闭双重认证（已绑定GA，传验证码关闭）
		DisableGoogleAuth2FAWithCode(ctx context.Context, in *DisableGoogleAuth2FAWithCodeReq, opts ...grpc.CallOption) (*DisableGoogleAuth2FAWithCodeResp, error)
		// 校验Google验证器验证码（仅校验，不做任何状态修改）
		VerifyGoogleAuthCode(ctx context.Context, in *VerifyGoogleAuthCodeReq, opts ...grpc.CallOption) (*VerifyGoogleAuthCodeResp, error)
		// 我的页-使用设置－登录记录
		ListLoginRecords(ctx context.Context, in *ListLoginRecordsReq, opts ...grpc.CallOption) (*ListLoginRecordsResp, error)
		// 我的页-使用设置－钱包地址（链上地址）
		ListWalletAddresses(ctx context.Context, in *ListWalletAddressesReq, opts ...grpc.CallOption) (*ListWalletAddressesResp, error)
		AddWalletAddress(ctx context.Context, in *AddWalletAddressReq, opts ...grpc.CallOption) (*AddWalletAddressResp, error)
		UpdateWalletAddress(ctx context.Context, in *UpdateWalletAddressReq, opts ...grpc.CallOption) (*UpdateWalletAddressResp, error)
		DeleteWalletAddress(ctx context.Context, in *DeleteWalletAddressReq, opts ...grpc.CallOption) (*DeleteWalletAddressResp, error)
		SetDefaultWalletAddress(ctx context.Context, in *SetDefaultWalletAddressReq, opts ...grpc.CallOption) (*SetDefaultWalletAddressResp, error)
		ValidateWalletAddress(ctx context.Context, in *ValidateWalletAddressReq, opts ...grpc.CallOption) (*ValidateWalletAddressResp, error)
		// 我的页-使用设置－钱包地址（内部地址，通过UID/邮箱添加平台内用户）
		ListInternalWalletAddresses(ctx context.Context, in *ListInternalWalletAddressesReq, opts ...grpc.CallOption) (*ListInternalWalletAddressesResp, error)
		AddInternalWalletAddress(ctx context.Context, in *AddInternalWalletAddressReq, opts ...grpc.CallOption) (*AddInternalWalletAddressResp, error)
		UpdateInternalWalletAddress(ctx context.Context, in *UpdateInternalWalletAddressReq, opts ...grpc.CallOption) (*UpdateInternalWalletAddressResp, error)
		DeleteInternalWalletAddress(ctx context.Context, in *DeleteInternalWalletAddressReq, opts ...grpc.CallOption) (*DeleteInternalWalletAddressResp, error)
		LookupInternalUser(ctx context.Context, in *LookupInternalUserReq, opts ...grpc.CallOption) (*LookupInternalUserResp, error)
		// 内部转账（用户之间的资产转移，支持审核）
		ValidateInternalTransferTarget(ctx context.Context, in *ValidateInternalTransferTargetReq, opts ...grpc.CallOption) (*ValidateInternalTransferTargetResp, error)
		SubmitInternalTransfer(ctx context.Context, in *SubmitInternalTransferReq, opts ...grpc.CallOption) (*SubmitInternalTransferResp, error)
		CancelInternalTransfer(ctx context.Context, in *CancelInternalTransferReq, opts ...grpc.CallOption) (*CancelInternalTransferResp, error)
		// 提现免审白名单（用户自绑定）
		ListWithdrawAuditWhitelistBindableNetworks(ctx context.Context, in *ListWithdrawAuditWhitelistBindableNetworksReq, opts ...grpc.CallOption) (*ListWithdrawAuditWhitelistBindableNetworksResp, error)
		SetMyWithdrawAuditWhitelistBinding(ctx context.Context, in *SetMyWithdrawAuditWhitelistBindingReq, opts ...grpc.CallOption) (*SetMyWithdrawAuditWhitelistBindingResp, error)
		GetMyWithdrawAuditWhitelistBindingStatus(ctx context.Context, in *GetMyWithdrawAuditWhitelistBindingStatusReq, opts ...grpc.CallOption) (*GetMyWithdrawAuditWhitelistBindingStatusResp, error)
		UnbindMyWithdrawAuditWhitelistBindings(ctx context.Context, in *UnbindMyWithdrawAuditWhitelistBindingsReq, opts ...grpc.CallOption) (*UnbindMyWithdrawAuditWhitelistBindingsResp, error)
		// 我的页-偏好设置
		GetPreferences(ctx context.Context, in *GetPreferencesReq, opts ...grpc.CallOption) (*GetPreferencesResp, error)
		ListLanguageOptions(ctx context.Context, in *ListLanguageOptionsReq, opts ...grpc.CallOption) (*ListLanguageOptionsResp, error)
		ListPriceUnitOptions(ctx context.Context, in *ListPriceUnitOptionsReq, opts ...grpc.CallOption) (*ListPriceUnitOptionsResp, error)
		SetPreferences(ctx context.Context, in *SetPreferencesReq, opts ...grpc.CallOption) (*SetPreferencesResp, error)
		// 获取客户端配置
		GetClientConfig(ctx context.Context, in *GetClientConfigReq, opts ...grpc.CallOption) (*GetClientConfigResp, error)
		// ==================== Web3 Swap (proxy to swap microservice) ====================
		SwapGetQuote(ctx context.Context, in *BusinessSwapGetQuoteRequest, opts ...grpc.CallOption) (*BusinessSwapGetQuoteResponse, error)
		SwapExecuteSwap(ctx context.Context, in *BusinessSwapExecuteSwapRequest, opts ...grpc.CallOption) (*BusinessSwapExecuteSwapResponse, error)
		SwapGetApprovalTransaction(ctx context.Context, in *BusinessSwapGetApprovalTransactionRequest, opts ...grpc.CallOption) (*BusinessSwapGetApprovalTransactionResponse, error)
		SwapResetApproval(ctx context.Context, in *BusinessSwapResetApprovalRequest, opts ...grpc.CallOption) (*BusinessSwapResetApprovalResponse, error)
		SwapGetSwapStatus(ctx context.Context, in *BusinessSwapGetSwapStatusRequest, opts ...grpc.CallOption) (*BusinessSwapGetSwapStatusResponse, error)
		SwapGetSwapDetail(ctx context.Context, in *BusinessSwapGetSwapDetailRequest, opts ...grpc.CallOption) (*BusinessSwapGetSwapDetailResponse, error)
		SwapGetSwapHistory(ctx context.Context, in *BusinessSwapGetSwapHistoryRequest, opts ...grpc.CallOption) (*BusinessSwapGetSwapHistoryResponse, error)
		SwapGetSupportedTokens(ctx context.Context, in *BusinessSwapGetSupportedTokensRequest, opts ...grpc.CallOption) (*BusinessSwapGetSupportedTokensResponse, error)
		SwapGetSupportedChains(ctx context.Context, in *BusinessSwapGetSupportedChainsRequest, opts ...grpc.CallOption) (*BusinessSwapGetSupportedChainsResponse, error)
		SwapGetExternalSwapStatus(ctx context.Context, in *BusinessSwapGetExternalSwapStatusRequest, opts ...grpc.CallOption) (*BusinessSwapGetExternalSwapStatusResponse, error)
		// ==================== Web3 User Management ====================
		CreateWeb3User(ctx context.Context, in *CreateWeb3UserReq, opts ...grpc.CallOption) (*CreateWeb3UserResp, error)
		// 添加 Web3 用户地址
		AddWeb3UserAddress(ctx context.Context, in *AddWeb3UserAddressReq, opts ...grpc.CallOption) (*AddWeb3UserAddressResp, error)
		// 批量添加 Web3 用户地址（一次添加多条链的地址）
		BatchAddWeb3UserAddress(ctx context.Context, in *BatchAddWeb3UserAddressReq, opts ...grpc.CallOption) (*BatchAddWeb3UserAddressResp, error)
		// 查询可用链列表（Web3 用户）
		ListWeb3Chains(ctx context.Context, in *ListWeb3ChainsReq, opts ...grpc.CallOption) (*ListWeb3ChainsResp, error)
		// 根据 device_id 获取 Web3 用户信息
		GetWeb3UserByDeviceId(ctx context.Context, in *GetWeb3UserByDeviceIdReq, opts ...grpc.CallOption) (*GetWeb3UserByDeviceIdResp, error)
		// 获取 Web3 用户资产概览
		GetWeb3AssetOverview(ctx context.Context, in *GetWeb3AssetOverviewReq, opts ...grpc.CallOption) (*GetWeb3AssetOverviewResp, error)
		// 获取 Web3 用户交易记录列表
		ListWeb3Transactions(ctx context.Context, in *ListWeb3TransactionsReq, opts ...grpc.CallOption) (*ListWeb3TransactionsResp, error)
		// 获取 Web3 交易详情
		GetWeb3TransactionDetail(ctx context.Context, in *GetWeb3TransactionDetailReq, opts ...grpc.CallOption) (*GetWeb3TransactionDetailResp, error)
		// Web3 交易结果查询（根据交易哈希查询状态和结果）
		GetWeb3TransactionResult(ctx context.Context, in *GetWeb3TransactionResultReq, opts ...grpc.CallOption) (*GetWeb3TransactionResultResp, error)
		// 广播 Web3 交易（Web3 用户专用）
		BroadcastWeb3Transaction(ctx context.Context, in *BroadcastWeb3TransactionReq, opts ...grpc.CallOption) (*BroadcastWeb3TransactionResp, error)
		// 获取 Web3 支持的资产列表（根据链）
		ListWeb3SupportedAssets(ctx context.Context, in *ListWeb3SupportedAssetsReq, opts ...grpc.CallOption) (*ListWeb3SupportedAssetsResp, error)
		// 获取 Web3 用户地址的 Nonce（用于构建 EVM 交易）
		GetWeb3Nonce(ctx context.Context, in *GetWeb3NonceReq, opts ...grpc.CallOption) (*GetWeb3NonceResp, error)
		// 构建 Web3 TRON 交易（返回未签名的 rawData，供客户端签名）
		BuildTronTransaction(ctx context.Context, in *BuildTronTransactionReq, opts ...grpc.CallOption) (*BuildTronTransactionResp, error)
		// 获取 Web3 代币详细信息（合约地址、网络、价格、市值、持有者等）
		GetWeb3TokenDetail(ctx context.Context, in *GetWeb3TokenDetailReq, opts ...grpc.CallOption) (*GetWeb3TokenDetailResp, error)
	}

	defaultBusiness struct {
		cli zrpc.Client
	}
)

func NewBusiness(cli zrpc.Client) Business {
	return &defaultBusiness{
		cli: cli,
	}
}

// ==================== Auth ====================
func (m *defaultBusiness) LoginByEmailCode(ctx context.Context, in *LoginByEmailCodeRequest, opts ...grpc.CallOption) (*LoginByEmailCodeResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.LoginByEmailCode(ctx, in, opts...)
}

// 登录（手机+验证码）
func (m *defaultBusiness) LoginByPhoneCode(ctx context.Context, in *LoginByPhoneCodeRequest, opts ...grpc.CallOption) (*LoginByPhoneCodeResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.LoginByPhoneCode(ctx, in, opts...)
}

// 登录（Google OAuth）
func (m *defaultBusiness) LoginByGoogle(ctx context.Context, in *LoginByGoogleRequest, opts ...grpc.CallOption) (*LoginByGoogleResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.LoginByGoogle(ctx, in, opts...)
}

// 忘记密码（邮箱+验证码）
func (m *defaultBusiness) ForgotPasswordByEmail(ctx context.Context, in *ForgotPasswordByEmailRequest, opts ...grpc.CallOption) (*ForgotPasswordByEmailResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ForgotPasswordByEmail(ctx, in, opts...)
}

// 忘记密码（手机+验证码）
func (m *defaultBusiness) ForgotPasswordByPhone(ctx context.Context, in *ForgotPasswordByPhoneRequest, opts ...grpc.CallOption) (*ForgotPasswordByPhoneResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ForgotPasswordByPhone(ctx, in, opts...)
}

// Geetest 验证
func (m *defaultBusiness) ValidateGeetest(ctx context.Context, in *ValidateGeetestRequest, opts ...grpc.CallOption) (*ValidateGeetestResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ValidateGeetest(ctx, in, opts...)
}

// 获取支持的国家/地区区号
func (m *defaultBusiness) GetCountryCodes(ctx context.Context, in *GetCountryCodesRequest, opts ...grpc.CallOption) (*GetCountryCodesResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetCountryCodes(ctx, in, opts...)
}

func (m *defaultBusiness) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

func (m *defaultBusiness) SendSMSCode(ctx context.Context, in *SendSMSCodeReq, opts ...grpc.CallOption) (*SendSMSCodeResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SendSMSCode(ctx, in, opts...)
}

func (m *defaultBusiness) SendEmailCode(ctx context.Context, in *SendEmailCodeReq, opts ...grpc.CallOption) (*SendEmailCodeResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SendEmailCode(ctx, in, opts...)
}

// 登出
func (m *defaultBusiness) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

// 资产页
func (m *defaultBusiness) GetAssetOverview(ctx context.Context, in *GetAssetOverviewReq, opts ...grpc.CallOption) (*GetAssetOverviewResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetAssetOverview(ctx, in, opts...)
}

func (m *defaultBusiness) GetAssetDetail(ctx context.Context, in *GetAssetDetailReq, opts ...grpc.CallOption) (*GetAssetDetailResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetAssetDetail(ctx, in, opts...)
}

// 获取所有资产配置（包含精度等信息）
func (m *defaultBusiness) GetAssetConfig(ctx context.Context, in *GetAssetConfigReq, opts ...grpc.CallOption) (*GetAssetConfigResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetAssetConfig(ctx, in, opts...)
}

func (m *defaultBusiness) ListTransactionRecords(ctx context.Context, in *ListTransactionRecordsReq, opts ...grpc.CallOption) (*ListTransactionRecordsResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListTransactionRecords(ctx, in, opts...)
}

func (m *defaultBusiness) GetTransactionRecordDetail(ctx context.Context, in *GetTransactionRecordDetailReq, opts ...grpc.CallOption) (*GetTransactionRecordDetailResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetTransactionRecordDetail(ctx, in, opts...)
}

func (m *defaultBusiness) GetDepositInfo(ctx context.Context, in *GetDepositInfoReq, opts ...grpc.CallOption) (*GetDepositInfoResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetDepositInfo(ctx, in, opts...)
}

func (m *defaultBusiness) CreateDeposit(ctx context.Context, in *CreateDepositReq, opts ...grpc.CallOption) (*CreateDepositResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.CreateDeposit(ctx, in, opts...)
}

func (m *defaultBusiness) ListDepositRecords(ctx context.Context, in *ListDepositRecordsReq, opts ...grpc.CallOption) (*ListDepositRecordsResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListDepositRecords(ctx, in, opts...)
}

func (m *defaultBusiness) GetDepositDetail(ctx context.Context, in *GetDepositDetailReq, opts ...grpc.CallOption) (*GetDepositDetailResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetDepositDetail(ctx, in, opts...)
}

// 资产-充值地址簿（同链多地址）
func (m *defaultBusiness) ListDepositAddressBook(ctx context.Context, in *ListDepositAddressBookReq, opts ...grpc.CallOption) (*ListDepositAddressBookResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListDepositAddressBook(ctx, in, opts...)
}

func (m *defaultBusiness) CreateDepositAddressBook(ctx context.Context, in *CreateDepositAddressBookReq, opts ...grpc.CallOption) (*CreateDepositAddressBookResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.CreateDepositAddressBook(ctx, in, opts...)
}

func (m *defaultBusiness) GetDepositAddressBookDetail(ctx context.Context, in *GetDepositAddressBookDetailReq, opts ...grpc.CallOption) (*GetDepositAddressBookDetailResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetDepositAddressBookDetail(ctx, in, opts...)
}

func (m *defaultBusiness) UpdateDepositAddressBook(ctx context.Context, in *UpdateDepositAddressBookReq, opts ...grpc.CallOption) (*UpdateDepositAddressBookResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.UpdateDepositAddressBook(ctx, in, opts...)
}

func (m *defaultBusiness) DeleteDepositAddressBook(ctx context.Context, in *DeleteDepositAddressBookReq, opts ...grpc.CallOption) (*DeleteDepositAddressBookResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.DeleteDepositAddressBook(ctx, in, opts...)
}

func (m *defaultBusiness) SetDefaultDepositAddressBook(ctx context.Context, in *SetDefaultDepositAddressBookReq, opts ...grpc.CallOption) (*SetDefaultDepositAddressBookResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SetDefaultDepositAddressBook(ctx, in, opts...)
}

func (m *defaultBusiness) ListDepositAddressBookDeposits(ctx context.Context, in *ListDepositAddressBookDepositsReq, opts ...grpc.CallOption) (*ListDepositAddressBookDepositsResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListDepositAddressBookDeposits(ctx, in, opts...)
}

func (m *defaultBusiness) ListActionAssets(ctx context.Context, in *ListActionAssetsReq, opts ...grpc.CallOption) (*ListActionAssetsResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListActionAssets(ctx, in, opts...)
}

func (m *defaultBusiness) ListActionNetworks(ctx context.Context, in *ListActionNetworksReq, opts ...grpc.CallOption) (*ListActionNetworksResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListActionNetworks(ctx, in, opts...)
}

// 资产页-币种提现手续费规则配置查询
func (m *defaultBusiness) GetAssetWithdrawFeeConfig(ctx context.Context, in *GetAssetWithdrawFeeConfigReq, opts ...grpc.CallOption) (*GetAssetWithdrawFeeConfigResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetAssetWithdrawFeeConfig(ctx, in, opts...)
}

// 资产页-汇率查询
func (m *defaultBusiness) GetExchangeRate(ctx context.Context, in *GetExchangeRateReq, opts ...grpc.CallOption) (*GetExchangeRateResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetExchangeRate(ctx, in, opts...)
}

// 资产页-法币汇率列表（1 USDT = n 法币）
func (m *defaultBusiness) ListFiatRates(ctx context.Context, in *ListFiatRatesReq, opts ...grpc.CallOption) (*ListFiatRatesResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListFiatRates(ctx, in, opts...)
}

func (m *defaultBusiness) GetWithdrawInfo(ctx context.Context, in *GetWithdrawInfoReq, opts ...grpc.CallOption) (*GetWithdrawInfoResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetWithdrawInfo(ctx, in, opts...)
}

// Web2 提币手续费预估（仅计算手续费规则，不构建链上交易，不使用 Web3 gas 接口）
func (m *defaultBusiness) EstimateWithdrawFee(ctx context.Context, in *EstimateWithdrawFeeReq, opts ...grpc.CallOption) (*EstimateWithdrawFeeResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.EstimateWithdrawFee(ctx, in, opts...)
}

// Web2 提币手续费计算（校验余额；返回 fee/min_withdraw_amount/required_amount）
func (m *defaultBusiness) CalcWithdrawFee(ctx context.Context, in *CalcWithdrawFeeReq, opts ...grpc.CallOption) (*CalcWithdrawFeeResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.CalcWithdrawFee(ctx, in, opts...)
}

func (m *defaultBusiness) CreateWithdraw(ctx context.Context, in *CreateWithdrawReq, opts ...grpc.CallOption) (*CreateWithdrawResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.CreateWithdraw(ctx, in, opts...)
}

func (m *defaultBusiness) ListWithdrawRecords(ctx context.Context, in *ListWithdrawRecordsReq, opts ...grpc.CallOption) (*ListWithdrawRecordsResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListWithdrawRecords(ctx, in, opts...)
}

func (m *defaultBusiness) GetWithdrawAuditStatus(ctx context.Context, in *GetWithdrawAuditStatusReq, opts ...grpc.CallOption) (*GetWithdrawAuditStatusResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetWithdrawAuditStatus(ctx, in, opts...)
}

func (m *defaultBusiness) GetWithdrawDetail(ctx context.Context, in *GetWithdrawDetailReq, opts ...grpc.CallOption) (*GetWithdrawDetailResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetWithdrawDetail(ctx, in, opts...)
}

// 资产页-消息通知（Web2 用户）
func (m *defaultBusiness) ListNotifications(ctx context.Context, in *ListNotificationsReq, opts ...grpc.CallOption) (*ListNotificationsResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListNotifications(ctx, in, opts...)
}

func (m *defaultBusiness) MarkNotificationRead(ctx context.Context, in *MarkNotificationReadReq, opts ...grpc.CallOption) (*MarkNotificationReadResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.MarkNotificationRead(ctx, in, opts...)
}

func (m *defaultBusiness) MarkAllNotificationsRead(ctx context.Context, in *MarkAllNotificationsReadReq, opts ...grpc.CallOption) (*MarkAllNotificationsReadResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.MarkAllNotificationsRead(ctx, in, opts...)
}

func (m *defaultBusiness) DeleteNotification(ctx context.Context, in *DeleteNotificationReq, opts ...grpc.CallOption) (*DeleteNotificationResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.DeleteNotification(ctx, in, opts...)
}

func (m *defaultBusiness) ClearAllNotifications(ctx context.Context, in *ClearAllNotificationsReq, opts ...grpc.CallOption) (*ClearAllNotificationsResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ClearAllNotifications(ctx, in, opts...)
}

// 内部接口：创建消息通知（供业务逻辑调用）
func (m *defaultBusiness) CreateUserNotification(ctx context.Context, in *CreateUserNotificationReq, opts ...grpc.CallOption) (*CreateUserNotificationResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.CreateUserNotification(ctx, in, opts...)
}

// 推送通知：通过别名发送推送（供业务逻辑调用）
func (m *defaultBusiness) SendPushNotificationByAlias(ctx context.Context, in *SendPushNotificationByAliasReq, opts ...grpc.CallOption) (*SendPushNotificationByAliasResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SendPushNotificationByAlias(ctx, in, opts...)
}

// 推送通知：通过设备ID发送推送（Web3用户专用）
func (m *defaultBusiness) SendPushNotificationByDeviceToken(ctx context.Context, in *SendPushNotificationByDeviceTokenReq, opts ...grpc.CallOption) (*SendPushNotificationByDeviceTokenResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SendPushNotificationByDeviceToken(ctx, in, opts...)
}

// 设备管理：注册设备（Web3用户专用）
func (m *defaultBusiness) RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.RegisterDevice(ctx, in, opts...)
}

func (m *defaultBusiness) GetMyOverview(ctx context.Context, in *GetMyOverviewReq, opts ...grpc.CallOption) (*GetMyOverviewResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetMyOverview(ctx, in, opts...)
}

func (m *defaultBusiness) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultBusiness) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

func (m *defaultBusiness) BindEmail(ctx context.Context, in *BindEmailReq, opts ...grpc.CallOption) (*BindEmailResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.BindEmail(ctx, in, opts...)
}

func (m *defaultBusiness) ChangeEmail(ctx context.Context, in *ChangeEmailReq, opts ...grpc.CallOption) (*ChangeEmailResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ChangeEmail(ctx, in, opts...)
}

// 我的页-手机号
func (m *defaultBusiness) BindPhone(ctx context.Context, in *BindPhoneReq, opts ...grpc.CallOption) (*BindPhoneResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.BindPhone(ctx, in, opts...)
}

func (m *defaultBusiness) ChangePhone(ctx context.Context, in *ChangePhoneReq, opts ...grpc.CallOption) (*ChangePhoneResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ChangePhone(ctx, in, opts...)
}

func (m *defaultBusiness) ListWalletProviders(ctx context.Context, in *ListWalletProvidersReq, opts ...grpc.CallOption) (*ListWalletProvidersResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListWalletProviders(ctx, in, opts...)
}

func (m *defaultBusiness) ListProviderAccounts(ctx context.Context, in *ListProviderAccountsReq, opts ...grpc.CallOption) (*ListProviderAccountsResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListProviderAccounts(ctx, in, opts...)
}

func (m *defaultBusiness) LinkWalletAccount(ctx context.Context, in *LinkWalletAccountReq, opts ...grpc.CallOption) (*LinkWalletAccountResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.LinkWalletAccount(ctx, in, opts...)
}

func (m *defaultBusiness) UnlinkWalletAccount(ctx context.Context, in *UnlinkWalletAccountReq, opts ...grpc.CallOption) (*UnlinkWalletAccountResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.UnlinkWalletAccount(ctx, in, opts...)
}

func (m *defaultBusiness) SetPrimaryLinkedWallet(ctx context.Context, in *SetPrimaryLinkedWalletReq, opts ...grpc.CallOption) (*SetPrimaryLinkedWalletResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SetPrimaryLinkedWallet(ctx, in, opts...)
}

func (m *defaultBusiness) GetLinkedWalletAccounts(ctx context.Context, in *GetLinkedWalletAccountsReq, opts ...grpc.CallOption) (*GetLinkedWalletAccountsResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetLinkedWalletAccounts(ctx, in, opts...)
}

// 我的页-登录密码
func (m *defaultBusiness) ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*ChangePasswordResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}

func (m *defaultBusiness) SetTradePassword(ctx context.Context, in *SetTradePasswordReq, opts ...grpc.CallOption) (*SetTradePasswordResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SetTradePassword(ctx, in, opts...)
}

func (m *defaultBusiness) ResetTradePassword(ctx context.Context, in *ResetTradePasswordReq, opts ...grpc.CallOption) (*ResetTradePasswordResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ResetTradePassword(ctx, in, opts...)
}

func (m *defaultBusiness) VerifyTradePassword(ctx context.Context, in *VerifyTradePasswordReq, opts ...grpc.CallOption) (*VerifyTradePasswordResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.VerifyTradePassword(ctx, in, opts...)
}

// 我的页-Web3交易密码
func (m *defaultBusiness) SetWeb3TradePassword(ctx context.Context, in *SetWeb3TradePasswordReq, opts ...grpc.CallOption) (*SetWeb3TradePasswordResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SetWeb3TradePassword(ctx, in, opts...)
}

func (m *defaultBusiness) VerifyWeb3TradePassword(ctx context.Context, in *VerifyWeb3TradePasswordReq, opts ...grpc.CallOption) (*VerifyWeb3TradePasswordResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.VerifyWeb3TradePassword(ctx, in, opts...)
}

func (m *defaultBusiness) UpdateWeb3TradePassword(ctx context.Context, in *UpdateWeb3TradePasswordReq, opts ...grpc.CallOption) (*UpdateWeb3TradePasswordResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.UpdateWeb3TradePassword(ctx, in, opts...)
}

// 我的页-使用设置-生物识别（Web2）
func (m *defaultBusiness) RegisterBiometricKey(ctx context.Context, in *RegisterBiometricKeyReq, opts ...grpc.CallOption) (*RegisterBiometricKeyResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.RegisterBiometricKey(ctx, in, opts...)
}

// 创建提币生物识别挑战（用于签名）
func (m *defaultBusiness) CreateWithdrawBiometricChallenge(ctx context.Context, in *CreateWithdrawBiometricChallengeReq, opts ...grpc.CallOption) (*CreateBiometricChallengeResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.CreateWithdrawBiometricChallenge(ctx, in, opts...)
}

// 创建提现免审白名单绑定生物识别挑战（用于签名）
func (m *defaultBusiness) CreateWithdrawAuditWhitelistBindingBiometricChallenge(ctx context.Context, in *CreateWithdrawAuditWhitelistBindingBiometricChallengeReq, opts ...grpc.CallOption) (*CreateBiometricChallengeResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.CreateWithdrawAuditWhitelistBindingBiometricChallenge(ctx, in, opts...)
}

// 创建重置交易密码生物识别挑战（用于签名）
func (m *defaultBusiness) CreateResetTradePasswordBiometricChallenge(ctx context.Context, in *CreateResetTradePasswordBiometricChallengeReq, opts ...grpc.CallOption) (*CreateBiometricChallengeResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.CreateResetTradePasswordBiometricChallenge(ctx, in, opts...)
}

// 解绑当前用户生物识别（仅交易密码）
func (m *defaultBusiness) UnbindBiometric(ctx context.Context, in *UnbindBiometricReq, opts ...grpc.CallOption) (*UnbindBiometricResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.UnbindBiometric(ctx, in, opts...)
}

// 我的页-使用设置-双重认证
func (m *defaultBusiness) GetGoogleAuthSetup(ctx context.Context, in *GetGoogleAuthSetupReq, opts ...grpc.CallOption) (*GetGoogleAuthSetupResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetGoogleAuthSetup(ctx, in, opts...)
}

// 绑定 Google 验证器
func (m *defaultBusiness) BindGoogleAuth(ctx context.Context, in *BindGoogleAuthReq, opts ...grpc.CallOption) (*BindGoogleAuthResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.BindGoogleAuth(ctx, in, opts...)
}

// 解绑 Google 验证器
func (m *defaultBusiness) UnbindGoogleAuth(ctx context.Context, in *UnbindGoogleAuthReq, opts ...grpc.CallOption) (*UnbindGoogleAuthResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.UnbindGoogleAuth(ctx, in, opts...)
}

// 关闭双重认证（不解绑 Google 验证器）
func (m *defaultBusiness) DisableGoogleAuth2FA(ctx context.Context, in *DisableGoogleAuth2FAReq, opts ...grpc.CallOption) (*DisableGoogleAuth2FAResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.DisableGoogleAuth2FA(ctx, in, opts...)
}

// 开启双重认证（已绑定GA，传验证码开启）
func (m *defaultBusiness) EnableGoogleAuth2FA(ctx context.Context, in *EnableGoogleAuth2FAReq, opts ...grpc.CallOption) (*EnableGoogleAuth2FAResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.EnableGoogleAuth2FA(ctx, in, opts...)
}

// 关闭双重认证（已绑定GA，传验证码关闭）
func (m *defaultBusiness) DisableGoogleAuth2FAWithCode(ctx context.Context, in *DisableGoogleAuth2FAWithCodeReq, opts ...grpc.CallOption) (*DisableGoogleAuth2FAWithCodeResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.DisableGoogleAuth2FAWithCode(ctx, in, opts...)
}

// 校验Google验证器验证码（仅校验，不做任何状态修改）
func (m *defaultBusiness) VerifyGoogleAuthCode(ctx context.Context, in *VerifyGoogleAuthCodeReq, opts ...grpc.CallOption) (*VerifyGoogleAuthCodeResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.VerifyGoogleAuthCode(ctx, in, opts...)
}

// 我的页-使用设置－登录记录
func (m *defaultBusiness) ListLoginRecords(ctx context.Context, in *ListLoginRecordsReq, opts ...grpc.CallOption) (*ListLoginRecordsResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListLoginRecords(ctx, in, opts...)
}

// 我的页-使用设置－钱包地址（链上地址）
func (m *defaultBusiness) ListWalletAddresses(ctx context.Context, in *ListWalletAddressesReq, opts ...grpc.CallOption) (*ListWalletAddressesResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListWalletAddresses(ctx, in, opts...)
}

func (m *defaultBusiness) AddWalletAddress(ctx context.Context, in *AddWalletAddressReq, opts ...grpc.CallOption) (*AddWalletAddressResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.AddWalletAddress(ctx, in, opts...)
}

func (m *defaultBusiness) UpdateWalletAddress(ctx context.Context, in *UpdateWalletAddressReq, opts ...grpc.CallOption) (*UpdateWalletAddressResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.UpdateWalletAddress(ctx, in, opts...)
}

func (m *defaultBusiness) DeleteWalletAddress(ctx context.Context, in *DeleteWalletAddressReq, opts ...grpc.CallOption) (*DeleteWalletAddressResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.DeleteWalletAddress(ctx, in, opts...)
}

func (m *defaultBusiness) SetDefaultWalletAddress(ctx context.Context, in *SetDefaultWalletAddressReq, opts ...grpc.CallOption) (*SetDefaultWalletAddressResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SetDefaultWalletAddress(ctx, in, opts...)
}

func (m *defaultBusiness) ValidateWalletAddress(ctx context.Context, in *ValidateWalletAddressReq, opts ...grpc.CallOption) (*ValidateWalletAddressResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ValidateWalletAddress(ctx, in, opts...)
}

// 我的页-使用设置－钱包地址（内部地址，通过UID/邮箱添加平台内用户）
func (m *defaultBusiness) ListInternalWalletAddresses(ctx context.Context, in *ListInternalWalletAddressesReq, opts ...grpc.CallOption) (*ListInternalWalletAddressesResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListInternalWalletAddresses(ctx, in, opts...)
}

func (m *defaultBusiness) AddInternalWalletAddress(ctx context.Context, in *AddInternalWalletAddressReq, opts ...grpc.CallOption) (*AddInternalWalletAddressResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.AddInternalWalletAddress(ctx, in, opts...)
}

func (m *defaultBusiness) UpdateInternalWalletAddress(ctx context.Context, in *UpdateInternalWalletAddressReq, opts ...grpc.CallOption) (*UpdateInternalWalletAddressResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.UpdateInternalWalletAddress(ctx, in, opts...)
}

func (m *defaultBusiness) DeleteInternalWalletAddress(ctx context.Context, in *DeleteInternalWalletAddressReq, opts ...grpc.CallOption) (*DeleteInternalWalletAddressResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.DeleteInternalWalletAddress(ctx, in, opts...)
}

func (m *defaultBusiness) LookupInternalUser(ctx context.Context, in *LookupInternalUserReq, opts ...grpc.CallOption) (*LookupInternalUserResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.LookupInternalUser(ctx, in, opts...)
}

// 内部转账（用户之间的资产转移，支持审核）
func (m *defaultBusiness) ValidateInternalTransferTarget(ctx context.Context, in *ValidateInternalTransferTargetReq, opts ...grpc.CallOption) (*ValidateInternalTransferTargetResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ValidateInternalTransferTarget(ctx, in, opts...)
}

func (m *defaultBusiness) SubmitInternalTransfer(ctx context.Context, in *SubmitInternalTransferReq, opts ...grpc.CallOption) (*SubmitInternalTransferResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SubmitInternalTransfer(ctx, in, opts...)
}

func (m *defaultBusiness) CancelInternalTransfer(ctx context.Context, in *CancelInternalTransferReq, opts ...grpc.CallOption) (*CancelInternalTransferResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.CancelInternalTransfer(ctx, in, opts...)
}

// 提现免审白名单（用户自绑定）
func (m *defaultBusiness) ListWithdrawAuditWhitelistBindableNetworks(ctx context.Context, in *ListWithdrawAuditWhitelistBindableNetworksReq, opts ...grpc.CallOption) (*ListWithdrawAuditWhitelistBindableNetworksResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListWithdrawAuditWhitelistBindableNetworks(ctx, in, opts...)
}

func (m *defaultBusiness) SetMyWithdrawAuditWhitelistBinding(ctx context.Context, in *SetMyWithdrawAuditWhitelistBindingReq, opts ...grpc.CallOption) (*SetMyWithdrawAuditWhitelistBindingResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SetMyWithdrawAuditWhitelistBinding(ctx, in, opts...)
}

func (m *defaultBusiness) GetMyWithdrawAuditWhitelistBindingStatus(ctx context.Context, in *GetMyWithdrawAuditWhitelistBindingStatusReq, opts ...grpc.CallOption) (*GetMyWithdrawAuditWhitelistBindingStatusResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetMyWithdrawAuditWhitelistBindingStatus(ctx, in, opts...)
}

func (m *defaultBusiness) UnbindMyWithdrawAuditWhitelistBindings(ctx context.Context, in *UnbindMyWithdrawAuditWhitelistBindingsReq, opts ...grpc.CallOption) (*UnbindMyWithdrawAuditWhitelistBindingsResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.UnbindMyWithdrawAuditWhitelistBindings(ctx, in, opts...)
}

// 我的页-偏好设置
func (m *defaultBusiness) GetPreferences(ctx context.Context, in *GetPreferencesReq, opts ...grpc.CallOption) (*GetPreferencesResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetPreferences(ctx, in, opts...)
}

func (m *defaultBusiness) ListLanguageOptions(ctx context.Context, in *ListLanguageOptionsReq, opts ...grpc.CallOption) (*ListLanguageOptionsResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListLanguageOptions(ctx, in, opts...)
}

func (m *defaultBusiness) ListPriceUnitOptions(ctx context.Context, in *ListPriceUnitOptionsReq, opts ...grpc.CallOption) (*ListPriceUnitOptionsResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListPriceUnitOptions(ctx, in, opts...)
}

func (m *defaultBusiness) SetPreferences(ctx context.Context, in *SetPreferencesReq, opts ...grpc.CallOption) (*SetPreferencesResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SetPreferences(ctx, in, opts...)
}

// 获取客户端配置
func (m *defaultBusiness) GetClientConfig(ctx context.Context, in *GetClientConfigReq, opts ...grpc.CallOption) (*GetClientConfigResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetClientConfig(ctx, in, opts...)
}

// ==================== Web3 Swap (proxy to swap microservice) ====================
func (m *defaultBusiness) SwapGetQuote(ctx context.Context, in *BusinessSwapGetQuoteRequest, opts ...grpc.CallOption) (*BusinessSwapGetQuoteResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SwapGetQuote(ctx, in, opts...)
}

func (m *defaultBusiness) SwapExecuteSwap(ctx context.Context, in *BusinessSwapExecuteSwapRequest, opts ...grpc.CallOption) (*BusinessSwapExecuteSwapResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SwapExecuteSwap(ctx, in, opts...)
}

func (m *defaultBusiness) SwapGetApprovalTransaction(ctx context.Context, in *BusinessSwapGetApprovalTransactionRequest, opts ...grpc.CallOption) (*BusinessSwapGetApprovalTransactionResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SwapGetApprovalTransaction(ctx, in, opts...)
}

func (m *defaultBusiness) SwapResetApproval(ctx context.Context, in *BusinessSwapResetApprovalRequest, opts ...grpc.CallOption) (*BusinessSwapResetApprovalResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SwapResetApproval(ctx, in, opts...)
}

func (m *defaultBusiness) SwapGetSwapStatus(ctx context.Context, in *BusinessSwapGetSwapStatusRequest, opts ...grpc.CallOption) (*BusinessSwapGetSwapStatusResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SwapGetSwapStatus(ctx, in, opts...)
}

func (m *defaultBusiness) SwapGetSwapDetail(ctx context.Context, in *BusinessSwapGetSwapDetailRequest, opts ...grpc.CallOption) (*BusinessSwapGetSwapDetailResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SwapGetSwapDetail(ctx, in, opts...)
}

func (m *defaultBusiness) SwapGetSwapHistory(ctx context.Context, in *BusinessSwapGetSwapHistoryRequest, opts ...grpc.CallOption) (*BusinessSwapGetSwapHistoryResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SwapGetSwapHistory(ctx, in, opts...)
}

func (m *defaultBusiness) SwapGetSupportedTokens(ctx context.Context, in *BusinessSwapGetSupportedTokensRequest, opts ...grpc.CallOption) (*BusinessSwapGetSupportedTokensResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SwapGetSupportedTokens(ctx, in, opts...)
}

func (m *defaultBusiness) SwapGetSupportedChains(ctx context.Context, in *BusinessSwapGetSupportedChainsRequest, opts ...grpc.CallOption) (*BusinessSwapGetSupportedChainsResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SwapGetSupportedChains(ctx, in, opts...)
}

func (m *defaultBusiness) SwapGetExternalSwapStatus(ctx context.Context, in *BusinessSwapGetExternalSwapStatusRequest, opts ...grpc.CallOption) (*BusinessSwapGetExternalSwapStatusResponse, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.SwapGetExternalSwapStatus(ctx, in, opts...)
}

// ==================== Web3 User Management ====================
func (m *defaultBusiness) CreateWeb3User(ctx context.Context, in *CreateWeb3UserReq, opts ...grpc.CallOption) (*CreateWeb3UserResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.CreateWeb3User(ctx, in, opts...)
}

// 添加 Web3 用户地址
func (m *defaultBusiness) AddWeb3UserAddress(ctx context.Context, in *AddWeb3UserAddressReq, opts ...grpc.CallOption) (*AddWeb3UserAddressResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.AddWeb3UserAddress(ctx, in, opts...)
}

// 批量添加 Web3 用户地址（一次添加多条链的地址）
func (m *defaultBusiness) BatchAddWeb3UserAddress(ctx context.Context, in *BatchAddWeb3UserAddressReq, opts ...grpc.CallOption) (*BatchAddWeb3UserAddressResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.BatchAddWeb3UserAddress(ctx, in, opts...)
}

// 查询可用链列表（Web3 用户）
func (m *defaultBusiness) ListWeb3Chains(ctx context.Context, in *ListWeb3ChainsReq, opts ...grpc.CallOption) (*ListWeb3ChainsResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListWeb3Chains(ctx, in, opts...)
}

// 根据 device_id 获取 Web3 用户信息
func (m *defaultBusiness) GetWeb3UserByDeviceId(ctx context.Context, in *GetWeb3UserByDeviceIdReq, opts ...grpc.CallOption) (*GetWeb3UserByDeviceIdResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetWeb3UserByDeviceId(ctx, in, opts...)
}

// 获取 Web3 用户资产概览
func (m *defaultBusiness) GetWeb3AssetOverview(ctx context.Context, in *GetWeb3AssetOverviewReq, opts ...grpc.CallOption) (*GetWeb3AssetOverviewResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetWeb3AssetOverview(ctx, in, opts...)
}

// 获取 Web3 用户交易记录列表
func (m *defaultBusiness) ListWeb3Transactions(ctx context.Context, in *ListWeb3TransactionsReq, opts ...grpc.CallOption) (*ListWeb3TransactionsResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListWeb3Transactions(ctx, in, opts...)
}

// 获取 Web3 交易详情
func (m *defaultBusiness) GetWeb3TransactionDetail(ctx context.Context, in *GetWeb3TransactionDetailReq, opts ...grpc.CallOption) (*GetWeb3TransactionDetailResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetWeb3TransactionDetail(ctx, in, opts...)
}

// Web3 交易结果查询（根据交易哈希查询状态和结果）
func (m *defaultBusiness) GetWeb3TransactionResult(ctx context.Context, in *GetWeb3TransactionResultReq, opts ...grpc.CallOption) (*GetWeb3TransactionResultResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetWeb3TransactionResult(ctx, in, opts...)
}

// 广播 Web3 交易（Web3 用户专用）
func (m *defaultBusiness) BroadcastWeb3Transaction(ctx context.Context, in *BroadcastWeb3TransactionReq, opts ...grpc.CallOption) (*BroadcastWeb3TransactionResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.BroadcastWeb3Transaction(ctx, in, opts...)
}

// 获取 Web3 支持的资产列表（根据链）
func (m *defaultBusiness) ListWeb3SupportedAssets(ctx context.Context, in *ListWeb3SupportedAssetsReq, opts ...grpc.CallOption) (*ListWeb3SupportedAssetsResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.ListWeb3SupportedAssets(ctx, in, opts...)
}

// 获取 Web3 用户地址的 Nonce（用于构建 EVM 交易）
func (m *defaultBusiness) GetWeb3Nonce(ctx context.Context, in *GetWeb3NonceReq, opts ...grpc.CallOption) (*GetWeb3NonceResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetWeb3Nonce(ctx, in, opts...)
}

// 构建 Web3 TRON 交易（返回未签名的 rawData，供客户端签名）
func (m *defaultBusiness) BuildTronTransaction(ctx context.Context, in *BuildTronTransactionReq, opts ...grpc.CallOption) (*BuildTronTransactionResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.BuildTronTransaction(ctx, in, opts...)
}

// 获取 Web3 代币详细信息（合约地址、网络、价格、市值、持有者等）
func (m *defaultBusiness) GetWeb3TokenDetail(ctx context.Context, in *GetWeb3TokenDetailReq, opts ...grpc.CallOption) (*GetWeb3TokenDetailResp, error) {
	client := pb.NewBusinessClient(m.cli.Conn())
	return client.GetWeb3TokenDetail(ctx, in, opts...)
}
