// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: consolidation.proto

package server

import (
	"context"

	"internalwallet/proto/pb"
	"internalwallet/services/consolidation/rpc/internal/logic"
	"internalwallet/services/consolidation/rpc/internal/svc"
)

type ConsolidationServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedConsolidationServer
}

func NewConsolidationServer(svcCtx *svc.ServiceContext) *ConsolidationServer {
	return &ConsolidationServer{
		svcCtx: svcCtx,
	}
}

// Manually trigger discovery/execution for a specific chain/asset (best-effort).
func (s *ConsolidationServer) TriggerConsolidation(ctx context.Context, in *pb.TriggerConsolidationRequest) (*pb.TriggerConsolidationResponse, error) {
	l := logic.NewTriggerConsolidationLogic(ctx, s.svcCtx)
	return l.TriggerConsolidation(in)
}

// Query task by task_id.
func (s *ConsolidationServer) GetConsolidationTask(ctx context.Context, in *pb.GetConsolidationTaskRequest) (*pb.GetConsolidationTaskResponse, error) {
	l := logic.NewGetConsolidationTaskLogic(ctx, s.svcCtx)
	return l.GetConsolidationTask(in)
}

// List tasks with filters.
func (s *ConsolidationServer) ListConsolidationTasks(ctx context.Context, in *pb.ListConsolidationTasksRequest) (*pb.ListConsolidationTasksResponse, error) {
	l := logic.NewListConsolidationTasksLogic(ctx, s.svcCtx)
	return l.ListConsolidationTasks(in)
}

// Aggregated stats.
func (s *ConsolidationServer) GetConsolidationStats(ctx context.Context, in *pb.GetConsolidationStatsRequest) (*pb.GetConsolidationStatsResponse, error) {
	l := logic.NewGetConsolidationStatsLogic(ctx, s.svcCtx)
	return l.GetConsolidationStats(in)
}

// Cancel a pending task.
func (s *ConsolidationServer) CancelConsolidationTask(ctx context.Context, in *pb.CancelConsolidationTaskRequest) (*pb.CancelConsolidationTaskResponse, error) {
	l := logic.NewCancelConsolidationTaskLogic(ctx, s.svcCtx)
	return l.CancelConsolidationTask(in)
}

// Retry a failed/permanent-failed task (subject to max retry policy).
func (s *ConsolidationServer) RetryConsolidationTask(ctx context.Context, in *pb.RetryConsolidationTaskRequest) (*pb.RetryConsolidationTaskResponse, error) {
	l := logic.NewRetryConsolidationTaskLogic(ctx, s.svcCtx)
	return l.RetryConsolidationTask(in)
}

// List logs with filters.
func (s *ConsolidationServer) ListConsolidationLogs(ctx context.Context, in *pb.ListConsolidationLogsRequest) (*pb.ListConsolidationLogsResponse, error) {
	l := logic.NewListConsolidationLogsLogic(ctx, s.svcCtx)
	return l.ListConsolidationLogs(in)
}

// List top-up records with filters.
func (s *ConsolidationServer) ListConsolidationTopupRecords(ctx context.Context, in *pb.ListConsolidationTopupRecordsRequest) (*pb.ListConsolidationTopupRecordsResponse, error) {
	l := logic.NewListConsolidationTopupRecordsLogic(ctx, s.svcCtx)
	return l.ListConsolidationTopupRecords(in)
}

// List energy rental records with filters.
func (s *ConsolidationServer) ListEnergyRentalRecords(ctx context.Context, in *pb.ListEnergyRentalRecordsRequest) (*pb.ListEnergyRentalRecordsResponse, error) {
	l := logic.NewListEnergyRentalRecordsLogic(ctx, s.svcCtx)
	return l.ListEnergyRentalRecords(in)
}

// Get energy rental record by ID.
func (s *ConsolidationServer) GetEnergyRentalRecord(ctx context.Context, in *pb.GetEnergyRentalRecordRequest) (*pb.GetEnergyRentalRecordResponse, error) {
	l := logic.NewGetEnergyRentalRecordLogic(ctx, s.svcCtx)
	return l.GetEnergyRentalRecord(in)
}
