package model

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type UserModel struct {
	// NOTE: ID field is now AUTO_INCREMENT in database (not Snowflake)
	// BaseModel.ID will be auto-generated by database
	ID                int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // Database auto-increment ID
	UUID              string    `gorm:"column:uuid;type:varchar(36);not null;uniqueIndex"`
	Email             string    `gorm:"column:email;type:varchar(100);default:NULL;uniqueIndex"`
	Phone             string    `gorm:"column:phone;type:varchar(20);default:NULL;uniqueIndex"`
	CountryCode       string    `gorm:"column:country_code;type:varchar(10);default:''"`
	Nickname          string    `gorm:"column:nickname;type:varchar(50);default:''"`
	Avatar            string    `gorm:"column:avatar;type:varchar(255);default:''"`
	PasswordHash      string    `gorm:"column:password_hash;type:varchar(255);default:''"` // bcrypt 密码哈希
	KycLevel          int32     `gorm:"column:kyc_level;type:tinyint;default:0"`
	MemberLevel       int32     `gorm:"column:member_level;type:tinyint;default:1"`
	GoogleAuthSecret  string    `gorm:"column:google_auth_secret;type:varchar(100);default:''"`
	Is2faEnabled      bool      `gorm:"column:is_2fa_enabled;type:tinyint(1);default:0"`
	HasTradePassword  bool      `gorm:"column:has_trade_password;type:tinyint(1);default:0"`
	TradePasswordHash string    `gorm:"column:trade_password_hash;type:varchar(255);default:''"`
	AntiPhishingCode  string    `gorm:"column:anti_phishing_code;type:varchar(20);default:''"`
	CountryRegion     string    `gorm:"column:country_region;type:varchar(50);default:''"`
	Language          int32     `gorm:"column:language;type:tinyint;default:0"`
	PriceUnit         int32     `gorm:"column:price_unit;type:tinyint;default:0"`
	ThemeMode         string    `gorm:"column:theme_mode;type:varchar(20);default:'system'"`
	Bio               string    `gorm:"column:bio;type:text"`
	Source            string    `gorm:"column:source;type:varchar(50);default:''"`
	Secret            string    `gorm:"column:secret;type:varchar(64);default:''"`
	BackupCodes       string    `gorm:"column:backup_codes;type:text"`
	Enabled           bool      `gorm:"column:enabled;type:tinyint(1);default:0"`
	Status            int32     `gorm:"column:status;type:tinyint;default:1"`
	RegisterIp        string    `gorm:"column:register_ip;type:varchar(50);default:''"`
	LastLoginTime     time.Time `gorm:"column:last_login_time;type:datetime;default:CURRENT_TIMESTAMP"`
	FailedLoginCount  int       `gorm:"column:failed_login_count;type:int;default:0"`
	LockUntil         time.Time `gorm:"column:lock_until;type:datetime;default:CURRENT_TIMESTAMP"`
	CreatedAt         time.Time `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP"`
	UpdatedAt         time.Time `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP"`
	DeletedAt         *time.Time `gorm:"column:deleted_at;type:datetime;default:NULL;index"` // Soft delete
}

func (UserModel) TableName() string { return "users" }

func (u *UserModel) BeforeCreate(tx *gorm.DB) error {
	// NOTE: Do NOT call BaseModel.BeforeCreate() because:
	// 1. UserModel uses database AUTO_INCREMENT for ID (not Snowflake)
	// 2. We override ID, CreatedAt, UpdatedAt, DeletedAt fields directly
	// 3. BaseModel.BeforeCreate() would try to generate Snowflake ID which we don't want

	// Generate UUID if not set
	if u.UUID == "" {
		u.UUID = uuid.NewString()
	}

	// Set timestamps manually (since we're not calling BaseModel.BeforeCreate)
	now := time.Now().Local()
	if u.CreatedAt.IsZero() {
		u.CreatedAt = now
	}
	if u.UpdatedAt.IsZero() {
		u.UpdatedAt = now
	}

	// IMPORTANT:
	// - email/phone 在 DB 中有 UNIQUE 索引
	// - 多个用户如果插入空字符串(""), 会触发 Duplicate entry ''
	// - MariaDB/MySQL 允许 UNIQUE 列出现多个 NULL
	// 因此：创建用户时将空字符串写成 NULL。
	if u.Email == "" {
		tx.Statement.SetColumn("Email", gorm.Expr("NULL"))
	}
	if u.Phone == "" {
		tx.Statement.SetColumn("Phone", gorm.Expr("NULL"))
	}
	return nil
}

func (u *UserModel) BeforeUpdate(tx *gorm.DB) error {
	// Update timestamp manually
	u.UpdatedAt = time.Now().Local()
	return nil
}
