// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: signer.proto

package signerservice

import (
	"context"

	"internalwallet/proto/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddressBatchItem                         = pb.AddressBatchItem
	CompanyWalletInfo                        = pb.CompanyWalletInfo
	DatabaseHealth                           = pb.DatabaseHealth
	ExportPublicKeyBatchRequest              = pb.ExportPublicKeyBatchRequest
	ExportPublicKeyBatchResponse             = pb.ExportPublicKeyBatchResponse
	ExportPublicKeyRequest                   = pb.ExportPublicKeyRequest
	ExportPublicKeyResponse                  = pb.ExportPublicKeyResponse
	GenerateAddressBatchRequest              = pb.GenerateAddressBatchRequest
	GenerateAddressBatchResponse             = pb.GenerateAddressBatchResponse
	GenerateUserDepositAddressRequest        = pb.GenerateUserDepositAddressRequest
	GenerateUserDepositAddressResponse       = pb.GenerateUserDepositAddressResponse
	GenerateUserDepositAddressesRequest      = pb.GenerateUserDepositAddressesRequest
	GenerateUserDepositAddressesResponse     = pb.GenerateUserDepositAddressesResponse
	GetAddressFromPathRequest                = pb.GetAddressFromPathRequest
	GetAddressFromPathResponse               = pb.GetAddressFromPathResponse
	GetCompanyWalletByAddressRequest         = pb.GetCompanyWalletByAddressRequest
	GetCompanyWalletRequest                  = pb.GetCompanyWalletRequest
	GetCompanyWalletResponse                 = pb.GetCompanyWalletResponse
	GetHotWalletMnemonicChallengeRequest     = pb.GetHotWalletMnemonicChallengeRequest
	GetHotWalletMnemonicChallengeResponse    = pb.GetHotWalletMnemonicChallengeResponse
	GetHotWalletMnemonicPageRequest          = pb.GetHotWalletMnemonicPageRequest
	GetHotWalletMnemonicPageResponse         = pb.GetHotWalletMnemonicPageResponse
	GetMnemonicChallengeRequest              = pb.GetMnemonicChallengeRequest
	GetMnemonicChallengeResponse             = pb.GetMnemonicChallengeResponse
	GetRuntimeStatusRequest                  = pb.GetRuntimeStatusRequest
	GetRuntimeStatusResponse                 = pb.GetRuntimeStatusResponse
	HealthCheckRequest                       = pb.HealthCheckRequest
	HealthCheckResponse                      = pb.HealthCheckResponse
	ListCompanyWalletsRequest                = pb.ListCompanyWalletsRequest
	ListCompanyWalletsResponse               = pb.ListCompanyWalletsResponse
	ListSeedsRequest                         = pb.ListSeedsRequest
	ListSeedsResponse                        = pb.ListSeedsResponse
	LockHotWalletRequest                     = pb.LockHotWalletRequest
	LockHotWalletResponse                    = pb.LockHotWalletResponse
	MnemonicAnswer                           = pb.MnemonicAnswer
	PubkeyInfo                               = pb.PubkeyInfo
	QuerySignatureLogsRequest                = pb.QuerySignatureLogsRequest
	QuerySignatureLogsResponse               = pb.QuerySignatureLogsResponse
	SeedInfo                                 = pb.SeedInfo
	SeedsHealth                              = pb.SeedsHealth
	SignBatchRequest                         = pb.SignBatchRequest
	SignBatchResponse                        = pb.SignBatchResponse
	SignMessageRequest                       = pb.SignMessageRequest
	SignMessageResponse                      = pb.SignMessageResponse
	SignResultItem                           = pb.SignResultItem
	SignTransactionRequest                   = pb.SignTransactionRequest
	SignTransactionResponse                  = pb.SignTransactionResponse
	SignatureLogInfo                         = pb.SignatureLogInfo
	StartHotWalletInitRequest                = pb.StartHotWalletInitRequest
	StartHotWalletInitResponse               = pb.StartHotWalletInitResponse
	TransactionItem                          = pb.TransactionItem
	UnlockHotWalletRequest                   = pb.UnlockHotWalletRequest
	UnlockHotWalletResponse                  = pb.UnlockHotWalletResponse
	UpdateSeedStatusRequest                  = pb.UpdateSeedStatusRequest
	UpdateSeedStatusResponse                 = pb.UpdateSeedStatusResponse
	UserDepositAddress                       = pb.UserDepositAddress
	VerifyHotWalletMnemonicChallengeRequest  = pb.VerifyHotWalletMnemonicChallengeRequest
	VerifyHotWalletMnemonicChallengeResponse = pb.VerifyHotWalletMnemonicChallengeResponse
	VerifyMnemonicChallengeRequest           = pb.VerifyMnemonicChallengeRequest
	VerifyMnemonicChallengeResponse          = pb.VerifyMnemonicChallengeResponse

	SignerService interface {
		// ========== Seed管理 ==========
		ListSeeds(ctx context.Context, in *ListSeedsRequest, opts ...grpc.CallOption) (*ListSeedsResponse, error)
		// 更新Seed状态
		UpdateSeedStatus(ctx context.Context, in *UpdateSeedStatusRequest, opts ...grpc.CallOption) (*UpdateSeedStatusResponse, error)
		// 获取助记词验证挑战（3-word challenge）
		GetMnemonicChallenge(ctx context.Context, in *GetMnemonicChallengeRequest, opts ...grpc.CallOption) (*GetMnemonicChallengeResponse, error)
		// 验证助记词挑战
		VerifyMnemonicChallenge(ctx context.Context, in *VerifyMnemonicChallengeRequest, opts ...grpc.CallOption) (*VerifyMnemonicChallengeResponse, error)
		// ========== HD钱包地址管理 ==========
		GenerateUserDepositAddresses(ctx context.Context, in *GenerateUserDepositAddressesRequest, opts ...grpc.CallOption) (*GenerateUserDepositAddressesResponse, error)
		// 为用户生成单个充值地址（支持 change_index，用于同链多地址）
		GenerateUserDepositAddress(ctx context.Context, in *GenerateUserDepositAddressRequest, opts ...grpc.CallOption) (*GenerateUserDepositAddressResponse, error)
		// 根据派生路径获取地址
		GetAddressFromPath(ctx context.Context, in *GetAddressFromPathRequest, opts ...grpc.CallOption) (*GetAddressFromPathResponse, error)
		// 批量生成地址
		GenerateAddressBatch(ctx context.Context, in *GenerateAddressBatchRequest, opts ...grpc.CallOption) (*GenerateAddressBatchResponse, error)
		// ========== 公司钱包管理 ==========
		GetCompanyWallet(ctx context.Context, in *GetCompanyWalletRequest, opts ...grpc.CallOption) (*GetCompanyWalletResponse, error)
		// 查询所有公司钱包地址
		ListCompanyWallets(ctx context.Context, in *ListCompanyWalletsRequest, opts ...grpc.CallOption) (*ListCompanyWalletsResponse, error)
		// 根据地址查询公司钱包信息
		GetCompanyWalletByAddress(ctx context.Context, in *GetCompanyWalletByAddressRequest, opts ...grpc.CallOption) (*GetCompanyWalletResponse, error)
		// ========== 公钥导出 ==========
		ExportPublicKey(ctx context.Context, in *ExportPublicKeyRequest, opts ...grpc.CallOption) (*ExportPublicKeyResponse, error)
		// 批量导出公钥
		ExportPublicKeyBatch(ctx context.Context, in *ExportPublicKeyBatchRequest, opts ...grpc.CallOption) (*ExportPublicKeyBatchResponse, error)
		// ========== 签名服务 ==========
		SignTransaction(ctx context.Context, in *SignTransactionRequest, opts ...grpc.CallOption) (*SignTransactionResponse, error)
		// 批量签名
		SignBatch(ctx context.Context, in *SignBatchRequest, opts ...grpc.CallOption) (*SignBatchResponse, error)
		// 消息签名
		SignMessage(ctx context.Context, in *SignMessageRequest, opts ...grpc.CallOption) (*SignMessageResponse, error)
		// ========== 日志查询 ==========
		QuerySignatureLogs(ctx context.Context, in *QuerySignatureLogsRequest, opts ...grpc.CallOption) (*QuerySignatureLogsResponse, error)
		// ========== 健康检查 ==========
		HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
		// ========== 热钱包初始化 / signer 解锁门禁 ==========
		GetRuntimeStatus(ctx context.Context, in *GetRuntimeStatusRequest, opts ...grpc.CallOption) (*GetRuntimeStatusResponse, error)
		// 开始热钱包初始化（生成24词助记词并进入分页展示会话）
		StartHotWalletInit(ctx context.Context, in *StartHotWalletInitRequest, opts ...grpc.CallOption) (*StartHotWalletInitResponse, error)
		// 分页获取助记词（每页4个词）
		GetHotWalletMnemonicPage(ctx context.Context, in *GetHotWalletMnemonicPageRequest, opts ...grpc.CallOption) (*GetHotWalletMnemonicPageResponse, error)
		// 获取四词校验挑战
		GetHotWalletMnemonicChallenge(ctx context.Context, in *GetHotWalletMnemonicChallengeRequest, opts ...grpc.CallOption) (*GetHotWalletMnemonicChallengeResponse, error)
		// 验证四词校验挑战
		VerifyHotWalletMnemonicChallenge(ctx context.Context, in *VerifyHotWalletMnemonicChallengeRequest, opts ...grpc.CallOption) (*VerifyHotWalletMnemonicChallengeResponse, error)
		// 解锁热钱包（每次 signer 重启后需要重新解锁）
		UnlockHotWallet(ctx context.Context, in *UnlockHotWalletRequest, opts ...grpc.CallOption) (*UnlockHotWalletResponse, error)
		// 手动锁定（可选）
		LockHotWallet(ctx context.Context, in *LockHotWalletRequest, opts ...grpc.CallOption) (*LockHotWalletResponse, error)
	}

	defaultSignerService struct {
		cli zrpc.Client
	}
)

func NewSignerService(cli zrpc.Client) SignerService {
	return &defaultSignerService{
		cli: cli,
	}
}

// ========== Seed管理 ==========
func (m *defaultSignerService) ListSeeds(ctx context.Context, in *ListSeedsRequest, opts ...grpc.CallOption) (*ListSeedsResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.ListSeeds(ctx, in, opts...)
}

// 更新Seed状态
func (m *defaultSignerService) UpdateSeedStatus(ctx context.Context, in *UpdateSeedStatusRequest, opts ...grpc.CallOption) (*UpdateSeedStatusResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.UpdateSeedStatus(ctx, in, opts...)
}

// 获取助记词验证挑战（3-word challenge）
func (m *defaultSignerService) GetMnemonicChallenge(ctx context.Context, in *GetMnemonicChallengeRequest, opts ...grpc.CallOption) (*GetMnemonicChallengeResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.GetMnemonicChallenge(ctx, in, opts...)
}

// 验证助记词挑战
func (m *defaultSignerService) VerifyMnemonicChallenge(ctx context.Context, in *VerifyMnemonicChallengeRequest, opts ...grpc.CallOption) (*VerifyMnemonicChallengeResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.VerifyMnemonicChallenge(ctx, in, opts...)
}

// ========== HD钱包地址管理 ==========
func (m *defaultSignerService) GenerateUserDepositAddresses(ctx context.Context, in *GenerateUserDepositAddressesRequest, opts ...grpc.CallOption) (*GenerateUserDepositAddressesResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.GenerateUserDepositAddresses(ctx, in, opts...)
}

// 为用户生成单个充值地址（支持 change_index，用于同链多地址）
func (m *defaultSignerService) GenerateUserDepositAddress(ctx context.Context, in *GenerateUserDepositAddressRequest, opts ...grpc.CallOption) (*GenerateUserDepositAddressResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.GenerateUserDepositAddress(ctx, in, opts...)
}

// 根据派生路径获取地址
func (m *defaultSignerService) GetAddressFromPath(ctx context.Context, in *GetAddressFromPathRequest, opts ...grpc.CallOption) (*GetAddressFromPathResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.GetAddressFromPath(ctx, in, opts...)
}

// 批量生成地址
func (m *defaultSignerService) GenerateAddressBatch(ctx context.Context, in *GenerateAddressBatchRequest, opts ...grpc.CallOption) (*GenerateAddressBatchResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.GenerateAddressBatch(ctx, in, opts...)
}

// ========== 公司钱包管理 ==========
func (m *defaultSignerService) GetCompanyWallet(ctx context.Context, in *GetCompanyWalletRequest, opts ...grpc.CallOption) (*GetCompanyWalletResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.GetCompanyWallet(ctx, in, opts...)
}

// 查询所有公司钱包地址
func (m *defaultSignerService) ListCompanyWallets(ctx context.Context, in *ListCompanyWalletsRequest, opts ...grpc.CallOption) (*ListCompanyWalletsResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.ListCompanyWallets(ctx, in, opts...)
}

// 根据地址查询公司钱包信息
func (m *defaultSignerService) GetCompanyWalletByAddress(ctx context.Context, in *GetCompanyWalletByAddressRequest, opts ...grpc.CallOption) (*GetCompanyWalletResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.GetCompanyWalletByAddress(ctx, in, opts...)
}

// ========== 公钥导出 ==========
func (m *defaultSignerService) ExportPublicKey(ctx context.Context, in *ExportPublicKeyRequest, opts ...grpc.CallOption) (*ExportPublicKeyResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.ExportPublicKey(ctx, in, opts...)
}

// 批量导出公钥
func (m *defaultSignerService) ExportPublicKeyBatch(ctx context.Context, in *ExportPublicKeyBatchRequest, opts ...grpc.CallOption) (*ExportPublicKeyBatchResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.ExportPublicKeyBatch(ctx, in, opts...)
}

// ========== 签名服务 ==========
func (m *defaultSignerService) SignTransaction(ctx context.Context, in *SignTransactionRequest, opts ...grpc.CallOption) (*SignTransactionResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.SignTransaction(ctx, in, opts...)
}

// 批量签名
func (m *defaultSignerService) SignBatch(ctx context.Context, in *SignBatchRequest, opts ...grpc.CallOption) (*SignBatchResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.SignBatch(ctx, in, opts...)
}

// 消息签名
func (m *defaultSignerService) SignMessage(ctx context.Context, in *SignMessageRequest, opts ...grpc.CallOption) (*SignMessageResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.SignMessage(ctx, in, opts...)
}

// ========== 日志查询 ==========
func (m *defaultSignerService) QuerySignatureLogs(ctx context.Context, in *QuerySignatureLogsRequest, opts ...grpc.CallOption) (*QuerySignatureLogsResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.QuerySignatureLogs(ctx, in, opts...)
}

// ========== 健康检查 ==========
func (m *defaultSignerService) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.HealthCheck(ctx, in, opts...)
}

// ========== 热钱包初始化 / signer 解锁门禁 ==========
func (m *defaultSignerService) GetRuntimeStatus(ctx context.Context, in *GetRuntimeStatusRequest, opts ...grpc.CallOption) (*GetRuntimeStatusResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.GetRuntimeStatus(ctx, in, opts...)
}

// 开始热钱包初始化（生成24词助记词并进入分页展示会话）
func (m *defaultSignerService) StartHotWalletInit(ctx context.Context, in *StartHotWalletInitRequest, opts ...grpc.CallOption) (*StartHotWalletInitResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.StartHotWalletInit(ctx, in, opts...)
}

// 分页获取助记词（每页4个词）
func (m *defaultSignerService) GetHotWalletMnemonicPage(ctx context.Context, in *GetHotWalletMnemonicPageRequest, opts ...grpc.CallOption) (*GetHotWalletMnemonicPageResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.GetHotWalletMnemonicPage(ctx, in, opts...)
}

// 获取四词校验挑战
func (m *defaultSignerService) GetHotWalletMnemonicChallenge(ctx context.Context, in *GetHotWalletMnemonicChallengeRequest, opts ...grpc.CallOption) (*GetHotWalletMnemonicChallengeResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.GetHotWalletMnemonicChallenge(ctx, in, opts...)
}

// 验证四词校验挑战
func (m *defaultSignerService) VerifyHotWalletMnemonicChallenge(ctx context.Context, in *VerifyHotWalletMnemonicChallengeRequest, opts ...grpc.CallOption) (*VerifyHotWalletMnemonicChallengeResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.VerifyHotWalletMnemonicChallenge(ctx, in, opts...)
}

// 解锁热钱包（每次 signer 重启后需要重新解锁）
func (m *defaultSignerService) UnlockHotWallet(ctx context.Context, in *UnlockHotWalletRequest, opts ...grpc.CallOption) (*UnlockHotWalletResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.UnlockHotWallet(ctx, in, opts...)
}

// 手动锁定（可选）
func (m *defaultSignerService) LockHotWallet(ctx context.Context, in *LockHotWalletRequest, opts ...grpc.CallOption) (*LockHotWalletResponse, error) {
	client := pb.NewSignerServiceClient(m.cli.Conn())
	return client.LockHotWallet(ctx, in, opts...)
}
