// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: business.proto

package server

import (
	"context"

	"internalwallet/proto/pb"
	"internalwallet/services/business/rpc/internal/logic"
	"internalwallet/services/business/rpc/internal/svc"
)

type BusinessServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedBusinessServer
}

func NewBusinessServer(svcCtx *svc.ServiceContext) *BusinessServer {
	return &BusinessServer{
		svcCtx: svcCtx,
	}
}

// ==================== Auth ====================
func (s *BusinessServer) LoginByEmailCode(ctx context.Context, in *pb.LoginByEmailCodeRequest) (*pb.LoginByEmailCodeResponse, error) {
	l := logic.NewLoginByEmailCodeLogic(ctx, s.svcCtx)
	return l.LoginByEmailCode(in)
}

// 登录（手机+验证码）
func (s *BusinessServer) LoginByPhoneCode(ctx context.Context, in *pb.LoginByPhoneCodeRequest) (*pb.LoginByPhoneCodeResponse, error) {
	l := logic.NewLoginByPhoneCodeLogic(ctx, s.svcCtx)
	return l.LoginByPhoneCode(in)
}

// 登录（Google OAuth）
func (s *BusinessServer) LoginByGoogle(ctx context.Context, in *pb.LoginByGoogleRequest) (*pb.LoginByGoogleResponse, error) {
	l := logic.NewLoginByGoogleLogic(ctx, s.svcCtx)
	return l.LoginByGoogle(in)
}

// 忘记密码（邮箱+验证码）
func (s *BusinessServer) ForgotPasswordByEmail(ctx context.Context, in *pb.ForgotPasswordByEmailRequest) (*pb.ForgotPasswordByEmailResponse, error) {
	l := logic.NewForgotPasswordByEmailLogic(ctx, s.svcCtx)
	return l.ForgotPasswordByEmail(in)
}

// 忘记密码（手机+验证码）
func (s *BusinessServer) ForgotPasswordByPhone(ctx context.Context, in *pb.ForgotPasswordByPhoneRequest) (*pb.ForgotPasswordByPhoneResponse, error) {
	l := logic.NewForgotPasswordByPhoneLogic(ctx, s.svcCtx)
	return l.ForgotPasswordByPhone(in)
}

// Geetest 验证
func (s *BusinessServer) ValidateGeetest(ctx context.Context, in *pb.ValidateGeetestRequest) (*pb.ValidateGeetestResponse, error) {
	l := logic.NewValidateGeetestLogic(ctx, s.svcCtx)
	return l.ValidateGeetest(in)
}

// 获取支持的国家/地区区号
func (s *BusinessServer) GetCountryCodes(ctx context.Context, in *pb.GetCountryCodesRequest) (*pb.GetCountryCodesResponse, error) {
	l := logic.NewGetCountryCodesLogic(ctx, s.svcCtx)
	return l.GetCountryCodes(in)
}

func (s *BusinessServer) RefreshToken(ctx context.Context, in *pb.RefreshTokenReq) (*pb.RefreshTokenResp, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

func (s *BusinessServer) SendSMSCode(ctx context.Context, in *pb.SendSMSCodeReq) (*pb.SendSMSCodeResp, error) {
	l := logic.NewSendSMSCodeLogic(ctx, s.svcCtx)
	return l.SendSMSCode(in)
}

func (s *BusinessServer) SendEmailCode(ctx context.Context, in *pb.SendEmailCodeReq) (*pb.SendEmailCodeResp, error) {
	l := logic.NewSendEmailCodeLogic(ctx, s.svcCtx)
	return l.SendEmailCode(in)
}

// 登出
func (s *BusinessServer) Logout(ctx context.Context, in *pb.LogoutReq) (*pb.LogoutResp, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

// 资产页
func (s *BusinessServer) GetAssetOverview(ctx context.Context, in *pb.GetAssetOverviewReq) (*pb.GetAssetOverviewResp, error) {
	l := logic.NewGetAssetOverviewLogic(ctx, s.svcCtx)
	return l.GetAssetOverview(in)
}

func (s *BusinessServer) GetAssetDetail(ctx context.Context, in *pb.GetAssetDetailReq) (*pb.GetAssetDetailResp, error) {
	l := logic.NewGetAssetDetailLogic(ctx, s.svcCtx)
	return l.GetAssetDetail(in)
}

// 获取所有资产配置（包含精度等信息）
func (s *BusinessServer) GetAssetConfig(ctx context.Context, in *pb.GetAssetConfigReq) (*pb.GetAssetConfigResp, error) {
	l := logic.NewGetAssetConfigLogic(ctx, s.svcCtx)
	return l.GetAssetConfig(in)
}

func (s *BusinessServer) ListTransactionRecords(ctx context.Context, in *pb.ListTransactionRecordsReq) (*pb.ListTransactionRecordsResp, error) {
	l := logic.NewListTransactionRecordsLogic(ctx, s.svcCtx)
	return l.ListTransactionRecords(in)
}

func (s *BusinessServer) GetTransactionRecordDetail(ctx context.Context, in *pb.GetTransactionRecordDetailReq) (*pb.GetTransactionRecordDetailResp, error) {
	l := logic.NewGetTransactionRecordDetailLogic(ctx, s.svcCtx)
	return l.GetTransactionRecordDetail(in)
}

func (s *BusinessServer) GetDepositInfo(ctx context.Context, in *pb.GetDepositInfoReq) (*pb.GetDepositInfoResp, error) {
	l := logic.NewGetDepositInfoLogic(ctx, s.svcCtx)
	return l.GetDepositInfo(in)
}

func (s *BusinessServer) CreateDeposit(ctx context.Context, in *pb.CreateDepositReq) (*pb.CreateDepositResp, error) {
	l := logic.NewCreateDepositLogic(ctx, s.svcCtx)
	return l.CreateDeposit(in)
}

func (s *BusinessServer) ListDepositRecords(ctx context.Context, in *pb.ListDepositRecordsReq) (*pb.ListDepositRecordsResp, error) {
	l := logic.NewListDepositRecordsLogic(ctx, s.svcCtx)
	return l.ListDepositRecords(in)
}

func (s *BusinessServer) GetDepositDetail(ctx context.Context, in *pb.GetDepositDetailReq) (*pb.GetDepositDetailResp, error) {
	l := logic.NewGetDepositDetailLogic(ctx, s.svcCtx)
	return l.GetDepositDetail(in)
}

// 资产-充值地址簿（同链多地址）
func (s *BusinessServer) ListDepositAddressBook(ctx context.Context, in *pb.ListDepositAddressBookReq) (*pb.ListDepositAddressBookResp, error) {
	l := logic.NewListDepositAddressBookLogic(ctx, s.svcCtx)
	return l.ListDepositAddressBook(in)
}

func (s *BusinessServer) CreateDepositAddressBook(ctx context.Context, in *pb.CreateDepositAddressBookReq) (*pb.CreateDepositAddressBookResp, error) {
	l := logic.NewCreateDepositAddressBookLogic(ctx, s.svcCtx)
	return l.CreateDepositAddressBook(in)
}

func (s *BusinessServer) GetDepositAddressBookDetail(ctx context.Context, in *pb.GetDepositAddressBookDetailReq) (*pb.GetDepositAddressBookDetailResp, error) {
	l := logic.NewGetDepositAddressBookDetailLogic(ctx, s.svcCtx)
	return l.GetDepositAddressBookDetail(in)
}

func (s *BusinessServer) UpdateDepositAddressBook(ctx context.Context, in *pb.UpdateDepositAddressBookReq) (*pb.UpdateDepositAddressBookResp, error) {
	l := logic.NewUpdateDepositAddressBookLogic(ctx, s.svcCtx)
	return l.UpdateDepositAddressBook(in)
}

func (s *BusinessServer) DeleteDepositAddressBook(ctx context.Context, in *pb.DeleteDepositAddressBookReq) (*pb.DeleteDepositAddressBookResp, error) {
	l := logic.NewDeleteDepositAddressBookLogic(ctx, s.svcCtx)
	return l.DeleteDepositAddressBook(in)
}

func (s *BusinessServer) SetDefaultDepositAddressBook(ctx context.Context, in *pb.SetDefaultDepositAddressBookReq) (*pb.SetDefaultDepositAddressBookResp, error) {
	l := logic.NewSetDefaultDepositAddressBookLogic(ctx, s.svcCtx)
	return l.SetDefaultDepositAddressBook(in)
}

func (s *BusinessServer) ListDepositAddressBookDeposits(ctx context.Context, in *pb.ListDepositAddressBookDepositsReq) (*pb.ListDepositAddressBookDepositsResp, error) {
	l := logic.NewListDepositAddressBookDepositsLogic(ctx, s.svcCtx)
	return l.ListDepositAddressBookDeposits(in)
}

func (s *BusinessServer) ListActionAssets(ctx context.Context, in *pb.ListActionAssetsReq) (*pb.ListActionAssetsResp, error) {
	l := logic.NewListActionAssetsLogic(ctx, s.svcCtx)
	return l.ListActionAssets(in)
}

func (s *BusinessServer) ListActionNetworks(ctx context.Context, in *pb.ListActionNetworksReq) (*pb.ListActionNetworksResp, error) {
	l := logic.NewListActionNetworksLogic(ctx, s.svcCtx)
	return l.ListActionNetworks(in)
}

// 资产页-币种提现手续费规则配置查询
func (s *BusinessServer) GetAssetWithdrawFeeConfig(ctx context.Context, in *pb.GetAssetWithdrawFeeConfigReq) (*pb.GetAssetWithdrawFeeConfigResp, error) {
	l := logic.NewGetAssetWithdrawFeeConfigLogic(ctx, s.svcCtx)
	return l.GetAssetWithdrawFeeConfig(in)
}

// 资产页-汇率查询
func (s *BusinessServer) GetExchangeRate(ctx context.Context, in *pb.GetExchangeRateReq) (*pb.GetExchangeRateResp, error) {
	l := logic.NewGetExchangeRateLogic(ctx, s.svcCtx)
	return l.GetExchangeRate(in)
}

// 资产页-法币汇率列表（1 USDT = n 法币）
func (s *BusinessServer) ListFiatRates(ctx context.Context, in *pb.ListFiatRatesReq) (*pb.ListFiatRatesResp, error) {
	l := logic.NewListFiatRatesLogic(ctx, s.svcCtx)
	return l.ListFiatRates(in)
}

func (s *BusinessServer) GetWithdrawInfo(ctx context.Context, in *pb.GetWithdrawInfoReq) (*pb.GetWithdrawInfoResp, error) {
	l := logic.NewGetWithdrawInfoLogic(ctx, s.svcCtx)
	return l.GetWithdrawInfo(in)
}

// Web2 提币手续费预估（仅计算手续费规则，不构建链上交易，不使用 Web3 gas 接口）
func (s *BusinessServer) EstimateWithdrawFee(ctx context.Context, in *pb.EstimateWithdrawFeeReq) (*pb.EstimateWithdrawFeeResp, error) {
	l := logic.NewEstimateWithdrawFeeLogic(ctx, s.svcCtx)
	return l.EstimateWithdrawFee(in)
}

// Web2 提币手续费计算（校验余额；返回 fee/min_withdraw_amount/required_amount）
func (s *BusinessServer) CalcWithdrawFee(ctx context.Context, in *pb.CalcWithdrawFeeReq) (*pb.CalcWithdrawFeeResp, error) {
	l := logic.NewCalcWithdrawFeeLogic(ctx, s.svcCtx)
	return l.CalcWithdrawFee(in)
}

func (s *BusinessServer) CreateWithdraw(ctx context.Context, in *pb.CreateWithdrawReq) (*pb.CreateWithdrawResp, error) {
	l := logic.NewCreateWithdrawLogic(ctx, s.svcCtx)
	return l.CreateWithdraw(in)
}

func (s *BusinessServer) ListWithdrawRecords(ctx context.Context, in *pb.ListWithdrawRecordsReq) (*pb.ListWithdrawRecordsResp, error) {
	l := logic.NewListWithdrawRecordsLogic(ctx, s.svcCtx)
	return l.ListWithdrawRecords(in)
}

func (s *BusinessServer) GetWithdrawAuditStatus(ctx context.Context, in *pb.GetWithdrawAuditStatusReq) (*pb.GetWithdrawAuditStatusResp, error) {
	l := logic.NewGetWithdrawAuditStatusLogic(ctx, s.svcCtx)
	return l.GetWithdrawAuditStatus(in)
}

func (s *BusinessServer) GetWithdrawDetail(ctx context.Context, in *pb.GetWithdrawDetailReq) (*pb.GetWithdrawDetailResp, error) {
	l := logic.NewGetWithdrawDetailLogic(ctx, s.svcCtx)
	return l.GetWithdrawDetail(in)
}

// 资产页-消息通知（Web2 用户）
func (s *BusinessServer) ListNotifications(ctx context.Context, in *pb.ListNotificationsReq) (*pb.ListNotificationsResp, error) {
	l := logic.NewListNotificationsLogic(ctx, s.svcCtx)
	return l.ListNotifications(in)
}

func (s *BusinessServer) MarkNotificationRead(ctx context.Context, in *pb.MarkNotificationReadReq) (*pb.MarkNotificationReadResp, error) {
	l := logic.NewMarkNotificationReadLogic(ctx, s.svcCtx)
	return l.MarkNotificationRead(in)
}

func (s *BusinessServer) MarkAllNotificationsRead(ctx context.Context, in *pb.MarkAllNotificationsReadReq) (*pb.MarkAllNotificationsReadResp, error) {
	l := logic.NewMarkAllNotificationsReadLogic(ctx, s.svcCtx)
	return l.MarkAllNotificationsRead(in)
}

func (s *BusinessServer) DeleteNotification(ctx context.Context, in *pb.DeleteNotificationReq) (*pb.DeleteNotificationResp, error) {
	l := logic.NewDeleteNotificationLogic(ctx, s.svcCtx)
	return l.DeleteNotification(in)
}

func (s *BusinessServer) ClearAllNotifications(ctx context.Context, in *pb.ClearAllNotificationsReq) (*pb.ClearAllNotificationsResp, error) {
	l := logic.NewClearAllNotificationsLogic(ctx, s.svcCtx)
	return l.ClearAllNotifications(in)
}

// 内部接口：创建消息通知（供业务逻辑调用）
func (s *BusinessServer) CreateUserNotification(ctx context.Context, in *pb.CreateUserNotificationReq) (*pb.CreateUserNotificationResp, error) {
	l := logic.NewCreateUserNotificationLogic(ctx, s.svcCtx)
	return l.CreateUserNotification(in)
}

// 推送通知：通过别名发送推送（供业务逻辑调用）
func (s *BusinessServer) SendPushNotificationByAlias(ctx context.Context, in *pb.SendPushNotificationByAliasReq) (*pb.SendPushNotificationByAliasResp, error) {
	l := logic.NewSendPushNotificationByAliasLogic(ctx, s.svcCtx)
	return l.SendPushNotificationByAlias(in)
}

// 推送通知：通过设备ID发送推送（Web3用户专用）
func (s *BusinessServer) SendPushNotificationByDeviceToken(ctx context.Context, in *pb.SendPushNotificationByDeviceTokenReq) (*pb.SendPushNotificationByDeviceTokenResp, error) {
	l := logic.NewSendPushNotificationByDeviceTokenLogic(ctx, s.svcCtx)
	return l.SendPushNotificationByDeviceToken(in)
}

// 设备管理：注册设备（Web3用户专用）
func (s *BusinessServer) RegisterDevice(ctx context.Context, in *pb.RegisterDeviceReq) (*pb.RegisterDeviceResp, error) {
	l := logic.NewRegisterDeviceLogic(ctx, s.svcCtx)
	return l.RegisterDevice(in)
}

func (s *BusinessServer) GetMyOverview(ctx context.Context, in *pb.GetMyOverviewReq) (*pb.GetMyOverviewResp, error) {
	l := logic.NewGetMyOverviewLogic(ctx, s.svcCtx)
	return l.GetMyOverview(in)
}

func (s *BusinessServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoReq) (*pb.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *BusinessServer) UpdateUserInfo(ctx context.Context, in *pb.UpdateUserInfoReq) (*pb.UpdateUserInfoResp, error) {
	l := logic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}

func (s *BusinessServer) BindEmail(ctx context.Context, in *pb.BindEmailReq) (*pb.BindEmailResp, error) {
	l := logic.NewBindEmailLogic(ctx, s.svcCtx)
	return l.BindEmail(in)
}

func (s *BusinessServer) ChangeEmail(ctx context.Context, in *pb.ChangeEmailReq) (*pb.ChangeEmailResp, error) {
	l := logic.NewChangeEmailLogic(ctx, s.svcCtx)
	return l.ChangeEmail(in)
}

// 我的页-手机号
func (s *BusinessServer) BindPhone(ctx context.Context, in *pb.BindPhoneReq) (*pb.BindPhoneResp, error) {
	l := logic.NewBindPhoneLogic(ctx, s.svcCtx)
	return l.BindPhone(in)
}

func (s *BusinessServer) ChangePhone(ctx context.Context, in *pb.ChangePhoneReq) (*pb.ChangePhoneResp, error) {
	l := logic.NewChangePhoneLogic(ctx, s.svcCtx)
	return l.ChangePhone(in)
}

func (s *BusinessServer) ListWalletProviders(ctx context.Context, in *pb.ListWalletProvidersReq) (*pb.ListWalletProvidersResp, error) {
	l := logic.NewListWalletProvidersLogic(ctx, s.svcCtx)
	return l.ListWalletProviders(in)
}

func (s *BusinessServer) ListProviderAccounts(ctx context.Context, in *pb.ListProviderAccountsReq) (*pb.ListProviderAccountsResp, error) {
	l := logic.NewListProviderAccountsLogic(ctx, s.svcCtx)
	return l.ListProviderAccounts(in)
}

func (s *BusinessServer) LinkWalletAccount(ctx context.Context, in *pb.LinkWalletAccountReq) (*pb.LinkWalletAccountResp, error) {
	l := logic.NewLinkWalletAccountLogic(ctx, s.svcCtx)
	return l.LinkWalletAccount(in)
}

func (s *BusinessServer) UnlinkWalletAccount(ctx context.Context, in *pb.UnlinkWalletAccountReq) (*pb.UnlinkWalletAccountResp, error) {
	l := logic.NewUnlinkWalletAccountLogic(ctx, s.svcCtx)
	return l.UnlinkWalletAccount(in)
}

func (s *BusinessServer) SetPrimaryLinkedWallet(ctx context.Context, in *pb.SetPrimaryLinkedWalletReq) (*pb.SetPrimaryLinkedWalletResp, error) {
	l := logic.NewSetPrimaryLinkedWalletLogic(ctx, s.svcCtx)
	return l.SetPrimaryLinkedWallet(in)
}

func (s *BusinessServer) GetLinkedWalletAccounts(ctx context.Context, in *pb.GetLinkedWalletAccountsReq) (*pb.GetLinkedWalletAccountsResp, error) {
	l := logic.NewGetLinkedWalletAccountsLogic(ctx, s.svcCtx)
	return l.GetLinkedWalletAccounts(in)
}

// 我的页-登录密码
func (s *BusinessServer) ChangePassword(ctx context.Context, in *pb.ChangePasswordReq) (*pb.ChangePasswordResp, error) {
	l := logic.NewChangePasswordLogic(ctx, s.svcCtx)
	return l.ChangePassword(in)
}

func (s *BusinessServer) SetTradePassword(ctx context.Context, in *pb.SetTradePasswordReq) (*pb.SetTradePasswordResp, error) {
	l := logic.NewSetTradePasswordLogic(ctx, s.svcCtx)
	return l.SetTradePassword(in)
}

func (s *BusinessServer) ResetTradePassword(ctx context.Context, in *pb.ResetTradePasswordReq) (*pb.ResetTradePasswordResp, error) {
	l := logic.NewResetTradePasswordLogic(ctx, s.svcCtx)
	return l.ResetTradePassword(in)
}

func (s *BusinessServer) VerifyTradePassword(ctx context.Context, in *pb.VerifyTradePasswordReq) (*pb.VerifyTradePasswordResp, error) {
	l := logic.NewVerifyTradePasswordLogic(ctx, s.svcCtx)
	return l.VerifyTradePassword(in)
}

// 我的页-Web3交易密码
func (s *BusinessServer) SetWeb3TradePassword(ctx context.Context, in *pb.SetWeb3TradePasswordReq) (*pb.SetWeb3TradePasswordResp, error) {
	l := logic.NewSetWeb3TradePasswordLogic(ctx, s.svcCtx)
	return l.SetWeb3TradePassword(in)
}

func (s *BusinessServer) VerifyWeb3TradePassword(ctx context.Context, in *pb.VerifyWeb3TradePasswordReq) (*pb.VerifyWeb3TradePasswordResp, error) {
	l := logic.NewVerifyWeb3TradePasswordLogic(ctx, s.svcCtx)
	return l.VerifyWeb3TradePassword(in)
}

func (s *BusinessServer) UpdateWeb3TradePassword(ctx context.Context, in *pb.UpdateWeb3TradePasswordReq) (*pb.UpdateWeb3TradePasswordResp, error) {
	l := logic.NewUpdateWeb3TradePasswordLogic(ctx, s.svcCtx)
	return l.UpdateWeb3TradePassword(in)
}

// 我的页-使用设置-生物识别（Web2）
func (s *BusinessServer) RegisterBiometricKey(ctx context.Context, in *pb.RegisterBiometricKeyReq) (*pb.RegisterBiometricKeyResp, error) {
	l := logic.NewRegisterBiometricKeyLogic(ctx, s.svcCtx)
	return l.RegisterBiometricKey(in)
}

// 创建提币生物识别挑战（用于签名）
func (s *BusinessServer) CreateWithdrawBiometricChallenge(ctx context.Context, in *pb.CreateWithdrawBiometricChallengeReq) (*pb.CreateBiometricChallengeResp, error) {
	l := logic.NewCreateWithdrawBiometricChallengeLogic(ctx, s.svcCtx)
	return l.CreateWithdrawBiometricChallenge(in)
}

// 创建提现免审白名单绑定生物识别挑战（用于签名）
func (s *BusinessServer) CreateWithdrawAuditWhitelistBindingBiometricChallenge(ctx context.Context, in *pb.CreateWithdrawAuditWhitelistBindingBiometricChallengeReq) (*pb.CreateBiometricChallengeResp, error) {
	l := logic.NewCreateWithdrawAuditWhitelistBindingBiometricChallengeLogic(ctx, s.svcCtx)
	return l.CreateWithdrawAuditWhitelistBindingBiometricChallenge(in)
}

// 创建重置交易密码生物识别挑战（用于签名）
func (s *BusinessServer) CreateResetTradePasswordBiometricChallenge(ctx context.Context, in *pb.CreateResetTradePasswordBiometricChallengeReq) (*pb.CreateBiometricChallengeResp, error) {
	l := logic.NewCreateResetTradePasswordBiometricChallengeLogic(ctx, s.svcCtx)
	return l.CreateResetTradePasswordBiometricChallenge(in)
}

// 解绑当前用户生物识别（仅交易密码）
func (s *BusinessServer) UnbindBiometric(ctx context.Context, in *pb.UnbindBiometricReq) (*pb.UnbindBiometricResp, error) {
	l := logic.NewUnbindBiometricLogic(ctx, s.svcCtx)
	return l.UnbindBiometric(in)
}

// 我的页-使用设置-双重认证
func (s *BusinessServer) GetGoogleAuthSetup(ctx context.Context, in *pb.GetGoogleAuthSetupReq) (*pb.GetGoogleAuthSetupResp, error) {
	l := logic.NewGetGoogleAuthSetupLogic(ctx, s.svcCtx)
	return l.GetGoogleAuthSetup(in)
}

// 绑定 Google 验证器
func (s *BusinessServer) BindGoogleAuth(ctx context.Context, in *pb.BindGoogleAuthReq) (*pb.BindGoogleAuthResp, error) {
	l := logic.NewBindGoogleAuthLogic(ctx, s.svcCtx)
	return l.BindGoogleAuth(in)
}

// 解绑 Google 验证器
func (s *BusinessServer) UnbindGoogleAuth(ctx context.Context, in *pb.UnbindGoogleAuthReq) (*pb.UnbindGoogleAuthResp, error) {
	l := logic.NewUnbindGoogleAuthLogic(ctx, s.svcCtx)
	return l.UnbindGoogleAuth(in)
}

// 关闭双重认证（不解绑 Google 验证器）
func (s *BusinessServer) DisableGoogleAuth2FA(ctx context.Context, in *pb.DisableGoogleAuth2FAReq) (*pb.DisableGoogleAuth2FAResp, error) {
	l := logic.NewDisableGoogleAuth2FALogic(ctx, s.svcCtx)
	return l.DisableGoogleAuth2FA(in)
}

// 开启双重认证（已绑定GA，传验证码开启）
func (s *BusinessServer) EnableGoogleAuth2FA(ctx context.Context, in *pb.EnableGoogleAuth2FAReq) (*pb.EnableGoogleAuth2FAResp, error) {
	l := logic.NewEnableGoogleAuth2FALogic(ctx, s.svcCtx)
	return l.EnableGoogleAuth2FA(in)
}

// 关闭双重认证（已绑定GA，传验证码关闭）
func (s *BusinessServer) DisableGoogleAuth2FAWithCode(ctx context.Context, in *pb.DisableGoogleAuth2FAWithCodeReq) (*pb.DisableGoogleAuth2FAWithCodeResp, error) {
	l := logic.NewDisableGoogleAuth2FAWithCodeLogic(ctx, s.svcCtx)
	return l.DisableGoogleAuth2FAWithCode(in)
}

// 校验Google验证器验证码（仅校验，不做任何状态修改）
func (s *BusinessServer) VerifyGoogleAuthCode(ctx context.Context, in *pb.VerifyGoogleAuthCodeReq) (*pb.VerifyGoogleAuthCodeResp, error) {
	l := logic.NewVerifyGoogleAuthCodeLogic(ctx, s.svcCtx)
	return l.VerifyGoogleAuthCode(in)
}

// 我的页-使用设置－登录记录
func (s *BusinessServer) ListLoginRecords(ctx context.Context, in *pb.ListLoginRecordsReq) (*pb.ListLoginRecordsResp, error) {
	l := logic.NewListLoginRecordsLogic(ctx, s.svcCtx)
	return l.ListLoginRecords(in)
}

// 我的页-使用设置－钱包地址（链上地址）
func (s *BusinessServer) ListWalletAddresses(ctx context.Context, in *pb.ListWalletAddressesReq) (*pb.ListWalletAddressesResp, error) {
	l := logic.NewListWalletAddressesLogic(ctx, s.svcCtx)
	return l.ListWalletAddresses(in)
}

func (s *BusinessServer) AddWalletAddress(ctx context.Context, in *pb.AddWalletAddressReq) (*pb.AddWalletAddressResp, error) {
	l := logic.NewAddWalletAddressLogic(ctx, s.svcCtx)
	return l.AddWalletAddress(in)
}

func (s *BusinessServer) UpdateWalletAddress(ctx context.Context, in *pb.UpdateWalletAddressReq) (*pb.UpdateWalletAddressResp, error) {
	l := logic.NewUpdateWalletAddressLogic(ctx, s.svcCtx)
	return l.UpdateWalletAddress(in)
}

func (s *BusinessServer) DeleteWalletAddress(ctx context.Context, in *pb.DeleteWalletAddressReq) (*pb.DeleteWalletAddressResp, error) {
	l := logic.NewDeleteWalletAddressLogic(ctx, s.svcCtx)
	return l.DeleteWalletAddress(in)
}

func (s *BusinessServer) SetDefaultWalletAddress(ctx context.Context, in *pb.SetDefaultWalletAddressReq) (*pb.SetDefaultWalletAddressResp, error) {
	l := logic.NewSetDefaultWalletAddressLogic(ctx, s.svcCtx)
	return l.SetDefaultWalletAddress(in)
}

func (s *BusinessServer) ValidateWalletAddress(ctx context.Context, in *pb.ValidateWalletAddressReq) (*pb.ValidateWalletAddressResp, error) {
	l := logic.NewValidateWalletAddressLogic(ctx, s.svcCtx)
	return l.ValidateWalletAddress(in)
}

// 我的页-使用设置－钱包地址（内部地址，通过UID/邮箱添加平台内用户）
func (s *BusinessServer) ListInternalWalletAddresses(ctx context.Context, in *pb.ListInternalWalletAddressesReq) (*pb.ListInternalWalletAddressesResp, error) {
	l := logic.NewListInternalWalletAddressesLogic(ctx, s.svcCtx)
	return l.ListInternalWalletAddresses(in)
}

func (s *BusinessServer) AddInternalWalletAddress(ctx context.Context, in *pb.AddInternalWalletAddressReq) (*pb.AddInternalWalletAddressResp, error) {
	l := logic.NewAddInternalWalletAddressLogic(ctx, s.svcCtx)
	return l.AddInternalWalletAddress(in)
}

func (s *BusinessServer) UpdateInternalWalletAddress(ctx context.Context, in *pb.UpdateInternalWalletAddressReq) (*pb.UpdateInternalWalletAddressResp, error) {
	l := logic.NewUpdateInternalWalletAddressLogic(ctx, s.svcCtx)
	return l.UpdateInternalWalletAddress(in)
}

func (s *BusinessServer) DeleteInternalWalletAddress(ctx context.Context, in *pb.DeleteInternalWalletAddressReq) (*pb.DeleteInternalWalletAddressResp, error) {
	l := logic.NewDeleteInternalWalletAddressLogic(ctx, s.svcCtx)
	return l.DeleteInternalWalletAddress(in)
}

func (s *BusinessServer) LookupInternalUser(ctx context.Context, in *pb.LookupInternalUserReq) (*pb.LookupInternalUserResp, error) {
	l := logic.NewLookupInternalUserLogic(ctx, s.svcCtx)
	return l.LookupInternalUser(in)
}

// 内部转账（用户之间的资产转移，支持审核）
func (s *BusinessServer) ValidateInternalTransferTarget(ctx context.Context, in *pb.ValidateInternalTransferTargetReq) (*pb.ValidateInternalTransferTargetResp, error) {
	l := logic.NewValidateInternalTransferTargetLogic(ctx, s.svcCtx)
	return l.ValidateInternalTransferTarget(in)
}

func (s *BusinessServer) SubmitInternalTransfer(ctx context.Context, in *pb.SubmitInternalTransferReq) (*pb.SubmitInternalTransferResp, error) {
	l := logic.NewSubmitInternalTransferLogic(ctx, s.svcCtx)
	return l.SubmitInternalTransfer(in)
}

func (s *BusinessServer) CancelInternalTransfer(ctx context.Context, in *pb.CancelInternalTransferReq) (*pb.CancelInternalTransferResp, error) {
	l := logic.NewCancelInternalTransferLogic(ctx, s.svcCtx)
	return l.CancelInternalTransfer(in)
}

// 提现免审白名单（用户自绑定）
func (s *BusinessServer) ListWithdrawAuditWhitelistBindableNetworks(ctx context.Context, in *pb.ListWithdrawAuditWhitelistBindableNetworksReq) (*pb.ListWithdrawAuditWhitelistBindableNetworksResp, error) {
	l := logic.NewListWithdrawAuditWhitelistBindableNetworksLogic(ctx, s.svcCtx)
	return l.ListWithdrawAuditWhitelistBindableNetworks(in)
}

func (s *BusinessServer) SetMyWithdrawAuditWhitelistBinding(ctx context.Context, in *pb.SetMyWithdrawAuditWhitelistBindingReq) (*pb.SetMyWithdrawAuditWhitelistBindingResp, error) {
	l := logic.NewSetMyWithdrawAuditWhitelistBindingLogic(ctx, s.svcCtx)
	return l.SetMyWithdrawAuditWhitelistBinding(in)
}

func (s *BusinessServer) GetMyWithdrawAuditWhitelistBindingStatus(ctx context.Context, in *pb.GetMyWithdrawAuditWhitelistBindingStatusReq) (*pb.GetMyWithdrawAuditWhitelistBindingStatusResp, error) {
	l := logic.NewGetMyWithdrawAuditWhitelistBindingStatusLogic(ctx, s.svcCtx)
	return l.GetMyWithdrawAuditWhitelistBindingStatus(in)
}

func (s *BusinessServer) UnbindMyWithdrawAuditWhitelistBindings(ctx context.Context, in *pb.UnbindMyWithdrawAuditWhitelistBindingsReq) (*pb.UnbindMyWithdrawAuditWhitelistBindingsResp, error) {
	l := logic.NewUnbindMyWithdrawAuditWhitelistBindingsLogic(ctx, s.svcCtx)
	return l.UnbindMyWithdrawAuditWhitelistBindings(in)
}

// 我的页-偏好设置
func (s *BusinessServer) GetPreferences(ctx context.Context, in *pb.GetPreferencesReq) (*pb.GetPreferencesResp, error) {
	l := logic.NewGetPreferencesLogic(ctx, s.svcCtx)
	return l.GetPreferences(in)
}

func (s *BusinessServer) ListLanguageOptions(ctx context.Context, in *pb.ListLanguageOptionsReq) (*pb.ListLanguageOptionsResp, error) {
	l := logic.NewListLanguageOptionsLogic(ctx, s.svcCtx)
	return l.ListLanguageOptions(in)
}

func (s *BusinessServer) ListPriceUnitOptions(ctx context.Context, in *pb.ListPriceUnitOptionsReq) (*pb.ListPriceUnitOptionsResp, error) {
	l := logic.NewListPriceUnitOptionsLogic(ctx, s.svcCtx)
	return l.ListPriceUnitOptions(in)
}

func (s *BusinessServer) SetPreferences(ctx context.Context, in *pb.SetPreferencesReq) (*pb.SetPreferencesResp, error) {
	l := logic.NewSetPreferencesLogic(ctx, s.svcCtx)
	return l.SetPreferences(in)
}

// 获取客户端配置
func (s *BusinessServer) GetClientConfig(ctx context.Context, in *pb.GetClientConfigReq) (*pb.GetClientConfigResp, error) {
	l := logic.NewGetClientConfigLogic(ctx, s.svcCtx)
	return l.GetClientConfig(in)
}

// ==================== Web3 Swap (proxy to swap microservice) ====================
func (s *BusinessServer) SwapGetQuote(ctx context.Context, in *pb.BusinessSwapGetQuoteRequest) (*pb.BusinessSwapGetQuoteResponse, error) {
	l := logic.NewSwapGetQuoteLogic(ctx, s.svcCtx)
	return l.SwapGetQuote(in)
}

func (s *BusinessServer) SwapExecuteSwap(ctx context.Context, in *pb.BusinessSwapExecuteSwapRequest) (*pb.BusinessSwapExecuteSwapResponse, error) {
	l := logic.NewSwapExecuteSwapLogic(ctx, s.svcCtx)
	return l.SwapExecuteSwap(in)
}

func (s *BusinessServer) SwapGetApprovalTransaction(ctx context.Context, in *pb.BusinessSwapGetApprovalTransactionRequest) (*pb.BusinessSwapGetApprovalTransactionResponse, error) {
	l := logic.NewSwapGetApprovalTransactionLogic(ctx, s.svcCtx)
	return l.SwapGetApprovalTransaction(in)
}

func (s *BusinessServer) SwapResetApproval(ctx context.Context, in *pb.BusinessSwapResetApprovalRequest) (*pb.BusinessSwapResetApprovalResponse, error) {
	l := logic.NewSwapResetApprovalLogic(ctx, s.svcCtx)
	return l.SwapResetApproval(in)
}

func (s *BusinessServer) SwapGetSwapStatus(ctx context.Context, in *pb.BusinessSwapGetSwapStatusRequest) (*pb.BusinessSwapGetSwapStatusResponse, error) {
	l := logic.NewSwapGetSwapStatusLogic(ctx, s.svcCtx)
	return l.SwapGetSwapStatus(in)
}

func (s *BusinessServer) SwapGetSwapDetail(ctx context.Context, in *pb.BusinessSwapGetSwapDetailRequest) (*pb.BusinessSwapGetSwapDetailResponse, error) {
	l := logic.NewSwapGetSwapDetailLogic(ctx, s.svcCtx)
	return l.SwapGetSwapDetail(in)
}

func (s *BusinessServer) SwapGetSwapHistory(ctx context.Context, in *pb.BusinessSwapGetSwapHistoryRequest) (*pb.BusinessSwapGetSwapHistoryResponse, error) {
	l := logic.NewSwapGetSwapHistoryLogic(ctx, s.svcCtx)
	return l.SwapGetSwapHistory(in)
}

func (s *BusinessServer) SwapGetSupportedTokens(ctx context.Context, in *pb.BusinessSwapGetSupportedTokensRequest) (*pb.BusinessSwapGetSupportedTokensResponse, error) {
	l := logic.NewSwapGetSupportedTokensLogic(ctx, s.svcCtx)
	return l.SwapGetSupportedTokens(in)
}

func (s *BusinessServer) SwapGetSupportedChains(ctx context.Context, in *pb.BusinessSwapGetSupportedChainsRequest) (*pb.BusinessSwapGetSupportedChainsResponse, error) {
	l := logic.NewSwapGetSupportedChainsLogic(ctx, s.svcCtx)
	return l.SwapGetSupportedChains(in)
}

func (s *BusinessServer) SwapGetExternalSwapStatus(ctx context.Context, in *pb.BusinessSwapGetExternalSwapStatusRequest) (*pb.BusinessSwapGetExternalSwapStatusResponse, error) {
	l := logic.NewSwapGetExternalSwapStatusLogic(ctx, s.svcCtx)
	return l.SwapGetExternalSwapStatus(in)
}

// ==================== Web3 User Management ====================
func (s *BusinessServer) CreateWeb3User(ctx context.Context, in *pb.CreateWeb3UserReq) (*pb.CreateWeb3UserResp, error) {
	l := logic.NewCreateWeb3UserLogic(ctx, s.svcCtx)
	return l.CreateWeb3User(in)
}

// 添加 Web3 用户地址
func (s *BusinessServer) AddWeb3UserAddress(ctx context.Context, in *pb.AddWeb3UserAddressReq) (*pb.AddWeb3UserAddressResp, error) {
	l := logic.NewAddWeb3UserAddressLogic(ctx, s.svcCtx)
	return l.AddWeb3UserAddress(in)
}

// 批量添加 Web3 用户地址（一次添加多条链的地址）
func (s *BusinessServer) BatchAddWeb3UserAddress(ctx context.Context, in *pb.BatchAddWeb3UserAddressReq) (*pb.BatchAddWeb3UserAddressResp, error) {
	l := logic.NewBatchAddWeb3UserAddressLogic(ctx, s.svcCtx)
	return l.BatchAddWeb3UserAddress(in)
}

// 查询可用链列表（Web3 用户）
func (s *BusinessServer) ListWeb3Chains(ctx context.Context, in *pb.ListWeb3ChainsReq) (*pb.ListWeb3ChainsResp, error) {
	l := logic.NewListWeb3ChainsLogic(ctx, s.svcCtx)
	return l.ListWeb3Chains(in)
}

// 根据 device_id 获取 Web3 用户信息
func (s *BusinessServer) GetWeb3UserByDeviceId(ctx context.Context, in *pb.GetWeb3UserByDeviceIdReq) (*pb.GetWeb3UserByDeviceIdResp, error) {
	l := logic.NewGetWeb3UserByDeviceIdLogic(ctx, s.svcCtx)
	return l.GetWeb3UserByDeviceId(in)
}

// 获取 Web3 用户资产概览
func (s *BusinessServer) GetWeb3AssetOverview(ctx context.Context, in *pb.GetWeb3AssetOverviewReq) (*pb.GetWeb3AssetOverviewResp, error) {
	l := logic.NewGetWeb3AssetOverviewLogic(ctx, s.svcCtx)
	return l.GetWeb3AssetOverview(in)
}

// 获取 Web3 用户交易记录列表
func (s *BusinessServer) ListWeb3Transactions(ctx context.Context, in *pb.ListWeb3TransactionsReq) (*pb.ListWeb3TransactionsResp, error) {
	l := logic.NewListWeb3TransactionsLogic(ctx, s.svcCtx)
	return l.ListWeb3Transactions(in)
}

// 获取 Web3 交易详情
func (s *BusinessServer) GetWeb3TransactionDetail(ctx context.Context, in *pb.GetWeb3TransactionDetailReq) (*pb.GetWeb3TransactionDetailResp, error) {
	l := logic.NewGetWeb3TransactionDetailLogic(ctx, s.svcCtx)
	return l.GetWeb3TransactionDetail(in)
}

// Web3 交易结果查询（根据交易哈希查询状态和结果）
func (s *BusinessServer) GetWeb3TransactionResult(ctx context.Context, in *pb.GetWeb3TransactionResultReq) (*pb.GetWeb3TransactionResultResp, error) {
	l := logic.NewGetWeb3TransactionResultLogic(ctx, s.svcCtx)
	return l.GetWeb3TransactionResult(in)
}

// 广播 Web3 交易（Web3 用户专用）
func (s *BusinessServer) BroadcastWeb3Transaction(ctx context.Context, in *pb.BroadcastWeb3TransactionReq) (*pb.BroadcastWeb3TransactionResp, error) {
	l := logic.NewBroadcastWeb3TransactionLogic(ctx, s.svcCtx)
	return l.BroadcastWeb3Transaction(in)
}

// 获取 Web3 支持的资产列表（根据链）
func (s *BusinessServer) ListWeb3SupportedAssets(ctx context.Context, in *pb.ListWeb3SupportedAssetsReq) (*pb.ListWeb3SupportedAssetsResp, error) {
	l := logic.NewListWeb3SupportedAssetsLogic(ctx, s.svcCtx)
	return l.ListWeb3SupportedAssets(in)
}

// 获取 Web3 用户地址的 Nonce（用于构建 EVM 交易）
func (s *BusinessServer) GetWeb3Nonce(ctx context.Context, in *pb.GetWeb3NonceReq) (*pb.GetWeb3NonceResp, error) {
	l := logic.NewGetWeb3NonceLogic(ctx, s.svcCtx)
	return l.GetWeb3Nonce(in)
}

// 构建 Web3 TRON 交易（返回未签名的 rawData，供客户端签名）
func (s *BusinessServer) BuildTronTransaction(ctx context.Context, in *pb.BuildTronTransactionReq) (*pb.BuildTronTransactionResp, error) {
	l := logic.NewBuildTronTransactionLogic(ctx, s.svcCtx)
	return l.BuildTronTransaction(in)
}

// 获取 Web3 代币详细信息（合约地址、网络、价格、市值、持有者等）
func (s *BusinessServer) GetWeb3TokenDetail(ctx context.Context, in *pb.GetWeb3TokenDetailReq) (*pb.GetWeb3TokenDetailResp, error) {
	l := logic.NewGetWeb3TokenDetailLogic(ctx, s.svcCtx)
	return l.GetWeb3TokenDetail(in)
}
