// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: admin.proto

package server

import (
	"context"

	"internalwallet/proto/pb"
	"internalwallet/services/admin/rpc/internal/logic"
	"internalwallet/services/admin/rpc/internal/svc"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

// ==================== Auth ====================
func (s *AdminServer) RefreshToken(ctx context.Context, in *pb.RefreshTokenRequest) (*pb.RefreshTokenResponse, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

func (s *AdminServer) Logout(ctx context.Context, in *pb.LogoutRequest) (*pb.LogoutResponse, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

// ==================== Wallet Init / Signer Unlock ====================
func (s *AdminServer) GetHotWalletRuntimeStatus(ctx context.Context, in *pb.AdminGetHotWalletRuntimeStatusRequest) (*pb.AdminGetHotWalletRuntimeStatusResponse, error) {
	l := logic.NewGetHotWalletRuntimeStatusLogic(ctx, s.svcCtx)
	return l.GetHotWalletRuntimeStatus(in)
}

func (s *AdminServer) StartHotWalletInit(ctx context.Context, in *pb.AdminStartHotWalletInitRequest) (*pb.AdminStartHotWalletInitResponse, error) {
	l := logic.NewStartHotWalletInitLogic(ctx, s.svcCtx)
	return l.StartHotWalletInit(in)
}

func (s *AdminServer) GetHotWalletMnemonicPage(ctx context.Context, in *pb.AdminGetHotWalletMnemonicPageRequest) (*pb.AdminGetHotWalletMnemonicPageResponse, error) {
	l := logic.NewGetHotWalletMnemonicPageLogic(ctx, s.svcCtx)
	return l.GetHotWalletMnemonicPage(in)
}

func (s *AdminServer) GetHotWalletMnemonicChallenge(ctx context.Context, in *pb.AdminGetHotWalletMnemonicChallengeRequest) (*pb.AdminGetHotWalletMnemonicChallengeResponse, error) {
	l := logic.NewGetHotWalletMnemonicChallengeLogic(ctx, s.svcCtx)
	return l.GetHotWalletMnemonicChallenge(in)
}

func (s *AdminServer) VerifyHotWalletMnemonicChallenge(ctx context.Context, in *pb.AdminVerifyHotWalletMnemonicChallengeRequest) (*pb.AdminVerifyHotWalletMnemonicChallengeResponse, error) {
	l := logic.NewVerifyHotWalletMnemonicChallengeLogic(ctx, s.svcCtx)
	return l.VerifyHotWalletMnemonicChallenge(in)
}

func (s *AdminServer) UnlockSignerHotWallet(ctx context.Context, in *pb.AdminUnlockSignerHotWalletRequest) (*pb.AdminUnlockSignerHotWalletResponse, error) {
	l := logic.NewUnlockSignerHotWalletLogic(ctx, s.svcCtx)
	return l.UnlockSignerHotWallet(in)
}

// ==================== Admin MFA Flow (HTTP: /api/v1/admin/auth/*) ====================
func (s *AdminServer) AdminMFACaptchaGenerate(ctx context.Context, in *pb.AdminMFACaptchaGenerateRequest) (*pb.AdminMFACaptchaGenerateResponse, error) {
	l := logic.NewAdminMFACaptchaGenerateLogic(ctx, s.svcCtx)
	return l.AdminMFACaptchaGenerate(in)
}

func (s *AdminServer) AdminMFACaptchaValidate(ctx context.Context, in *pb.AdminMFACaptchaValidateRequest) (*pb.AdminMFACaptchaValidateResponse, error) {
	l := logic.NewAdminMFACaptchaValidateLogic(ctx, s.svcCtx)
	return l.AdminMFACaptchaValidate(in)
}

func (s *AdminServer) AdminMFALogin(ctx context.Context, in *pb.AdminMFALoginRequest) (*pb.AdminMFALoginResponse, error) {
	l := logic.NewAdminMFALoginLogic(ctx, s.svcCtx)
	return l.AdminMFALogin(in)
}

func (s *AdminServer) AdminMFAGetTwoFAQrCode(ctx context.Context, in *pb.AdminMFAGetTwoFAQrCodeRequest) (*pb.AdminMFAGetTwoFAQrCodeResponse, error) {
	l := logic.NewAdminMFAGetTwoFAQrCodeLogic(ctx, s.svcCtx)
	return l.AdminMFAGetTwoFAQrCode(in)
}

func (s *AdminServer) AdminMFABindTwoFA(ctx context.Context, in *pb.AdminMFABindTwoFARequest) (*pb.AdminMFABindTwoFAResponse, error) {
	l := logic.NewAdminMFABindTwoFALogic(ctx, s.svcCtx)
	return l.AdminMFABindTwoFA(in)
}

func (s *AdminServer) AdminMFAVerifyTwoFA(ctx context.Context, in *pb.AdminMFAVerifyTwoFARequest) (*pb.AdminMFAVerifyTwoFAResponse, error) {
	l := logic.NewAdminMFAVerifyTwoFALogic(ctx, s.svcCtx)
	return l.AdminMFAVerifyTwoFA(in)
}

// ==================== Admin Users ====================
func (s *AdminServer) ListAdmins(ctx context.Context, in *pb.ListAdminsRequest) (*pb.ListAdminsResponse, error) {
	l := logic.NewListAdminsLogic(ctx, s.svcCtx)
	return l.ListAdmins(in)
}

func (s *AdminServer) CreateAdmin(ctx context.Context, in *pb.CreateAdminRequest) (*pb.CreateAdminResponse, error) {
	l := logic.NewCreateAdminLogic(ctx, s.svcCtx)
	return l.CreateAdmin(in)
}

func (s *AdminServer) UpdateAdmin(ctx context.Context, in *pb.UpdateAdminRequest) (*pb.UpdateAdminResponse, error) {
	l := logic.NewUpdateAdminLogic(ctx, s.svcCtx)
	return l.UpdateAdmin(in)
}

func (s *AdminServer) DisableAdmin(ctx context.Context, in *pb.DisableAdminRequest) (*pb.DisableAdminResponse, error) {
	l := logic.NewDisableAdminLogic(ctx, s.svcCtx)
	return l.DisableAdmin(in)
}

func (s *AdminServer) ResetAdminPassword(ctx context.Context, in *pb.ResetAdminPasswordRequest) (*pb.ResetAdminPasswordResponse, error) {
	l := logic.NewResetAdminPasswordLogic(ctx, s.svcCtx)
	return l.ResetAdminPassword(in)
}

func (s *AdminServer) ResetAdminTwoFA(ctx context.Context, in *pb.ResetAdminTwoFARequest) (*pb.ResetAdminTwoFAResponse, error) {
	l := logic.NewResetAdminTwoFALogic(ctx, s.svcCtx)
	return l.ResetAdminTwoFA(in)
}

func (s *AdminServer) ChangeMyPassword(ctx context.Context, in *pb.ChangeMyPasswordRequest) (*pb.ChangeMyPasswordResponse, error) {
	l := logic.NewChangeMyPasswordLogic(ctx, s.svcCtx)
	return l.ChangeMyPassword(in)
}

// ==================== Users (Web2) ====================
func (s *AdminServer) ListUsers(ctx context.Context, in *pb.ListUsersRequest) (*pb.ListUsersResponse, error) {
	l := logic.NewListUsersLogic(ctx, s.svcCtx)
	return l.ListUsers(in)
}

func (s *AdminServer) GetUsersStatistics(ctx context.Context, in *pb.GetUsersStatisticsRequest) (*pb.GetUsersStatisticsResponse, error) {
	l := logic.NewGetUsersStatisticsLogic(ctx, s.svcCtx)
	return l.GetUsersStatistics(in)
}

func (s *AdminServer) ListUserWithdrawAuditWhitelistRules(ctx context.Context, in *pb.ListUserWithdrawAuditWhitelistRulesRequest) (*pb.ListUserWithdrawAuditWhitelistRulesResponse, error) {
	l := logic.NewListUserWithdrawAuditWhitelistRulesLogic(ctx, s.svcCtx)
	return l.ListUserWithdrawAuditWhitelistRules(in)
}

func (s *AdminServer) UpsertUserWithdrawAuditWhitelistRules(ctx context.Context, in *pb.UpsertUserWithdrawAuditWhitelistRulesRequest) (*pb.UpsertUserWithdrawAuditWhitelistRulesResponse, error) {
	l := logic.NewUpsertUserWithdrawAuditWhitelistRulesLogic(ctx, s.svcCtx)
	return l.UpsertUserWithdrawAuditWhitelistRules(in)
}

func (s *AdminServer) GetUserDetail(ctx context.Context, in *pb.GetUserDetailRequest) (*pb.GetUserDetailResponse, error) {
	l := logic.NewGetUserDetailLogic(ctx, s.svcCtx)
	return l.GetUserDetail(in)
}

func (s *AdminServer) FreezeUser(ctx context.Context, in *pb.FreezeUserRequest) (*pb.FreezeUserResponse, error) {
	l := logic.NewFreezeUserLogic(ctx, s.svcCtx)
	return l.FreezeUser(in)
}

func (s *AdminServer) UnfreezeUser(ctx context.Context, in *pb.UnfreezeUserRequest) (*pb.UnfreezeUserResponse, error) {
	l := logic.NewUnfreezeUserLogic(ctx, s.svcCtx)
	return l.UnfreezeUser(in)
}

func (s *AdminServer) TerminateUser(ctx context.Context, in *pb.TerminateUserRequest) (*pb.TerminateUserResponse, error) {
	l := logic.NewTerminateUserLogic(ctx, s.svcCtx)
	return l.TerminateUser(in)
}

func (s *AdminServer) UpdateUserRole(ctx context.Context, in *pb.UpdateUserRoleRequest) (*pb.UpdateUserRoleResponse, error) {
	l := logic.NewUpdateUserRoleLogic(ctx, s.svcCtx)
	return l.UpdateUserRole(in)
}

func (s *AdminServer) UpdateUserMemberLevel(ctx context.Context, in *pb.UpdateUserMemberLevelRequest) (*pb.UpdateUserMemberLevelResponse, error) {
	l := logic.NewUpdateUserMemberLevelLogic(ctx, s.svcCtx)
	return l.UpdateUserMemberLevel(in)
}

func (s *AdminServer) ResetUserPassword(ctx context.Context, in *pb.ResetUserPasswordRequest) (*pb.ResetUserPasswordResponse, error) {
	l := logic.NewResetUserPasswordLogic(ctx, s.svcCtx)
	return l.ResetUserPassword(in)
}

func (s *AdminServer) ResetUserTradePassword(ctx context.Context, in *pb.ResetUserTradePasswordRequest) (*pb.ResetUserTradePasswordResponse, error) {
	l := logic.NewResetUserTradePasswordLogic(ctx, s.svcCtx)
	return l.ResetUserTradePassword(in)
}

func (s *AdminServer) UnlockTradePassword(ctx context.Context, in *pb.UnlockTradePasswordRequest) (*pb.UnlockTradePasswordResponse, error) {
	l := logic.NewUnlockTradePasswordLogic(ctx, s.svcCtx)
	return l.UnlockTradePassword(in)
}

func (s *AdminServer) UpdateUserWithdrawAuditWhitelist(ctx context.Context, in *pb.UpdateUserWithdrawAuditWhitelistRequest) (*pb.UpdateUserWithdrawAuditWhitelistResponse, error) {
	l := logic.NewUpdateUserWithdrawAuditWhitelistLogic(ctx, s.svcCtx)
	return l.UpdateUserWithdrawAuditWhitelist(in)
}

func (s *AdminServer) UnbindUserTotp(ctx context.Context, in *pb.UnbindUserTotpRequest) (*pb.UnbindUserTotpResponse, error) {
	l := logic.NewUnbindUserTotpLogic(ctx, s.svcCtx)
	return l.UnbindUserTotp(in)
}

func (s *AdminServer) ListUser2FAHistory(ctx context.Context, in *pb.ListUser2FAHistoryRequest) (*pb.ListUser2FAHistoryResponse, error) {
	l := logic.NewListUser2FAHistoryLogic(ctx, s.svcCtx)
	return l.ListUser2FAHistory(in)
}

func (s *AdminServer) AddUserNote(ctx context.Context, in *pb.AddUserNoteRequest) (*pb.AddUserNoteResponse, error) {
	l := logic.NewAddUserNoteLogic(ctx, s.svcCtx)
	return l.AddUserNote(in)
}

func (s *AdminServer) ExportUsers(ctx context.Context, in *pb.ExportUsersRequest) (*pb.ExportUsersResponse, error) {
	l := logic.NewExportUsersLogic(ctx, s.svcCtx)
	return l.ExportUsers(in)
}

// ==================== My (Profile + RBAC) ====================
func (s *AdminServer) GetMe(ctx context.Context, in *pb.GetMeRequest) (*pb.GetMeResponse, error) {
	l := logic.NewGetMeLogic(ctx, s.svcCtx)
	return l.GetMe(in)
}

// ==================== Security (My Account) ====================
func (s *AdminServer) GetMySecuritySettings(ctx context.Context, in *pb.GetMySecuritySettingsRequest) (*pb.GetMySecuritySettingsResponse, error) {
	l := logic.NewGetMySecuritySettingsLogic(ctx, s.svcCtx)
	return l.GetMySecuritySettings(in)
}

func (s *AdminServer) StartTwoFASetup(ctx context.Context, in *pb.StartTwoFASetupRequest) (*pb.StartTwoFASetupResponse, error) {
	l := logic.NewStartTwoFASetupLogic(ctx, s.svcCtx)
	return l.StartTwoFASetup(in)
}

func (s *AdminServer) ConfirmTwoFASetup(ctx context.Context, in *pb.ConfirmTwoFASetupRequest) (*pb.ConfirmTwoFASetupResponse, error) {
	l := logic.NewConfirmTwoFASetupLogic(ctx, s.svcCtx)
	return l.ConfirmTwoFASetup(in)
}

func (s *AdminServer) StartTwoFARebind(ctx context.Context, in *pb.StartTwoFARebindRequest) (*pb.StartTwoFARebindResponse, error) {
	l := logic.NewStartTwoFARebindLogic(ctx, s.svcCtx)
	return l.StartTwoFARebind(in)
}

func (s *AdminServer) DisableTwoFA(ctx context.Context, in *pb.DisableTwoFARequest) (*pb.DisableTwoFAResponse, error) {
	l := logic.NewDisableTwoFALogic(ctx, s.svcCtx)
	return l.DisableTwoFA(in)
}

// ==================== RBAC v2 (My) ====================
func (s *AdminServer) GetMyRBAC(ctx context.Context, in *pb.GetMyRBACRequest) (*pb.GetMyRBACResponse, error) {
	l := logic.NewGetMyRBACLogic(ctx, s.svcCtx)
	return l.GetMyRBAC(in)
}

// RBAC v2 (UI helpers) - for frontend permission gating (scheme B)
func (s *AdminServer) GetRbacPermissionMap(ctx context.Context, in *pb.GetRbacPermissionMapRequest) (*pb.GetRbacPermissionMapResponse, error) {
	l := logic.NewGetRbacPermissionMapLogic(ctx, s.svcCtx)
	return l.GetRbacPermissionMap(in)
}

// ==================== RBAC v2 (Menus / Permissions / Roles) ====================
func (s *AdminServer) CreateMenu(ctx context.Context, in *pb.CreateMenuRequest) (*pb.CreateMenuResponse, error) {
	l := logic.NewCreateMenuLogic(ctx, s.svcCtx)
	return l.CreateMenu(in)
}

func (s *AdminServer) UpdateMenu(ctx context.Context, in *pb.UpdateMenuRequest) (*pb.UpdateMenuResponse, error) {
	l := logic.NewUpdateMenuLogic(ctx, s.svcCtx)
	return l.UpdateMenu(in)
}

func (s *AdminServer) DeleteMenu(ctx context.Context, in *pb.DeleteMenuRequest) (*pb.DeleteMenuResponse, error) {
	l := logic.NewDeleteMenuLogic(ctx, s.svcCtx)
	return l.DeleteMenu(in)
}

func (s *AdminServer) GetMenuById(ctx context.Context, in *pb.GetMenuByIdRequest) (*pb.GetMenuByIdResponse, error) {
	l := logic.NewGetMenuByIdLogic(ctx, s.svcCtx)
	return l.GetMenuById(in)
}

func (s *AdminServer) ListMenus(ctx context.Context, in *pb.ListMenusRequest) (*pb.ListMenusResponse, error) {
	l := logic.NewListMenusLogic(ctx, s.svcCtx)
	return l.ListMenus(in)
}

func (s *AdminServer) GetMenuTree(ctx context.Context, in *pb.GetMenuTreeRequest) (*pb.GetMenuTreeResponse, error) {
	l := logic.NewGetMenuTreeLogic(ctx, s.svcCtx)
	return l.GetMenuTree(in)
}

// -------- Permissions --------
func (s *AdminServer) CreatePermission(ctx context.Context, in *pb.CreatePermissionRequest) (*pb.CreatePermissionResponse, error) {
	l := logic.NewCreatePermissionLogic(ctx, s.svcCtx)
	return l.CreatePermission(in)
}

func (s *AdminServer) UpdatePermission(ctx context.Context, in *pb.UpdatePermissionRequest) (*pb.UpdatePermissionResponse, error) {
	l := logic.NewUpdatePermissionLogic(ctx, s.svcCtx)
	return l.UpdatePermission(in)
}

func (s *AdminServer) DeletePermission(ctx context.Context, in *pb.DeletePermissionRequest) (*pb.DeletePermissionResponse, error) {
	l := logic.NewDeletePermissionLogic(ctx, s.svcCtx)
	return l.DeletePermission(in)
}

func (s *AdminServer) GetPermissionById(ctx context.Context, in *pb.GetPermissionByIdRequest) (*pb.GetPermissionByIdResponse, error) {
	l := logic.NewGetPermissionByIdLogic(ctx, s.svcCtx)
	return l.GetPermissionById(in)
}

func (s *AdminServer) ListPermissions(ctx context.Context, in *pb.ListPermissionsRequest) (*pb.ListPermissionsResponse, error) {
	l := logic.NewListPermissionsLogic(ctx, s.svcCtx)
	return l.ListPermissions(in)
}

func (s *AdminServer) GetPermissionsByMenuId(ctx context.Context, in *pb.GetPermissionsByMenuIdRequest) (*pb.GetPermissionsByMenuIdResponse, error) {
	l := logic.NewGetPermissionsByMenuIdLogic(ctx, s.svcCtx)
	return l.GetPermissionsByMenuId(in)
}

// -------- Roles --------
func (s *AdminServer) CreateRole(ctx context.Context, in *pb.CreateRoleRequest) (*pb.CreateRoleResponse, error) {
	l := logic.NewCreateRoleLogic(ctx, s.svcCtx)
	return l.CreateRole(in)
}

func (s *AdminServer) UpdateRole(ctx context.Context, in *pb.UpdateRoleRequest) (*pb.UpdateRoleResponse, error) {
	l := logic.NewUpdateRoleLogic(ctx, s.svcCtx)
	return l.UpdateRole(in)
}

func (s *AdminServer) DeleteRole(ctx context.Context, in *pb.DeleteRoleRequest) (*pb.DeleteRoleResponse, error) {
	l := logic.NewDeleteRoleLogic(ctx, s.svcCtx)
	return l.DeleteRole(in)
}

func (s *AdminServer) GetRoleById(ctx context.Context, in *pb.GetRoleByIdRequest) (*pb.GetRoleByIdResponse, error) {
	l := logic.NewGetRoleByIdLogic(ctx, s.svcCtx)
	return l.GetRoleById(in)
}

func (s *AdminServer) ListRoles(ctx context.Context, in *pb.ListRolesRequest) (*pb.ListRolesResponse, error) {
	l := logic.NewListRolesLogic(ctx, s.svcCtx)
	return l.ListRoles(in)
}

func (s *AdminServer) AssignMenusToRole(ctx context.Context, in *pb.AssignMenusToRoleRequest) (*pb.AssignMenusToRoleResponse, error) {
	l := logic.NewAssignMenusToRoleLogic(ctx, s.svcCtx)
	return l.AssignMenusToRole(in)
}

func (s *AdminServer) AssignPermissionsToRole(ctx context.Context, in *pb.AssignPermissionsToRoleRequest) (*pb.AssignPermissionsToRoleResponse, error) {
	l := logic.NewAssignPermissionsToRoleLogic(ctx, s.svcCtx)
	return l.AssignPermissionsToRole(in)
}

func (s *AdminServer) AssignRolesToUser(ctx context.Context, in *pb.AssignRolesToUserRequest) (*pb.AssignRolesToUserResponse, error) {
	l := logic.NewAssignRolesToUserLogic(ctx, s.svcCtx)
	return l.AssignRolesToUser(in)
}

func (s *AdminServer) GetRoleMenus(ctx context.Context, in *pb.GetRoleMenusRequest) (*pb.GetRoleMenusResponse, error) {
	l := logic.NewGetRoleMenusLogic(ctx, s.svcCtx)
	return l.GetRoleMenus(in)
}

func (s *AdminServer) GetRolePermissions(ctx context.Context, in *pb.GetRolePermissionsRequest) (*pb.GetRolePermissionsResponse, error) {
	l := logic.NewGetRolePermissionsLogic(ctx, s.svcCtx)
	return l.GetRolePermissions(in)
}

func (s *AdminServer) GetUserRoles(ctx context.Context, in *pb.GetUserRolesRequest) (*pb.GetUserRolesResponse, error) {
	l := logic.NewGetUserRolesLogic(ctx, s.svcCtx)
	return l.GetUserRoles(in)
}

// ==================== System Settings ====================
func (s *AdminServer) GetSystemConfig(ctx context.Context, in *pb.GetSystemConfigRequest) (*pb.GetSystemConfigResponse, error) {
	l := logic.NewGetSystemConfigLogic(ctx, s.svcCtx)
	return l.GetSystemConfig(in)
}

func (s *AdminServer) UpdateSystemConfig(ctx context.Context, in *pb.UpdateSystemConfigRequest) (*pb.UpdateSystemConfigResponse, error) {
	l := logic.NewUpdateSystemConfigLogic(ctx, s.svcCtx)
	return l.UpdateSystemConfig(in)
}

func (s *AdminServer) GetClientConfig(ctx context.Context, in *pb.GetClientConfigRequest) (*pb.GetClientConfigResponse, error) {
	l := logic.NewGetClientConfigLogic(ctx, s.svcCtx)
	return l.GetClientConfig(in)
}

// ==================== Alert Configs ====================
func (s *AdminServer) ListAlertConfigs(ctx context.Context, in *pb.AdminListAlertConfigsRequest) (*pb.AdminListAlertConfigsResponse, error) {
	l := logic.NewListAlertConfigsLogic(ctx, s.svcCtx)
	return l.ListAlertConfigs(in)
}

func (s *AdminServer) CreateAlertConfig(ctx context.Context, in *pb.AdminCreateAlertConfigRequest) (*pb.AdminCreateAlertConfigResponse, error) {
	l := logic.NewCreateAlertConfigLogic(ctx, s.svcCtx)
	return l.CreateAlertConfig(in)
}

func (s *AdminServer) UpdateAlertConfig(ctx context.Context, in *pb.AdminUpdateAlertConfigRequest) (*pb.AdminUpdateAlertConfigResponse, error) {
	l := logic.NewUpdateAlertConfigLogic(ctx, s.svcCtx)
	return l.UpdateAlertConfig(in)
}

func (s *AdminServer) DeleteAlertConfig(ctx context.Context, in *pb.AdminDeleteAlertConfigRequest) (*pb.AdminDeleteAlertConfigResponse, error) {
	l := logic.NewDeleteAlertConfigLogic(ctx, s.svcCtx)
	return l.DeleteAlertConfig(in)
}

func (s *AdminServer) GetAlertConfig(ctx context.Context, in *pb.AdminGetAlertConfigRequest) (*pb.AdminGetAlertConfigResponse, error) {
	l := logic.NewGetAlertConfigLogic(ctx, s.svcCtx)
	return l.GetAlertConfig(in)
}

func (s *AdminServer) ToggleAlertConfig(ctx context.Context, in *pb.AdminToggleAlertConfigRequest) (*pb.AdminToggleAlertConfigResponse, error) {
	l := logic.NewToggleAlertConfigLogic(ctx, s.svcCtx)
	return l.ToggleAlertConfig(in)
}

func (s *AdminServer) GetAlertConfigWithStats(ctx context.Context, in *pb.AdminGetAlertConfigWithStatsRequest) (*pb.AdminGetAlertConfigWithStatsResponse, error) {
	l := logic.NewGetAlertConfigWithStatsLogic(ctx, s.svcCtx)
	return l.GetAlertConfigWithStats(in)
}

// ==================== Audit Logs ====================
func (s *AdminServer) GetAuditLogs(ctx context.Context, in *pb.GetAuditLogsRequest) (*pb.GetAuditLogsResponse, error) {
	l := logic.NewGetAuditLogsLogic(ctx, s.svcCtx)
	return l.GetAuditLogs(in)
}

// ==================== Swap Configuration (Simplified Architecture) ====================
func (s *AdminServer) CreateSwapApiKey(ctx context.Context, in *pb.AdminCreateSwapApiKeyRequest) (*pb.AdminCreateSwapApiKeyResponse, error) {
	l := logic.NewCreateSwapApiKeyLogic(ctx, s.svcCtx)
	return l.CreateSwapApiKey(in)
}

func (s *AdminServer) RevokeSwapApiKey(ctx context.Context, in *pb.AdminRevokeSwapApiKeyRequest) (*pb.AdminRevokeSwapApiKeyResponse, error) {
	l := logic.NewRevokeSwapApiKeyLogic(ctx, s.svcCtx)
	return l.RevokeSwapApiKey(in)
}

func (s *AdminServer) ListSwapApiKeys(ctx context.Context, in *pb.AdminListSwapApiKeysRequest) (*pb.AdminListSwapApiKeysResponse, error) {
	l := logic.NewListSwapApiKeysLogic(ctx, s.svcCtx)
	return l.ListSwapApiKeys(in)
}

// Provider管理
func (s *AdminServer) ListSwapProvidersForDropdown(ctx context.Context, in *pb.AdminListSwapProvidersForDropdownRequest) (*pb.AdminListSwapProvidersForDropdownResponse, error) {
	l := logic.NewListSwapProvidersForDropdownLogic(ctx, s.svcCtx)
	return l.ListSwapProvidersForDropdown(in)
}

func (s *AdminServer) ListSwapProviders(ctx context.Context, in *pb.AdminListSwapProvidersRequest) (*pb.AdminListSwapProvidersResponse, error) {
	l := logic.NewListSwapProvidersLogic(ctx, s.svcCtx)
	return l.ListSwapProviders(in)
}

func (s *AdminServer) GetSwapProviderDetail(ctx context.Context, in *pb.AdminGetSwapProviderDetailRequest) (*pb.AdminGetSwapProviderDetailResponse, error) {
	l := logic.NewGetSwapProviderDetailLogic(ctx, s.svcCtx)
	return l.GetSwapProviderDetail(in)
}

func (s *AdminServer) CreateSwapProvider(ctx context.Context, in *pb.AdminCreateSwapProviderRequest) (*pb.AdminCreateSwapProviderResponse, error) {
	l := logic.NewCreateSwapProviderLogic(ctx, s.svcCtx)
	return l.CreateSwapProvider(in)
}

func (s *AdminServer) UpdateSwapProvider(ctx context.Context, in *pb.AdminUpdateSwapProviderRequest) (*pb.AdminUpdateSwapProviderResponse, error) {
	l := logic.NewUpdateSwapProviderLogic(ctx, s.svcCtx)
	return l.UpdateSwapProvider(in)
}

func (s *AdminServer) DeleteSwapProvider(ctx context.Context, in *pb.AdminDeleteSwapProviderRequest) (*pb.AdminDeleteSwapProviderResponse, error) {
	l := logic.NewDeleteSwapProviderLogic(ctx, s.svcCtx)
	return l.DeleteSwapProvider(in)
}

func (s *AdminServer) EnableSwapProvider(ctx context.Context, in *pb.AdminEnableSwapProviderRequest) (*pb.AdminEnableSwapProviderResponse, error) {
	l := logic.NewEnableSwapProviderLogic(ctx, s.svcCtx)
	return l.EnableSwapProvider(in)
}

func (s *AdminServer) DisableSwapProvider(ctx context.Context, in *pb.AdminDisableSwapProviderRequest) (*pb.AdminDisableSwapProviderResponse, error) {
	l := logic.NewDisableSwapProviderLogic(ctx, s.svcCtx)
	return l.DisableSwapProvider(in)
}

// Config管理
func (s *AdminServer) ListSwapConfigs(ctx context.Context, in *pb.AdminListSwapConfigsRequest) (*pb.AdminListSwapConfigsResponse, error) {
	l := logic.NewListSwapConfigsLogic(ctx, s.svcCtx)
	return l.ListSwapConfigs(in)
}

func (s *AdminServer) GetSwapConfigDetail(ctx context.Context, in *pb.AdminGetSwapConfigDetailRequest) (*pb.AdminGetSwapConfigDetailResponse, error) {
	l := logic.NewGetSwapConfigDetailLogic(ctx, s.svcCtx)
	return l.GetSwapConfigDetail(in)
}

func (s *AdminServer) CreateSwapConfig(ctx context.Context, in *pb.AdminCreateSwapConfigRequest) (*pb.AdminCreateSwapConfigResponse, error) {
	l := logic.NewCreateSwapConfigLogic(ctx, s.svcCtx)
	return l.CreateSwapConfig(in)
}

func (s *AdminServer) UpdateSwapConfigDetail(ctx context.Context, in *pb.AdminUpdateSwapConfigDetailRequest) (*pb.AdminUpdateSwapConfigDetailResponse, error) {
	l := logic.NewUpdateSwapConfigDetailLogic(ctx, s.svcCtx)
	return l.UpdateSwapConfigDetail(in)
}

func (s *AdminServer) DeleteSwapConfig(ctx context.Context, in *pb.AdminDeleteSwapConfigRequest) (*pb.AdminDeleteSwapConfigResponse, error) {
	l := logic.NewDeleteSwapConfigLogic(ctx, s.svcCtx)
	return l.DeleteSwapConfig(in)
}

func (s *AdminServer) ListProjectSwapConfigs(ctx context.Context, in *pb.AdminListProjectSwapConfigsRequest) (*pb.AdminListProjectSwapConfigsResponse, error) {
	l := logic.NewListProjectSwapConfigsLogic(ctx, s.svcCtx)
	return l.ListProjectSwapConfigs(in)
}

func (s *AdminServer) EnableSwapConfigForProject(ctx context.Context, in *pb.AdminEnableSwapConfigForProjectRequest) (*pb.AdminEnableSwapConfigForProjectResponse, error) {
	l := logic.NewEnableSwapConfigForProjectLogic(ctx, s.svcCtx)
	return l.EnableSwapConfigForProject(in)
}

func (s *AdminServer) DisableSwapConfigForProject(ctx context.Context, in *pb.AdminDisableSwapConfigForProjectRequest) (*pb.AdminDisableSwapConfigForProjectResponse, error) {
	l := logic.NewDisableSwapConfigForProjectLogic(ctx, s.svcCtx)
	return l.DisableSwapConfigForProject(in)
}

func (s *AdminServer) ListSwapTransactions(ctx context.Context, in *pb.AdminListSwapTransactionsRequest) (*pb.AdminListSwapTransactionsResponse, error) {
	l := logic.NewListSwapTransactionsLogic(ctx, s.svcCtx)
	return l.ListSwapTransactions(in)
}

// ==================== Wallet Assets ====================
func (s *AdminServer) GetCurrencyOverview(ctx context.Context, in *pb.GetCurrencyOverviewRequest) (*pb.GetCurrencyOverviewResponse, error) {
	l := logic.NewGetCurrencyOverviewLogic(ctx, s.svcCtx)
	return l.GetCurrencyOverview(in)
}

func (s *AdminServer) CreateCurrency(ctx context.Context, in *pb.CreateCurrencyRequest) (*pb.CreateCurrencyResponse, error) {
	l := logic.NewCreateCurrencyLogic(ctx, s.svcCtx)
	return l.CreateCurrency(in)
}

func (s *AdminServer) UpdateCurrency(ctx context.Context, in *pb.UpdateCurrencyRequest) (*pb.UpdateCurrencyResponse, error) {
	l := logic.NewUpdateCurrencyLogic(ctx, s.svcCtx)
	return l.UpdateCurrency(in)
}

func (s *AdminServer) GetCurrency(ctx context.Context, in *pb.GetCurrencyRequest) (*pb.GetCurrencyResponse, error) {
	l := logic.NewGetCurrencyLogic(ctx, s.svcCtx)
	return l.GetCurrency(in)
}

func (s *AdminServer) ListCurrencies(ctx context.Context, in *pb.ListCurrenciesRequest) (*pb.ListCurrenciesResponse, error) {
	l := logic.NewListCurrenciesLogic(ctx, s.svcCtx)
	return l.ListCurrencies(in)
}

func (s *AdminServer) GetCurrencyConfig(ctx context.Context, in *pb.GetCurrencyConfigRequest) (*pb.GetCurrencyConfigResponse, error) {
	l := logic.NewGetCurrencyConfigLogic(ctx, s.svcCtx)
	return l.GetCurrencyConfig(in)
}

func (s *AdminServer) UpdateCurrencyConfig(ctx context.Context, in *pb.UpdateCurrencyConfigRequest) (*pb.UpdateCurrencyConfigResponse, error) {
	l := logic.NewUpdateCurrencyConfigLogic(ctx, s.svcCtx)
	return l.UpdateCurrencyConfig(in)
}

func (s *AdminServer) UpdateCurrencyStatus(ctx context.Context, in *pb.UpdateCurrencyStatusRequest) (*pb.UpdateCurrencyStatusResponse, error) {
	l := logic.NewUpdateCurrencyStatusLogic(ctx, s.svcCtx)
	return l.UpdateCurrencyStatus(in)
}

func (s *AdminServer) GetCurrencyGlobalWithdrawFee(ctx context.Context, in *pb.GetCurrencyGlobalWithdrawFeeRequest) (*pb.GetCurrencyGlobalWithdrawFeeResponse, error) {
	l := logic.NewGetCurrencyGlobalWithdrawFeeLogic(ctx, s.svcCtx)
	return l.GetCurrencyGlobalWithdrawFee(in)
}

func (s *AdminServer) UpdateCurrencyGlobalWithdrawFee(ctx context.Context, in *pb.UpdateCurrencyGlobalWithdrawFeeRequest) (*pb.UpdateCurrencyGlobalWithdrawFeeResponse, error) {
	l := logic.NewUpdateCurrencyGlobalWithdrawFeeLogic(ctx, s.svcCtx)
	return l.UpdateCurrencyGlobalWithdrawFee(in)
}

func (s *AdminServer) GetCurrencyGlobalWithdrawAudit(ctx context.Context, in *pb.GetCurrencyGlobalWithdrawAuditRequest) (*pb.GetCurrencyGlobalWithdrawAuditResponse, error) {
	l := logic.NewGetCurrencyGlobalWithdrawAuditLogic(ctx, s.svcCtx)
	return l.GetCurrencyGlobalWithdrawAudit(in)
}

func (s *AdminServer) UpdateCurrencyGlobalWithdrawAudit(ctx context.Context, in *pb.UpdateCurrencyGlobalWithdrawAuditRequest) (*pb.UpdateCurrencyGlobalWithdrawAuditResponse, error) {
	l := logic.NewUpdateCurrencyGlobalWithdrawAuditLogic(ctx, s.svcCtx)
	return l.UpdateCurrencyGlobalWithdrawAudit(in)
}

func (s *AdminServer) GetCurrencyGlobalTransferAudit(ctx context.Context, in *pb.GetCurrencyGlobalTransferAuditRequest) (*pb.GetCurrencyGlobalTransferAuditResponse, error) {
	l := logic.NewGetCurrencyGlobalTransferAuditLogic(ctx, s.svcCtx)
	return l.GetCurrencyGlobalTransferAudit(in)
}

func (s *AdminServer) UpdateCurrencyGlobalTransferAudit(ctx context.Context, in *pb.UpdateCurrencyGlobalTransferAuditRequest) (*pb.UpdateCurrencyGlobalTransferAuditResponse, error) {
	l := logic.NewUpdateCurrencyGlobalTransferAuditLogic(ctx, s.svcCtx)
	return l.UpdateCurrencyGlobalTransferAudit(in)
}

// -------- Chains --------
func (s *AdminServer) ListChains(ctx context.Context, in *pb.ListChainsRequest) (*pb.ListChainsResponse, error) {
	l := logic.NewListChainsLogic(ctx, s.svcCtx)
	return l.ListChains(in)
}

func (s *AdminServer) UpdateChainIcon(ctx context.Context, in *pb.UpdateChainIconRequest) (*pb.UpdateChainIconResponse, error) {
	l := logic.NewUpdateChainIconLogic(ctx, s.svcCtx)
	return l.UpdateChainIcon(in)
}

// -------- Accounting (Ledger) --------
func (s *AdminServer) AccountingListAccountTypes(ctx context.Context, in *pb.AccountingListAccountTypesRequest) (*pb.AccountingListAccountTypesResponse, error) {
	l := logic.NewAccountingListAccountTypesLogic(ctx, s.svcCtx)
	return l.AccountingListAccountTypes(in)
}

func (s *AdminServer) AccountingCreateAccountType(ctx context.Context, in *pb.AccountingCreateAccountTypeRequest) (*pb.AccountingCreateAccountTypeResponse, error) {
	l := logic.NewAccountingCreateAccountTypeLogic(ctx, s.svcCtx)
	return l.AccountingCreateAccountType(in)
}

func (s *AdminServer) AccountingUpdateAccountType(ctx context.Context, in *pb.AccountingUpdateAccountTypeRequest) (*pb.AccountingUpdateAccountTypeResponse, error) {
	l := logic.NewAccountingUpdateAccountTypeLogic(ctx, s.svcCtx)
	return l.AccountingUpdateAccountType(in)
}

func (s *AdminServer) AccountingDeleteAccountType(ctx context.Context, in *pb.AccountingDeleteAccountTypeRequest) (*pb.AccountingDeleteAccountTypeResponse, error) {
	l := logic.NewAccountingDeleteAccountTypeLogic(ctx, s.svcCtx)
	return l.AccountingDeleteAccountType(in)
}

func (s *AdminServer) AccountingSetAccountTypeAssets(ctx context.Context, in *pb.AccountingSetAccountTypeAssetsRequest) (*pb.AccountingSetAccountTypeAssetsResponse, error) {
	l := logic.NewAccountingSetAccountTypeAssetsLogic(ctx, s.svcCtx)
	return l.AccountingSetAccountTypeAssets(in)
}

func (s *AdminServer) AccountingEnsureUserSetup(ctx context.Context, in *pb.AccountingEnsureUserSetupRequest) (*pb.AccountingEnsureUserSetupResponse, error) {
	l := logic.NewAccountingEnsureUserSetupLogic(ctx, s.svcCtx)
	return l.AccountingEnsureUserSetup(in)
}

func (s *AdminServer) AccountingGetUserBalances(ctx context.Context, in *pb.AccountingGetUserBalancesRequest) (*pb.AccountingGetUserBalancesResponse, error) {
	l := logic.NewAccountingGetUserBalancesLogic(ctx, s.svcCtx)
	return l.AccountingGetUserBalances(in)
}

func (s *AdminServer) AccountingEnsureSystemAccounts(ctx context.Context, in *pb.AccountingEnsureSystemAccountsRequest) (*pb.AccountingEnsureSystemAccountsResponse, error) {
	l := logic.NewAccountingEnsureSystemAccountsLogic(ctx, s.svcCtx)
	return l.AccountingEnsureSystemAccounts(in)
}

func (s *AdminServer) AccountingListLedgerTx(ctx context.Context, in *pb.AccountingListLedgerTxRequest) (*pb.AccountingListLedgerTxResponse, error) {
	l := logic.NewAccountingListLedgerTxLogic(ctx, s.svcCtx)
	return l.AccountingListLedgerTx(in)
}

func (s *AdminServer) AccountingGetLedgerTxDetail(ctx context.Context, in *pb.AccountingGetLedgerTxDetailRequest) (*pb.AccountingGetLedgerTxDetailResponse, error) {
	l := logic.NewAccountingGetLedgerTxDetailLogic(ctx, s.svcCtx)
	return l.AccountingGetLedgerTxDetail(in)
}

func (s *AdminServer) AccountingListUserTransactionRecords(ctx context.Context, in *pb.AccountingListUserTransactionRecordsRequest) (*pb.AccountingListUserTransactionRecordsResponse, error) {
	l := logic.NewAccountingListUserTransactionRecordsLogic(ctx, s.svcCtx)
	return l.AccountingListUserTransactionRecords(in)
}

func (s *AdminServer) AccountingGetUserTransactionRecordDetail(ctx context.Context, in *pb.AccountingGetUserTransactionRecordDetailRequest) (*pb.AccountingGetUserTransactionRecordDetailResponse, error) {
	l := logic.NewAccountingGetUserTransactionRecordDetailLogic(ctx, s.svcCtx)
	return l.AccountingGetUserTransactionRecordDetail(in)
}

// -------- Deposit Addresses --------
func (s *AdminServer) ListDepositAddresses(ctx context.Context, in *pb.ListDepositAddressesRequest) (*pb.ListDepositAddressesResponse, error) {
	l := logic.NewListDepositAddressesLogic(ctx, s.svcCtx)
	return l.ListDepositAddresses(in)
}

func (s *AdminServer) ListDepositAddressesWithBalance(ctx context.Context, in *pb.ListDepositAddressesWithBalanceRequest) (*pb.ListDepositAddressesWithBalanceResponse, error) {
	l := logic.NewListDepositAddressesWithBalanceLogic(ctx, s.svcCtx)
	return l.ListDepositAddressesWithBalance(in)
}

func (s *AdminServer) GetDepositAddress(ctx context.Context, in *pb.GetDepositAddressRequest) (*pb.GetDepositAddressResponse, error) {
	l := logic.NewGetDepositAddressLogic(ctx, s.svcCtx)
	return l.GetDepositAddress(in)
}

func (s *AdminServer) CreateDepositAddress(ctx context.Context, in *pb.CreateDepositAddressRequest) (*pb.CreateDepositAddressResponse, error) {
	l := logic.NewCreateDepositAddressLogic(ctx, s.svcCtx)
	return l.CreateDepositAddress(in)
}

func (s *AdminServer) UpdateDepositAddress(ctx context.Context, in *pb.UpdateDepositAddressRequest) (*pb.UpdateDepositAddressResponse, error) {
	l := logic.NewUpdateDepositAddressLogic(ctx, s.svcCtx)
	return l.UpdateDepositAddress(in)
}

func (s *AdminServer) DeleteDepositAddress(ctx context.Context, in *pb.DeleteDepositAddressRequest) (*pb.DeleteDepositAddressResponse, error) {
	l := logic.NewDeleteDepositAddressLogic(ctx, s.svcCtx)
	return l.DeleteDepositAddress(in)
}

func (s *AdminServer) InitializeUserWallet(ctx context.Context, in *pb.InitializeUserWalletRequest) (*pb.InitializeUserWalletResponse, error) {
	l := logic.NewInitializeUserWalletLogic(ctx, s.svcCtx)
	return l.InitializeUserWallet(in)
}

// -------- Deposit Address Balances --------
func (s *AdminServer) ListDepositAddressBalances(ctx context.Context, in *pb.ListDepositAddressBalancesRequest) (*pb.ListDepositAddressBalancesResponse, error) {
	l := logic.NewListDepositAddressBalancesLogic(ctx, s.svcCtx)
	return l.ListDepositAddressBalances(in)
}

// 获取地址余额
func (s *AdminServer) GetDepositAddressBalance(ctx context.Context, in *pb.GetDepositAddressBalanceRequest) (*pb.GetDepositAddressBalanceResponse, error) {
	l := logic.NewGetDepositAddressBalanceLogic(ctx, s.svcCtx)
	return l.GetDepositAddressBalance(in)
}

// 获取地址余额统计
func (s *AdminServer) GetDepositAddressBalanceStats(ctx context.Context, in *pb.GetDepositAddressBalanceStatsRequest) (*pb.GetDepositAddressBalanceStatsResponse, error) {
	l := logic.NewGetDepositAddressBalanceStatsLogic(ctx, s.svcCtx)
	return l.GetDepositAddressBalanceStats(in)
}

// 按币种统计待归集金额（币种分布）
func (s *AdminServer) GetDepositAddressBalanceByAsset(ctx context.Context, in *pb.GetDepositAddressBalanceByAssetRequest) (*pb.GetDepositAddressBalanceByAssetResponse, error) {
	l := logic.NewGetDepositAddressBalanceByAssetLogic(ctx, s.svcCtx)
	return l.GetDepositAddressBalanceByAsset(in)
}

// 更新地址余额
func (s *AdminServer) UpdateDepositAddressBalance(ctx context.Context, in *pb.UpdateDepositAddressBalanceRequest) (*pb.UpdateDepositAddressBalanceResponse, error) {
	l := logic.NewUpdateDepositAddressBalanceLogic(ctx, s.svcCtx)
	return l.UpdateDepositAddressBalance(in)
}

// -------- Consolidation (New module; independent from Sweep Tasks) --------
func (s *AdminServer) ListConsolidationTasks(ctx context.Context, in *pb.AdminListConsolidationTasksRequest) (*pb.AdminListConsolidationTasksResponse, error) {
	l := logic.NewListConsolidationTasksLogic(ctx, s.svcCtx)
	return l.ListConsolidationTasks(in)
}

func (s *AdminServer) GetConsolidationTask(ctx context.Context, in *pb.AdminGetConsolidationTaskRequest) (*pb.AdminGetConsolidationTaskResponse, error) {
	l := logic.NewGetConsolidationTaskLogic(ctx, s.svcCtx)
	return l.GetConsolidationTask(in)
}

func (s *AdminServer) RetryConsolidationTask(ctx context.Context, in *pb.AdminRetryConsolidationTaskRequest) (*pb.AdminRetryConsolidationTaskResponse, error) {
	l := logic.NewRetryConsolidationTaskLogic(ctx, s.svcCtx)
	return l.RetryConsolidationTask(in)
}

func (s *AdminServer) CancelConsolidationTask(ctx context.Context, in *pb.AdminCancelConsolidationTaskRequest) (*pb.AdminCancelConsolidationTaskResponse, error) {
	l := logic.NewCancelConsolidationTaskLogic(ctx, s.svcCtx)
	return l.CancelConsolidationTask(in)
}

func (s *AdminServer) TriggerConsolidation(ctx context.Context, in *pb.AdminTriggerConsolidationRequest) (*pb.AdminTriggerConsolidationResponse, error) {
	l := logic.NewTriggerConsolidationLogic(ctx, s.svcCtx)
	return l.TriggerConsolidation(in)
}

func (s *AdminServer) GetConsolidationStats(ctx context.Context, in *pb.AdminGetConsolidationStatsRequest) (*pb.AdminGetConsolidationStatsResponse, error) {
	l := logic.NewGetConsolidationStatsLogic(ctx, s.svcCtx)
	return l.GetConsolidationStats(in)
}

func (s *AdminServer) ListConsolidationLogs(ctx context.Context, in *pb.AdminListConsolidationLogsRequest) (*pb.AdminListConsolidationLogsResponse, error) {
	l := logic.NewListConsolidationLogsLogic(ctx, s.svcCtx)
	return l.ListConsolidationLogs(in)
}

func (s *AdminServer) ListConsolidationTopupRecords(ctx context.Context, in *pb.AdminListConsolidationTopupRecordsRequest) (*pb.AdminListConsolidationTopupRecordsResponse, error) {
	l := logic.NewListConsolidationTopupRecordsLogic(ctx, s.svcCtx)
	return l.ListConsolidationTopupRecords(in)
}

func (s *AdminServer) ListEnergyRentalRecords(ctx context.Context, in *pb.AdminListEnergyRentalRecordsRequest) (*pb.AdminListEnergyRentalRecordsResponse, error) {
	l := logic.NewListEnergyRentalRecordsLogic(ctx, s.svcCtx)
	return l.ListEnergyRentalRecords(in)
}

func (s *AdminServer) GetEnergyRentalRecord(ctx context.Context, in *pb.AdminGetEnergyRentalRecordRequest) (*pb.AdminGetEnergyRentalRecordResponse, error) {
	l := logic.NewGetEnergyRentalRecordLogic(ctx, s.svcCtx)
	return l.GetEnergyRentalRecord(in)
}

// -------- Deposits --------
func (s *AdminServer) ListDeposits(ctx context.Context, in *pb.ListDepositsRequest) (*pb.ListDepositsResponse, error) {
	l := logic.NewListDepositsLogic(ctx, s.svcCtx)
	return l.ListDeposits(in)
}

func (s *AdminServer) GetDeposit(ctx context.Context, in *pb.GetDepositRequest) (*pb.GetDepositResponse, error) {
	l := logic.NewGetDepositLogic(ctx, s.svcCtx)
	return l.GetDeposit(in)
}

func (s *AdminServer) CreateDeposit(ctx context.Context, in *pb.CreateDepositRequest) (*pb.CreateDepositResponse, error) {
	l := logic.NewCreateDepositLogic(ctx, s.svcCtx)
	return l.CreateDeposit(in)
}

func (s *AdminServer) UpdateDeposit(ctx context.Context, in *pb.UpdateDepositRequest) (*pb.UpdateDepositResponse, error) {
	l := logic.NewUpdateDepositLogic(ctx, s.svcCtx)
	return l.UpdateDeposit(in)
}

func (s *AdminServer) CancelDeposit(ctx context.Context, in *pb.CancelDepositRequest) (*pb.CancelDepositResponse, error) {
	l := logic.NewCancelDepositLogic(ctx, s.svcCtx)
	return l.CancelDeposit(in)
}

// -------- Withdrawals --------
func (s *AdminServer) CreateCurrencyWithdrawal(ctx context.Context, in *pb.CreateCurrencyWithdrawalRequest) (*pb.CreateCurrencyWithdrawalResponse, error) {
	l := logic.NewCreateCurrencyWithdrawalLogic(ctx, s.svcCtx)
	return l.CreateCurrencyWithdrawal(in)
}

func (s *AdminServer) GetCurrencyWithdrawal(ctx context.Context, in *pb.GetCurrencyWithdrawalRequest) (*pb.GetCurrencyWithdrawalResponse, error) {
	l := logic.NewGetCurrencyWithdrawalLogic(ctx, s.svcCtx)
	return l.GetCurrencyWithdrawal(in)
}

func (s *AdminServer) ListCurrencyWithdrawals(ctx context.Context, in *pb.ListCurrencyWithdrawalsRequest) (*pb.ListCurrencyWithdrawalsResponse, error) {
	l := logic.NewListCurrencyWithdrawalsLogic(ctx, s.svcCtx)
	return l.ListCurrencyWithdrawals(in)
}

func (s *AdminServer) ApproveCurrencyWithdrawal(ctx context.Context, in *pb.ApproveCurrencyWithdrawalRequest) (*pb.ApproveCurrencyWithdrawalResponse, error) {
	l := logic.NewApproveCurrencyWithdrawalLogic(ctx, s.svcCtx)
	return l.ApproveCurrencyWithdrawal(in)
}

func (s *AdminServer) RejectCurrencyWithdrawal(ctx context.Context, in *pb.RejectCurrencyWithdrawalRequest) (*pb.RejectCurrencyWithdrawalResponse, error) {
	l := logic.NewRejectCurrencyWithdrawalLogic(ctx, s.svcCtx)
	return l.RejectCurrencyWithdrawal(in)
}

func (s *AdminServer) CancelCurrencyWithdrawal(ctx context.Context, in *pb.CancelCurrencyWithdrawalRequest) (*pb.CancelCurrencyWithdrawalResponse, error) {
	l := logic.NewCancelCurrencyWithdrawalLogic(ctx, s.svcCtx)
	return l.CancelCurrencyWithdrawal(in)
}

func (s *AdminServer) UpdateCurrencyWithdrawal(ctx context.Context, in *pb.UpdateCurrencyWithdrawalRequest) (*pb.UpdateCurrencyWithdrawalResponse, error) {
	l := logic.NewUpdateCurrencyWithdrawalLogic(ctx, s.svcCtx)
	return l.UpdateCurrencyWithdrawal(in)
}

func (s *AdminServer) ListCurrencyWithdrawalEvents(ctx context.Context, in *pb.ListCurrencyWithdrawalEventsRequest) (*pb.ListCurrencyWithdrawalEventsResponse, error) {
	l := logic.NewListCurrencyWithdrawalEventsLogic(ctx, s.svcCtx)
	return l.ListCurrencyWithdrawalEvents(in)
}

// -------- Internal Transfers (User-to-User) --------
func (s *AdminServer) ListInternalTransfers(ctx context.Context, in *pb.ListInternalTransfersRequest) (*pb.ListInternalTransfersResponse, error) {
	l := logic.NewListInternalTransfersLogic(ctx, s.svcCtx)
	return l.ListInternalTransfers(in)
}

func (s *AdminServer) GetInternalTransfer(ctx context.Context, in *pb.GetInternalTransferRequest) (*pb.GetInternalTransferResponse, error) {
	l := logic.NewGetInternalTransferLogic(ctx, s.svcCtx)
	return l.GetInternalTransfer(in)
}

func (s *AdminServer) ApproveInternalTransfer(ctx context.Context, in *pb.ApproveInternalTransferRequest) (*pb.ApproveInternalTransferResponse, error) {
	l := logic.NewApproveInternalTransferLogic(ctx, s.svcCtx)
	return l.ApproveInternalTransfer(in)
}

func (s *AdminServer) RejectInternalTransfer(ctx context.Context, in *pb.RejectInternalTransferRequest) (*pb.RejectInternalTransferResponse, error) {
	l := logic.NewRejectInternalTransferLogic(ctx, s.svcCtx)
	return l.RejectInternalTransfer(in)
}

func (s *AdminServer) CancelInternalTransfer(ctx context.Context, in *pb.CancelInternalTransferRequest) (*pb.CancelInternalTransferResponse, error) {
	l := logic.NewCancelInternalTransferLogic(ctx, s.svcCtx)
	return l.CancelInternalTransfer(in)
}

// ==================== Transfer (Batch Payout) ====================
func (s *AdminServer) ListTransferBatches(ctx context.Context, in *pb.ListTransferBatchesRequest) (*pb.ListTransferBatchesResponse, error) {
	l := logic.NewListTransferBatchesLogic(ctx, s.svcCtx)
	return l.ListTransferBatches(in)
}

func (s *AdminServer) ImportTransferBatch(ctx context.Context, in *pb.ImportTransferBatchRequest) (*pb.ImportTransferBatchResponse, error) {
	l := logic.NewImportTransferBatchLogic(ctx, s.svcCtx)
	return l.ImportTransferBatch(in)
}

func (s *AdminServer) GetTransferBatch(ctx context.Context, in *pb.GetTransferBatchRequest) (*pb.GetTransferBatchResponse, error) {
	l := logic.NewGetTransferBatchLogic(ctx, s.svcCtx)
	return l.GetTransferBatch(in)
}

func (s *AdminServer) SubmitTransferBatch(ctx context.Context, in *pb.SubmitTransferBatchRequest) (*pb.SubmitTransferBatchResponse, error) {
	l := logic.NewSubmitTransferBatchLogic(ctx, s.svcCtx)
	return l.SubmitTransferBatch(in)
}

func (s *AdminServer) ApproveTransferBatch(ctx context.Context, in *pb.ApproveTransferBatchRequest) (*pb.ApproveTransferBatchResponse, error) {
	l := logic.NewApproveTransferBatchLogic(ctx, s.svcCtx)
	return l.ApproveTransferBatch(in)
}

func (s *AdminServer) CancelTransferBatch(ctx context.Context, in *pb.CancelTransferBatchRequest) (*pb.CancelTransferBatchResponse, error) {
	l := logic.NewCancelTransferBatchLogic(ctx, s.svcCtx)
	return l.CancelTransferBatch(in)
}

func (s *AdminServer) ExecuteTransferBatch(ctx context.Context, in *pb.ExecuteTransferBatchRequest) (*pb.ExecuteTransferBatchResponse, error) {
	l := logic.NewExecuteTransferBatchLogic(ctx, s.svcCtx)
	return l.ExecuteTransferBatch(in)
}

func (s *AdminServer) RetryTransferBatch(ctx context.Context, in *pb.RetryTransferBatchRequest) (*pb.RetryTransferBatchResponse, error) {
	l := logic.NewRetryTransferBatchLogic(ctx, s.svcCtx)
	return l.RetryTransferBatch(in)
}

// ==================== Web3 Users ====================
func (s *AdminServer) ListWeb3Users(ctx context.Context, in *pb.ListWeb3UsersRequest) (*pb.ListWeb3UsersResponse, error) {
	l := logic.NewListWeb3UsersLogic(ctx, s.svcCtx)
	return l.ListWeb3Users(in)
}

func (s *AdminServer) GetWeb3User(ctx context.Context, in *pb.GetWeb3UserRequest) (*pb.GetWeb3UserResponse, error) {
	l := logic.NewGetWeb3UserLogic(ctx, s.svcCtx)
	return l.GetWeb3User(in)
}

func (s *AdminServer) GetWeb3UsersPageList(ctx context.Context, in *pb.GetWeb3UsersPageListRequest) (*pb.GetWeb3UsersPageListResponse, error) {
	l := logic.NewGetWeb3UsersPageListLogic(ctx, s.svcCtx)
	return l.GetWeb3UsersPageList(in)
}

func (s *AdminServer) GetWeb3UsersSummary(ctx context.Context, in *pb.GetWeb3UsersSummaryRequest) (*pb.GetWeb3UsersSummaryResponse, error) {
	l := logic.NewGetWeb3UsersSummaryLogic(ctx, s.svcCtx)
	return l.GetWeb3UsersSummary(in)
}

func (s *AdminServer) ListWeb3UserTransactions(ctx context.Context, in *pb.ListWeb3UserTransactionsRequest) (*pb.ListWeb3UserTransactionsResponse, error) {
	l := logic.NewListWeb3UserTransactionsLogic(ctx, s.svcCtx)
	return l.ListWeb3UserTransactions(in)
}

func (s *AdminServer) BlacklistWeb3Address(ctx context.Context, in *pb.BlacklistWeb3AddressRequest) (*pb.BlacklistWeb3AddressResponse, error) {
	l := logic.NewBlacklistWeb3AddressLogic(ctx, s.svcCtx)
	return l.BlacklistWeb3Address(in)
}

func (s *AdminServer) UnblacklistWeb3Address(ctx context.Context, in *pb.UnblacklistWeb3AddressRequest) (*pb.UnblacklistWeb3AddressResponse, error) {
	l := logic.NewUnblacklistWeb3AddressLogic(ctx, s.svcCtx)
	return l.UnblacklistWeb3Address(in)
}

func (s *AdminServer) BatchWeb3AddressBlacklist(ctx context.Context, in *pb.BatchWeb3AddressBlacklistRequest) (*pb.BatchWeb3AddressBlacklistResponse, error) {
	l := logic.NewBatchWeb3AddressBlacklistLogic(ctx, s.svcCtx)
	return l.BatchWeb3AddressBlacklist(in)
}

func (s *AdminServer) GetWeb3UserStatistics(ctx context.Context, in *pb.GetWeb3UserStatisticsRequest) (*pb.GetWeb3UserStatisticsResponse, error) {
	l := logic.NewGetWeb3UserStatisticsLogic(ctx, s.svcCtx)
	return l.GetWeb3UserStatistics(in)
}

func (s *AdminServer) ExportWeb3Users(ctx context.Context, in *pb.ExportWeb3UsersRequest) (*pb.ExportWeb3UsersResponse, error) {
	l := logic.NewExportWeb3UsersLogic(ctx, s.svcCtx)
	return l.ExportWeb3Users(in)
}

func (s *AdminServer) ListWeb3UserAddresses(ctx context.Context, in *pb.ListWeb3UserAddressesRequest) (*pb.ListWeb3UserAddressesResponse, error) {
	l := logic.NewListWeb3UserAddressesLogic(ctx, s.svcCtx)
	return l.ListWeb3UserAddresses(in)
}

// ==================== Blacklist (Sensitive Addresses) ====================
func (s *AdminServer) ListBlacklistAddresses(ctx context.Context, in *pb.ListBlacklistAddressesRequest) (*pb.ListBlacklistAddressesResponse, error) {
	l := logic.NewListBlacklistAddressesLogic(ctx, s.svcCtx)
	return l.ListBlacklistAddresses(in)
}

func (s *AdminServer) CreateBlacklistAddress(ctx context.Context, in *pb.CreateBlacklistAddressRequest) (*pb.CreateBlacklistAddressResponse, error) {
	l := logic.NewCreateBlacklistAddressLogic(ctx, s.svcCtx)
	return l.CreateBlacklistAddress(in)
}

func (s *AdminServer) BatchCreateBlacklistAddresses(ctx context.Context, in *pb.BatchCreateBlacklistAddressesRequest) (*pb.BatchCreateBlacklistAddressesResponse, error) {
	l := logic.NewBatchCreateBlacklistAddressesLogic(ctx, s.svcCtx)
	return l.BatchCreateBlacklistAddresses(in)
}

func (s *AdminServer) UpdateBlacklistAddressMonitorStatus(ctx context.Context, in *pb.UpdateBlacklistAddressMonitorStatusRequest) (*pb.UpdateBlacklistAddressMonitorStatusResponse, error) {
	l := logic.NewUpdateBlacklistAddressMonitorStatusLogic(ctx, s.svcCtx)
	return l.UpdateBlacklistAddressMonitorStatus(in)
}

func (s *AdminServer) DeleteBlacklistAddress(ctx context.Context, in *pb.DeleteBlacklistAddressRequest) (*pb.DeleteBlacklistAddressResponse, error) {
	l := logic.NewDeleteBlacklistAddressLogic(ctx, s.svcCtx)
	return l.DeleteBlacklistAddress(in)
}

func (s *AdminServer) ExportBlacklistAddresses(ctx context.Context, in *pb.ExportBlacklistAddressesRequest) (*pb.ExportBlacklistAddressesResponse, error) {
	l := logic.NewExportBlacklistAddressesLogic(ctx, s.svcCtx)
	return l.ExportBlacklistAddresses(in)
}

// ==================== Vault Funds Management ====================
func (s *AdminServer) GetVaultOverview(ctx context.Context, in *pb.GetVaultOverviewRequest) (*pb.GetVaultOverviewResponse, error) {
	l := logic.NewGetVaultOverviewLogic(ctx, s.svcCtx)
	return l.GetVaultOverview(in)
}

// 获取某个链的详细信息
func (s *AdminServer) GetVaultDetail(ctx context.Context, in *pb.GetVaultDetailRequest) (*pb.GetVaultDetailResponse, error) {
	l := logic.NewGetVaultDetailLogic(ctx, s.svcCtx)
	return l.GetVaultDetail(in)
}

// 创建资金调整
func (s *AdminServer) CreateVaultAdjustment(ctx context.Context, in *pb.CreateVaultAdjustmentRequest) (*pb.CreateVaultAdjustmentResponse, error) {
	l := logic.NewCreateVaultAdjustmentLogic(ctx, s.svcCtx)
	return l.CreateVaultAdjustment(in)
}

func (s *AdminServer) ListVaultAdjustments(ctx context.Context, in *pb.ListVaultAdjustmentsRequest) (*pb.ListVaultAdjustmentsResponse, error) {
	l := logic.NewListVaultAdjustmentsLogic(ctx, s.svcCtx)
	return l.ListVaultAdjustments(in)
}

// 审批资金调整
func (s *AdminServer) ApproveVaultAdjustment(ctx context.Context, in *pb.ApproveVaultAdjustmentRequest) (*pb.ApproveVaultAdjustmentResponse, error) {
	l := logic.NewApproveVaultAdjustmentLogic(ctx, s.svcCtx)
	return l.ApproveVaultAdjustment(in)
}

// 更新预警阈值
func (s *AdminServer) UpdateVaultThresholds(ctx context.Context, in *pb.UpdateVaultThresholdsRequest) (*pb.UpdateVaultThresholdsResponse, error) {
	l := logic.NewUpdateVaultThresholdsLogic(ctx, s.svcCtx)
	return l.UpdateVaultThresholds(in)
}

// 刷新余额
func (s *AdminServer) SyncVault(ctx context.Context, in *pb.SyncVaultRequest) (*pb.SyncVaultResponse, error) {
	l := logic.NewSyncVaultLogic(ctx, s.svcCtx)
	return l.SyncVault(in)
}

// ==================== Vault Address Management ====================
func (s *AdminServer) AddVaultAddress(ctx context.Context, in *pb.AddVaultAddressRequest) (*pb.AddVaultAddressResponse, error) {
	l := logic.NewAddVaultAddressLogic(ctx, s.svcCtx)
	return l.AddVaultAddress(in)
}

// 查看地址列表
func (s *AdminServer) ListVaultAddresses(ctx context.Context, in *pb.ListVaultAddressesRequest) (*pb.ListVaultAddressesResponse, error) {
	l := logic.NewListVaultAddressesLogic(ctx, s.svcCtx)
	return l.ListVaultAddresses(in)
}

// 修改地址状态
func (s *AdminServer) UpdateVaultAddressStatus(ctx context.Context, in *pb.UpdateVaultAddressStatusRequest) (*pb.UpdateVaultAddressStatusResponse, error) {
	l := logic.NewUpdateVaultAddressStatusLogic(ctx, s.svcCtx)
	return l.UpdateVaultAddressStatus(in)
}

// 删除地址
func (s *AdminServer) DeleteVaultAddress(ctx context.Context, in *pb.DeleteVaultAddressRequest) (*pb.DeleteVaultAddressResponse, error) {
	l := logic.NewDeleteVaultAddressLogic(ctx, s.svcCtx)
	return l.DeleteVaultAddress(in)
}

// 获取地址余额
func (s *AdminServer) GetVaultAddressBalances(ctx context.Context, in *pb.GetVaultAddressBalancesRequest) (*pb.GetVaultAddressBalancesResponse, error) {
	l := logic.NewGetVaultAddressBalancesLogic(ctx, s.svcCtx)
	return l.GetVaultAddressBalances(in)
}

// 检查热钱包余额是否足够（用于提现前验证）
func (s *AdminServer) CheckHotWalletBalance(ctx context.Context, in *pb.CheckHotWalletBalanceRequest) (*pb.CheckHotWalletBalanceResponse, error) {
	l := logic.NewCheckHotWalletBalanceLogic(ctx, s.svcCtx)
	return l.CheckHotWalletBalance(in)
}

// ==================== Dashboard Statistics ====================
func (s *AdminServer) GetDashboardOverview(ctx context.Context, in *pb.GetDashboardOverviewRequest) (*pb.GetDashboardOverviewResponse, error) {
	l := logic.NewGetDashboardOverviewLogic(ctx, s.svcCtx)
	return l.GetDashboardOverview(in)
}

// 获取仪表板趋势图表数据
func (s *AdminServer) GetDashboardTrends(ctx context.Context, in *pb.GetDashboardTrendsRequest) (*pb.GetDashboardTrendsResponse, error) {
	l := logic.NewGetDashboardTrendsLogic(ctx, s.svcCtx)
	return l.GetDashboardTrends(in)
}

// 获取最近操作动态
func (s *AdminServer) GetDashboardActivities(ctx context.Context, in *pb.GetDashboardActivitiesRequest) (*pb.GetDashboardActivitiesResponse, error) {
	l := logic.NewGetDashboardActivitiesLogic(ctx, s.svcCtx)
	return l.GetDashboardActivities(in)
}
