// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: notification.proto

package server

import (
	"context"

	"internalwallet/proto/pb"
	"internalwallet/services/notification/rpc/internal/logic"
	"internalwallet/services/notification/rpc/internal/svc"
)

type NotificationServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedNotificationServer
}

func NewNotificationServer(svcCtx *svc.ServiceContext) *NotificationServer {
	return &NotificationServer{
		svcCtx: svcCtx,
	}
}

// ==================== 设备管理 ====================
func (s *NotificationServer) RegisterDevice(ctx context.Context, in *pb.RegisterDeviceRequest) (*pb.RegisterDeviceResponse, error) {
	l := logic.NewRegisterDeviceLogic(ctx, s.svcCtx)
	return l.RegisterDevice(in)
}

// 注销设备（用户登出时调用）
func (s *NotificationServer) UnregisterDevice(ctx context.Context, in *pb.UnregisterDeviceRequest) (*pb.UnregisterDeviceResponse, error) {
	l := logic.NewUnregisterDeviceLogic(ctx, s.svcCtx)
	return l.UnregisterDevice(in)
}

// 获取用户设备列表
func (s *NotificationServer) GetUserDevices(ctx context.Context, in *pb.GetUserDevicesRequest) (*pb.GetUserDevicesResponse, error) {
	l := logic.NewGetUserDevicesLogic(ctx, s.svcCtx)
	return l.GetUserDevices(in)
}

// ==================== 推送发送 ====================
func (s *NotificationServer) SendNotification(ctx context.Context, in *pb.SendNotificationRequest) (*pb.SendNotificationResponse, error) {
	l := logic.NewSendNotificationLogic(ctx, s.svcCtx)
	return l.SendNotification(in)
}

// 发送批量推送
func (s *NotificationServer) SendBatchNotification(ctx context.Context, in *pb.SendBatchNotificationRequest) (*pb.SendBatchNotificationResponse, error) {
	l := logic.NewSendBatchNotificationLogic(ctx, s.svcCtx)
	return l.SendBatchNotification(in)
}

// 发送广播推送（所有用户）
func (s *NotificationServer) SendBroadcast(ctx context.Context, in *pb.SendBroadcastRequest) (*pb.SendBroadcastResponse, error) {
	l := logic.NewSendBroadcastLogic(ctx, s.svcCtx)
	return l.SendBroadcast(in)
}

// 通过别名发送推送（使用用户ID或设备ID作为别名）
func (s *NotificationServer) SendNotificationByAlias(ctx context.Context, in *pb.SendNotificationByAliasRequest) (*pb.SendNotificationByAliasResponse, error) {
	l := logic.NewSendNotificationByAliasLogic(ctx, s.svcCtx)
	return l.SendNotificationByAlias(in)
}

// 通过设备ID发送推送（Web3用户专用）
func (s *NotificationServer) SendNotificationByDeviceToken(ctx context.Context, in *pb.SendNotificationByDeviceTokenRequest) (*pb.SendNotificationByDeviceTokenResponse, error) {
	l := logic.NewSendNotificationByDeviceTokenLogic(ctx, s.svcCtx)
	return l.SendNotificationByDeviceToken(in)
}

// ==================== 推送历史 ====================
func (s *NotificationServer) GetNotificationHistory(ctx context.Context, in *pb.GetNotificationHistoryRequest) (*pb.GetNotificationHistoryResponse, error) {
	l := logic.NewGetNotificationHistoryLogic(ctx, s.svcCtx)
	return l.GetNotificationHistory(in)
}

// 获取推送详情
func (s *NotificationServer) GetNotificationDetail(ctx context.Context, in *pb.GetNotificationDetailRequest) (*pb.GetNotificationDetailResponse, error) {
	l := logic.NewGetNotificationDetailLogic(ctx, s.svcCtx)
	return l.GetNotificationDetail(in)
}

// 标记推送为已读
func (s *NotificationServer) MarkNotificationRead(ctx context.Context, in *pb.MarkNotificationReadRequest) (*pb.MarkNotificationReadResponse, error) {
	l := logic.NewMarkNotificationReadLogic(ctx, s.svcCtx)
	return l.MarkNotificationRead(in)
}

// ==================== 用户设置 ====================
func (s *NotificationServer) GetUserSettings(ctx context.Context, in *pb.GetUserSettingsRequest) (*pb.GetUserSettingsResponse, error) {
	l := logic.NewGetUserSettingsLogic(ctx, s.svcCtx)
	return l.GetUserSettings(in)
}

// 更新用户推送设置
func (s *NotificationServer) UpdateUserSettings(ctx context.Context, in *pb.UpdateUserSettingsRequest) (*pb.UpdateUserSettingsResponse, error) {
	l := logic.NewUpdateUserSettingsLogic(ctx, s.svcCtx)
	return l.UpdateUserSettings(in)
}

// ==================== 模板管理（Admin）====================
func (s *NotificationServer) ListTemplates(ctx context.Context, in *pb.ListTemplatesRequest) (*pb.ListTemplatesResponse, error) {
	l := logic.NewListTemplatesLogic(ctx, s.svcCtx)
	return l.ListTemplates(in)
}

// 创建推送模板
func (s *NotificationServer) CreateTemplate(ctx context.Context, in *pb.CreateTemplateRequest) (*pb.CreateTemplateResponse, error) {
	l := logic.NewCreateTemplateLogic(ctx, s.svcCtx)
	return l.CreateTemplate(in)
}

// 更新推送模板
func (s *NotificationServer) UpdateTemplate(ctx context.Context, in *pb.UpdateTemplateRequest) (*pb.UpdateTemplateResponse, error) {
	l := logic.NewUpdateTemplateLogic(ctx, s.svcCtx)
	return l.UpdateTemplate(in)
}

// ==================== 统计分析 ====================
func (s *NotificationServer) GetStatistics(ctx context.Context, in *pb.GetStatisticsRequest) (*pb.GetStatisticsResponse, error) {
	l := logic.NewGetStatisticsLogic(ctx, s.svcCtx)
	return l.GetStatistics(in)
}
