// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: chainrpc.proto

package server

import (
	"context"

	"internalwallet/proto/pb"
	"internalwallet/services/chainrpc/rpc/internal/logic"
	"internalwallet/services/chainrpc/rpc/internal/svc"
)

type ChainRPCServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedChainRPCServer
}

func NewChainRPCServer(svcCtx *svc.ServiceContext) *ChainRPCServer {
	return &ChainRPCServer{
		svcCtx: svcCtx,
	}
}

// ==================== 转账交易 ====================
func (s *ChainRPCServer) NativeTransfer(ctx context.Context, in *pb.NativeTransferReq) (*pb.TransactionResp, error) {
	l := logic.NewNativeTransferLogic(ctx, s.svcCtx)
	return l.NativeTransfer(in)
}

// 代币转账交易
func (s *ChainRPCServer) TokenTransfer(ctx context.Context, in *pb.TokenTransferReq) (*pb.TransactionResp, error) {
	l := logic.NewTokenTransferLogic(ctx, s.svcCtx)
	return l.TokenTransfer(in)
}

// 批量转账交易（归集用）
func (s *ChainRPCServer) BatchTransfer(ctx context.Context, in *pb.BatchTransferReq) (*pb.BatchTransferResp, error) {
	l := logic.NewBatchTransferLogic(ctx, s.svcCtx)
	return l.BatchTransfer(in)
}

// 估算Gas费用
func (s *ChainRPCServer) EstimateGas(ctx context.Context, in *pb.EstimateGasReq) (*pb.EstimateGasResp, error) {
	l := logic.NewEstimateGasLogic(ctx, s.svcCtx)
	return l.EstimateGas(in)
}

// 获取推荐Gas价格
func (s *ChainRPCServer) GetGasPrice(ctx context.Context, in *pb.GetGasPriceReq) (*pb.GetGasPriceResp, error) {
	l := logic.NewGetGasPriceLogic(ctx, s.svcCtx)
	return l.GetGasPrice(in)
}

// ==================== TRON 资源/手续费 ====================
func (s *ChainRPCServer) EstimateTronFee(ctx context.Context, in *pb.EstimateTronFeeReq) (*pb.EstimateTronFeeResp, error) {
	l := logic.NewEstimateTronFeeLogic(ctx, s.svcCtx)
	return l.EstimateTronFee(in)
}

// 查询 TRON 地址资源（Bandwidth/Energy/余额）
func (s *ChainRPCServer) GetTronAccountResources(ctx context.Context, in *pb.GetTronAccountResourcesReq) (*pb.GetTronAccountResourcesResp, error) {
	l := logic.NewGetTronAccountResourcesLogic(ctx, s.svcCtx)
	return l.GetTronAccountResources(in)
}

// ==================== 交易广播 ====================
func (s *ChainRPCServer) BroadcastTransaction(ctx context.Context, in *pb.BroadcastTransactionReq) (*pb.BroadcastTransactionResp, error) {
	l := logic.NewBroadcastTransactionLogic(ctx, s.svcCtx)
	return l.BroadcastTransaction(in)
}

// 加速交易（Replace-By-Fee）
func (s *ChainRPCServer) SpeedUpTransaction(ctx context.Context, in *pb.SpeedUpTransactionReq) (*pb.SpeedUpTransactionResp, error) {
	l := logic.NewSpeedUpTransactionLogic(ctx, s.svcCtx)
	return l.SpeedUpTransaction(in)
}

// 取消交易
func (s *ChainRPCServer) CancelTransaction(ctx context.Context, in *pb.CancelTransactionReq) (*pb.CancelTransactionResp, error) {
	l := logic.NewCancelTransactionLogic(ctx, s.svcCtx)
	return l.CancelTransaction(in)
}

// ==================== 链上查询 ====================
func (s *ChainRPCServer) GetBalance(ctx context.Context, in *pb.GetBalanceReq) (*pb.GetBalanceResp, error) {
	l := logic.NewGetBalanceLogic(ctx, s.svcCtx)
	return l.GetBalance(in)
}

// 查询代币余额
func (s *ChainRPCServer) GetTokenBalance(ctx context.Context, in *pb.GetTokenBalanceReq) (*pb.GetTokenBalanceResp, error) {
	l := logic.NewGetTokenBalanceLogic(ctx, s.svcCtx)
	return l.GetTokenBalance(in)
}

// 查询多地址余额
func (s *ChainRPCServer) GetMultiBalance(ctx context.Context, in *pb.GetMultiBalanceReq) (*pb.GetMultiBalanceResp, error) {
	l := logic.NewGetMultiBalanceLogic(ctx, s.svcCtx)
	return l.GetMultiBalance(in)
}

// 查询交易详情
func (s *ChainRPCServer) GetTransaction(ctx context.Context, in *pb.GetTransactionReq) (*pb.GetTransactionResp, error) {
	l := logic.NewGetTransactionLogic(ctx, s.svcCtx)
	return l.GetTransaction(in)
}

// 查询交易状态
func (s *ChainRPCServer) GetTransactionStatus(ctx context.Context, in *pb.GetTransactionStatusReq) (*pb.GetTransactionStatusResp, error) {
	l := logic.NewGetTransactionStatusLogic(ctx, s.svcCtx)
	return l.GetTransactionStatus(in)
}

// 查询交易收据
func (s *ChainRPCServer) GetTransactionReceipt(ctx context.Context, in *pb.GetTransactionReceiptReq) (*pb.GetTransactionReceiptResp, error) {
	l := logic.NewGetTransactionReceiptLogic(ctx, s.svcCtx)
	return l.GetTransactionReceipt(in)
}

// 查询区块高度
func (s *ChainRPCServer) GetBlockHeight(ctx context.Context, in *pb.GetBlockHeightReq) (*pb.GetBlockHeightResp, error) {
	l := logic.NewGetBlockHeightLogic(ctx, s.svcCtx)
	return l.GetBlockHeight(in)
}

// 查询区块信息
func (s *ChainRPCServer) GetBlock(ctx context.Context, in *pb.GetBlockReq) (*pb.GetBlockResp, error) {
	l := logic.NewGetBlockLogic(ctx, s.svcCtx)
	return l.GetBlock(in)
}

// 查询Nonce
func (s *ChainRPCServer) GetNonce(ctx context.Context, in *pb.GetNonceReq) (*pb.GetNonceResp, error) {
	l := logic.NewGetNonceLogic(ctx, s.svcCtx)
	return l.GetNonce(in)
}

// 构建 EVM 交易（ETH/BSC，返回未签名 rawTx，供 Signer 签名）
func (s *ChainRPCServer) BuildTransaction(ctx context.Context, in *pb.BuildTransactionReq) (*pb.BuildTransactionResp, error) {
	l := logic.NewBuildTransactionLogic(ctx, s.svcCtx)
	return l.BuildTransaction(in)
}

// 构建 TRON 交易（返回未签名的 rawData，供客户端签名）
func (s *ChainRPCServer) BuildTronTransaction(ctx context.Context, in *pb.ChainRpcBuildTronTransactionReq) (*pb.ChainRpcBuildTronTransactionResp, error) {
	l := logic.NewBuildTronTransactionLogic(ctx, s.svcCtx)
	return l.BuildTronTransaction(in)
}

// ==================== 代币信息 ====================
func (s *ChainRPCServer) GetTokenInfo(ctx context.Context, in *pb.GetTokenInfoReq) (*pb.GetTokenInfoResp, error) {
	l := logic.NewGetTokenInfoLogic(ctx, s.svcCtx)
	return l.GetTokenInfo(in)
}

// 批量查询代币信息
func (s *ChainRPCServer) GetTokenInfoBatch(ctx context.Context, in *pb.GetTokenInfoBatchReq) (*pb.GetTokenInfoBatchResp, error) {
	l := logic.NewGetTokenInfoBatchLogic(ctx, s.svcCtx)
	return l.GetTokenInfoBatch(in)
}

// ==================== 节点管理 ====================
func (s *ChainRPCServer) HealthCheck(ctx context.Context, in *pb.HealthCheckReq) (*pb.HealthCheckResp, error) {
	l := logic.NewHealthCheckLogic(ctx, s.svcCtx)
	return l.HealthCheck(in)
}

// 获取节点状态
func (s *ChainRPCServer) GetNodeStatus(ctx context.Context, in *pb.GetNodeStatusReq) (*pb.GetNodeStatusResp, error) {
	l := logic.NewGetNodeStatusLogic(ctx, s.svcCtx)
	return l.GetNodeStatus(in)
}

// 切换节点
func (s *ChainRPCServer) SwitchNode(ctx context.Context, in *pb.SwitchNodeReq) (*pb.SwitchNodeResp, error) {
	l := logic.NewSwitchNodeLogic(ctx, s.svcCtx)
	return l.SwitchNode(in)
}

// 测试节点连接
func (s *ChainRPCServer) TestNode(ctx context.Context, in *pb.TestNodeReq) (*pb.TestNodeResp, error) {
	l := logic.NewTestNodeLogic(ctx, s.svcCtx)
	return l.TestNode(in)
}
