export type IconifyCatalogItem = {
  /** e.g. `lucide:user` */
  icon: string;
  /** human readable label for searching */
  label: string;
};

// Keep this list curated to avoid bundling a huge icon index.
// Add more icons here when needed.
export const ICONIFY_LUCIDE: IconifyCatalogItem[] = [
  { icon: 'lucide:home', label: 'Home' },
  { icon: 'lucide:layout-dashboard', label: 'Dashboard' },
  { icon: 'lucide:panel-left', label: 'Sidebar' },
  { icon: 'lucide:menu', label: 'Menu' },
  { icon: 'lucide:wallet', label: 'Wallet' },
  { icon: 'lucide:credit-card', label: 'Card' },
  { icon: 'lucide:badge-dollar-sign', label: 'USD' },
  { icon: 'lucide:banknote', label: 'Banknote' },
  { icon: 'lucide:landmark', label: 'Bank' },
  { icon: 'lucide:send', label: 'Send' },
  { icon: 'lucide:arrow-right-left', label: 'Transfer' },
  { icon: 'lucide:arrow-left-right', label: 'Swap' },
  { icon: 'lucide:download', label: 'Download' },
  { icon: 'lucide:upload', label: 'Upload' },
  { icon: 'lucide:arrow-down-to-line', label: 'Import' },
  { icon: 'lucide:arrow-up-from-line', label: 'Export' },
  { icon: 'lucide:users', label: 'Users' },
  { icon: 'lucide:user', label: 'User' },
  { icon: 'lucide:user-cog', label: 'User Settings' },
  { icon: 'lucide:user-plus', label: 'User Add' },
  { icon: 'lucide:user-minus', label: 'User Remove' },
  { icon: 'lucide:badge-check', label: 'Verified' },
  { icon: 'lucide:settings', label: 'Settings' },
  { icon: 'lucide:sliders-horizontal', label: 'Controls' },
  { icon: 'lucide:wrench', label: 'Tools' },
  { icon: 'lucide:shield', label: 'Shield' },
  { icon: 'lucide:shield-check', label: 'Shield Check' },
  { icon: 'lucide:shield-alert', label: 'Shield Alert' },
  { icon: 'lucide:key', label: 'Key' },
  { icon: 'lucide:lock', label: 'Lock' },
  { icon: 'lucide:unlock', label: 'Unlock' },
  { icon: 'lucide:fingerprint', label: 'Fingerprint' },
  { icon: 'lucide:file-search', label: 'Search File' },
  { icon: 'lucide:search', label: 'Search' },
  { icon: 'lucide:filter', label: 'Filter' },
  { icon: 'lucide:list', label: 'List' },
  { icon: 'lucide:table', label: 'Table' },
  { icon: 'lucide:bar-chart-3', label: 'Chart' },
  { icon: 'lucide:pie-chart', label: 'Pie Chart' },
  { icon: 'lucide:line-chart', label: 'Line Chart' },
  { icon: 'lucide:history', label: 'History' },
  { icon: 'lucide:clipboard-check', label: 'Approval' },
  { icon: 'lucide:clipboard-list', label: 'Checklist' },
  { icon: 'lucide:check-circle-2', label: 'Success' },
  { icon: 'lucide:x-circle', label: 'Error' },
  { icon: 'lucide:alert-triangle', label: 'Warning' },
  { icon: 'lucide:info', label: 'Info' },
  { icon: 'lucide:circle-help', label: 'Help' },
  { icon: 'lucide:bell', label: 'Notification' },
  { icon: 'lucide:mail', label: 'Email' },
  { icon: 'lucide:message-square', label: 'Message' },
  { icon: 'lucide:globe', label: 'Globe' },
  { icon: 'lucide:cloud', label: 'Cloud' },
  { icon: 'lucide:database', label: 'Database' },
  { icon: 'lucide:server', label: 'Server' },
  { icon: 'lucide:terminal', label: 'Terminal' },
  { icon: 'lucide:file-text', label: 'Document' },
  { icon: 'lucide:file', label: 'File' },
  { icon: 'lucide:folder', label: 'Folder' },
  { icon: 'lucide:folder-tree', label: 'Folder Tree' },
  { icon: 'lucide:tag', label: 'Tag' },
  { icon: 'lucide:bookmark', label: 'Bookmark' },
  { icon: 'lucide:calendar', label: 'Calendar' },
  { icon: 'lucide:clock', label: 'Clock' },
  { icon: 'lucide:map', label: 'Map' },
  { icon: 'lucide:map-pin', label: 'Pin' },
  { icon: 'lucide:link', label: 'Link' },
  { icon: 'lucide:external-link', label: 'External Link' },
  { icon: 'lucide:eye', label: 'View' },
  { icon: 'lucide:eye-off', label: 'Hide' },
  { icon: 'lucide:trash-2', label: 'Delete' },
  { icon: 'lucide:pencil', label: 'Edit' },
  { icon: 'lucide:plus', label: 'Add' },
  { icon: 'lucide:minus', label: 'Minus' },
  { icon: 'lucide:refresh-cw', label: 'Reload' },
  { icon: 'lucide:loader', label: 'Loading' },
  { icon: 'lucide:copy', label: 'Copy' },
  { icon: 'lucide:save', label: 'Save' },
  { icon: 'lucide:share-2', label: 'Share' },
  { icon: 'lucide:log-in', label: 'Login' },
  { icon: 'lucide:log-out', label: 'Logout' },
  { icon: 'lucide:shield-ellipsis', label: 'Security' },
];

export const ICONIFY_MDI: IconifyCatalogItem[] = [
  { icon: 'mdi:view-dashboard-outline', label: 'Dashboard' },
  { icon: 'mdi:view-dashboard-variant-outline', label: 'Dashboard Variant' },
  { icon: 'mdi:menu', label: 'Menu' },
  { icon: 'mdi:wallet-outline', label: 'Wallet' },
  { icon: 'mdi:credit-card-outline', label: 'Card' },
  { icon: 'mdi:cash', label: 'Cash' },
  { icon: 'mdi:bank-outline', label: 'Bank' },
  { icon: 'mdi:account-group-outline', label: 'Users' },
  { icon: 'mdi:account-outline', label: 'User' },
  { icon: 'mdi:account-cog-outline', label: 'User Settings' },
  { icon: 'mdi:account-plus-outline', label: 'User Add' },
  { icon: 'mdi:account-remove-outline', label: 'User Remove' },
  { icon: 'mdi:cog-outline', label: 'Settings' },
  { icon: 'mdi:tune', label: 'Controls' },
  { icon: 'mdi:wrench-outline', label: 'Tools' },
  { icon: 'mdi:shield-check-outline', label: 'Shield' },
  { icon: 'mdi:shield-alert-outline', label: 'Shield Alert' },
  { icon: 'mdi:key-outline', label: 'Key' },
  { icon: 'mdi:lock-outline', label: 'Lock' },
  { icon: 'mdi:lock-open-outline', label: 'Unlock' },
  { icon: 'mdi:fingerprint', label: 'Fingerprint' },
  { icon: 'mdi:file-search-outline', label: 'Audit/Search' },
  { icon: 'mdi:magnify', label: 'Search' },
  { icon: 'mdi:filter-variant', label: 'Filter' },
  { icon: 'mdi:format-list-bulleted', label: 'List' },
  { icon: 'mdi:table', label: 'Table' },
  { icon: 'mdi:chart-bar', label: 'Chart' },
  { icon: 'mdi:chart-pie', label: 'Pie Chart' },
  { icon: 'mdi:download', label: 'Download' },
  { icon: 'mdi:upload', label: 'Upload' },
  { icon: 'mdi:send', label: 'Send' },
  { icon: 'mdi:history', label: 'History' },
  { icon: 'mdi:swap-horizontal', label: 'Swap' },
  { icon: 'mdi:clipboard-check-outline', label: 'Approval' },
  { icon: 'mdi:check-circle-outline', label: 'Success' },
  { icon: 'mdi:close-circle-outline', label: 'Error' },
  { icon: 'mdi:alert-outline', label: 'Warning' },
  { icon: 'mdi:information-outline', label: 'Info' },
  { icon: 'mdi:help-circle-outline', label: 'Help' },
  { icon: 'mdi:bell-outline', label: 'Notification' },
  { icon: 'mdi:email-outline', label: 'Email' },
  { icon: 'mdi:message-outline', label: 'Message' },
  { icon: 'mdi:web', label: 'Web' },
  { icon: 'mdi:cloud-outline', label: 'Cloud' },
  { icon: 'mdi:database-outline', label: 'Database' },
  { icon: 'mdi:server', label: 'Server' },
  { icon: 'mdi:console', label: 'Terminal' },
  { icon: 'mdi:file-document-outline', label: 'Document' },
  { icon: 'mdi:file-outline', label: 'File' },
  { icon: 'mdi:folder-outline', label: 'Folder' },
  { icon: 'mdi:tag-outline', label: 'Tag' },
  { icon: 'mdi:bookmark-outline', label: 'Bookmark' },
  { icon: 'mdi:calendar-month-outline', label: 'Calendar' },
  { icon: 'mdi:clock-outline', label: 'Clock' },
  { icon: 'mdi:map-outline', label: 'Map' },
  { icon: 'mdi:map-marker-outline', label: 'Pin' },
  { icon: 'mdi:link-variant', label: 'Link' },
  { icon: 'mdi:open-in-new', label: 'External Link' },
  { icon: 'mdi:eye-outline', label: 'View' },
  { icon: 'mdi:eye-off-outline', label: 'Hide' },
  { icon: 'mdi:trash-can-outline', label: 'Delete' },
  { icon: 'mdi:pencil-outline', label: 'Edit' },
  { icon: 'mdi:plus', label: 'Add' },
  { icon: 'mdi:minus', label: 'Minus' },
  { icon: 'mdi:refresh', label: 'Reload' },
  { icon: 'mdi:loading', label: 'Loading' },
  { icon: 'mdi:content-copy', label: 'Copy' },
  { icon: 'mdi:content-save-outline', label: 'Save' },
  { icon: 'mdi:share-variant-outline', label: 'Share' },
  { icon: 'mdi:login', label: 'Login' },
  { icon: 'mdi:logout', label: 'Logout' },
];


