// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: chainrpc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChainRPC_NativeTransfer_FullMethodName          = "/chainrpc.ChainRPC/NativeTransfer"
	ChainRPC_TokenTransfer_FullMethodName           = "/chainrpc.ChainRPC/TokenTransfer"
	ChainRPC_BatchTransfer_FullMethodName           = "/chainrpc.ChainRPC/BatchTransfer"
	ChainRPC_EstimateGas_FullMethodName             = "/chainrpc.ChainRPC/EstimateGas"
	ChainRPC_GetGasPrice_FullMethodName             = "/chainrpc.ChainRPC/GetGasPrice"
	ChainRPC_EstimateTronFee_FullMethodName         = "/chainrpc.ChainRPC/EstimateTronFee"
	ChainRPC_GetTronAccountResources_FullMethodName = "/chainrpc.ChainRPC/GetTronAccountResources"
	ChainRPC_BroadcastTransaction_FullMethodName    = "/chainrpc.ChainRPC/BroadcastTransaction"
	ChainRPC_SpeedUpTransaction_FullMethodName      = "/chainrpc.ChainRPC/SpeedUpTransaction"
	ChainRPC_CancelTransaction_FullMethodName       = "/chainrpc.ChainRPC/CancelTransaction"
	ChainRPC_GetBalance_FullMethodName              = "/chainrpc.ChainRPC/GetBalance"
	ChainRPC_GetTokenBalance_FullMethodName         = "/chainrpc.ChainRPC/GetTokenBalance"
	ChainRPC_GetMultiBalance_FullMethodName         = "/chainrpc.ChainRPC/GetMultiBalance"
	ChainRPC_GetTransaction_FullMethodName          = "/chainrpc.ChainRPC/GetTransaction"
	ChainRPC_GetTransactionStatus_FullMethodName    = "/chainrpc.ChainRPC/GetTransactionStatus"
	ChainRPC_GetTransactionReceipt_FullMethodName   = "/chainrpc.ChainRPC/GetTransactionReceipt"
	ChainRPC_GetBlockHeight_FullMethodName          = "/chainrpc.ChainRPC/GetBlockHeight"
	ChainRPC_GetBlock_FullMethodName                = "/chainrpc.ChainRPC/GetBlock"
	ChainRPC_GetNonce_FullMethodName                = "/chainrpc.ChainRPC/GetNonce"
	ChainRPC_BuildTransaction_FullMethodName        = "/chainrpc.ChainRPC/BuildTransaction"
	ChainRPC_BuildTronTransaction_FullMethodName    = "/chainrpc.ChainRPC/BuildTronTransaction"
	ChainRPC_GetTokenInfo_FullMethodName            = "/chainrpc.ChainRPC/GetTokenInfo"
	ChainRPC_GetTokenInfoBatch_FullMethodName       = "/chainrpc.ChainRPC/GetTokenInfoBatch"
	ChainRPC_HealthCheck_FullMethodName             = "/chainrpc.ChainRPC/HealthCheck"
	ChainRPC_GetNodeStatus_FullMethodName           = "/chainrpc.ChainRPC/GetNodeStatus"
	ChainRPC_SwitchNode_FullMethodName              = "/chainrpc.ChainRPC/SwitchNode"
	ChainRPC_TestNode_FullMethodName                = "/chainrpc.ChainRPC/TestNode"
)

// ChainRPCClient is the client API for ChainRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 链RPC服务 - 地址生成、转账交易、链上查询
type ChainRPCClient interface {
	// ==================== 转账交易 ====================
	// 主币转账交易
	NativeTransfer(ctx context.Context, in *NativeTransferReq, opts ...grpc.CallOption) (*TransactionResp, error)
	// 代币转账交易
	TokenTransfer(ctx context.Context, in *TokenTransferReq, opts ...grpc.CallOption) (*TransactionResp, error)
	// 批量转账交易（归集用）
	BatchTransfer(ctx context.Context, in *BatchTransferReq, opts ...grpc.CallOption) (*BatchTransferResp, error)
	// 估算Gas费用
	EstimateGas(ctx context.Context, in *EstimateGasReq, opts ...grpc.CallOption) (*EstimateGasResp, error)
	// 获取推荐Gas价格
	GetGasPrice(ctx context.Context, in *GetGasPriceReq, opts ...grpc.CallOption) (*GetGasPriceResp, error)
	// ==================== TRON 资源/手续费 ====================
	// 估算 TRON 手续费（Bandwidth + Energy + 激活费）
	EstimateTronFee(ctx context.Context, in *EstimateTronFeeReq, opts ...grpc.CallOption) (*EstimateTronFeeResp, error)
	// 查询 TRON 地址资源（Bandwidth/Energy/余额）
	GetTronAccountResources(ctx context.Context, in *GetTronAccountResourcesReq, opts ...grpc.CallOption) (*GetTronAccountResourcesResp, error)
	// ==================== 交易广播 ====================
	// 广播已签名交易
	BroadcastTransaction(ctx context.Context, in *BroadcastTransactionReq, opts ...grpc.CallOption) (*BroadcastTransactionResp, error)
	// 加速交易（Replace-By-Fee）
	SpeedUpTransaction(ctx context.Context, in *SpeedUpTransactionReq, opts ...grpc.CallOption) (*SpeedUpTransactionResp, error)
	// 取消交易
	CancelTransaction(ctx context.Context, in *CancelTransactionReq, opts ...grpc.CallOption) (*CancelTransactionResp, error)
	// ==================== 链上查询 ====================
	// 查询地址余额（主币）
	GetBalance(ctx context.Context, in *GetBalanceReq, opts ...grpc.CallOption) (*GetBalanceResp, error)
	// 查询代币余额
	GetTokenBalance(ctx context.Context, in *GetTokenBalanceReq, opts ...grpc.CallOption) (*GetTokenBalanceResp, error)
	// 查询多地址余额
	GetMultiBalance(ctx context.Context, in *GetMultiBalanceReq, opts ...grpc.CallOption) (*GetMultiBalanceResp, error)
	// 查询交易详情
	GetTransaction(ctx context.Context, in *GetTransactionReq, opts ...grpc.CallOption) (*GetTransactionResp, error)
	// 查询交易状态
	GetTransactionStatus(ctx context.Context, in *GetTransactionStatusReq, opts ...grpc.CallOption) (*GetTransactionStatusResp, error)
	// 查询交易收据
	GetTransactionReceipt(ctx context.Context, in *GetTransactionReceiptReq, opts ...grpc.CallOption) (*GetTransactionReceiptResp, error)
	// 查询区块高度
	GetBlockHeight(ctx context.Context, in *GetBlockHeightReq, opts ...grpc.CallOption) (*GetBlockHeightResp, error)
	// 查询区块信息
	GetBlock(ctx context.Context, in *GetBlockReq, opts ...grpc.CallOption) (*GetBlockResp, error)
	// 查询Nonce
	GetNonce(ctx context.Context, in *GetNonceReq, opts ...grpc.CallOption) (*GetNonceResp, error)
	// 构建 EVM 交易（ETH/BSC，返回未签名 rawTx，供 Signer 签名）
	BuildTransaction(ctx context.Context, in *BuildTransactionReq, opts ...grpc.CallOption) (*BuildTransactionResp, error)
	// 构建 TRON 交易（返回未签名的 rawData，供客户端签名）
	BuildTronTransaction(ctx context.Context, in *ChainRpcBuildTronTransactionReq, opts ...grpc.CallOption) (*ChainRpcBuildTronTransactionResp, error)
	// ==================== 代币信息 ====================
	// 查询代币信息（symbol, decimals, totalSupply）
	GetTokenInfo(ctx context.Context, in *GetTokenInfoReq, opts ...grpc.CallOption) (*GetTokenInfoResp, error)
	// 批量查询代币信息
	GetTokenInfoBatch(ctx context.Context, in *GetTokenInfoBatchReq, opts ...grpc.CallOption) (*GetTokenInfoBatchResp, error)
	// ==================== 节点管理 ====================
	// 节点健康检查
	HealthCheck(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckResp, error)
	// 获取节点状态
	GetNodeStatus(ctx context.Context, in *GetNodeStatusReq, opts ...grpc.CallOption) (*GetNodeStatusResp, error)
	// 切换节点
	SwitchNode(ctx context.Context, in *SwitchNodeReq, opts ...grpc.CallOption) (*SwitchNodeResp, error)
	// 测试节点连接
	TestNode(ctx context.Context, in *TestNodeReq, opts ...grpc.CallOption) (*TestNodeResp, error)
}

type chainRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewChainRPCClient(cc grpc.ClientConnInterface) ChainRPCClient {
	return &chainRPCClient{cc}
}

func (c *chainRPCClient) NativeTransfer(ctx context.Context, in *NativeTransferReq, opts ...grpc.CallOption) (*TransactionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResp)
	err := c.cc.Invoke(ctx, ChainRPC_NativeTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) TokenTransfer(ctx context.Context, in *TokenTransferReq, opts ...grpc.CallOption) (*TransactionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionResp)
	err := c.cc.Invoke(ctx, ChainRPC_TokenTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) BatchTransfer(ctx context.Context, in *BatchTransferReq, opts ...grpc.CallOption) (*BatchTransferResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchTransferResp)
	err := c.cc.Invoke(ctx, ChainRPC_BatchTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) EstimateGas(ctx context.Context, in *EstimateGasReq, opts ...grpc.CallOption) (*EstimateGasResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimateGasResp)
	err := c.cc.Invoke(ctx, ChainRPC_EstimateGas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) GetGasPrice(ctx context.Context, in *GetGasPriceReq, opts ...grpc.CallOption) (*GetGasPriceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGasPriceResp)
	err := c.cc.Invoke(ctx, ChainRPC_GetGasPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) EstimateTronFee(ctx context.Context, in *EstimateTronFeeReq, opts ...grpc.CallOption) (*EstimateTronFeeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimateTronFeeResp)
	err := c.cc.Invoke(ctx, ChainRPC_EstimateTronFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) GetTronAccountResources(ctx context.Context, in *GetTronAccountResourcesReq, opts ...grpc.CallOption) (*GetTronAccountResourcesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTronAccountResourcesResp)
	err := c.cc.Invoke(ctx, ChainRPC_GetTronAccountResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) BroadcastTransaction(ctx context.Context, in *BroadcastTransactionReq, opts ...grpc.CallOption) (*BroadcastTransactionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastTransactionResp)
	err := c.cc.Invoke(ctx, ChainRPC_BroadcastTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) SpeedUpTransaction(ctx context.Context, in *SpeedUpTransactionReq, opts ...grpc.CallOption) (*SpeedUpTransactionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpeedUpTransactionResp)
	err := c.cc.Invoke(ctx, ChainRPC_SpeedUpTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) CancelTransaction(ctx context.Context, in *CancelTransactionReq, opts ...grpc.CallOption) (*CancelTransactionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTransactionResp)
	err := c.cc.Invoke(ctx, ChainRPC_CancelTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) GetBalance(ctx context.Context, in *GetBalanceReq, opts ...grpc.CallOption) (*GetBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResp)
	err := c.cc.Invoke(ctx, ChainRPC_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) GetTokenBalance(ctx context.Context, in *GetTokenBalanceReq, opts ...grpc.CallOption) (*GetTokenBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenBalanceResp)
	err := c.cc.Invoke(ctx, ChainRPC_GetTokenBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) GetMultiBalance(ctx context.Context, in *GetMultiBalanceReq, opts ...grpc.CallOption) (*GetMultiBalanceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMultiBalanceResp)
	err := c.cc.Invoke(ctx, ChainRPC_GetMultiBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) GetTransaction(ctx context.Context, in *GetTransactionReq, opts ...grpc.CallOption) (*GetTransactionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionResp)
	err := c.cc.Invoke(ctx, ChainRPC_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) GetTransactionStatus(ctx context.Context, in *GetTransactionStatusReq, opts ...grpc.CallOption) (*GetTransactionStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionStatusResp)
	err := c.cc.Invoke(ctx, ChainRPC_GetTransactionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) GetTransactionReceipt(ctx context.Context, in *GetTransactionReceiptReq, opts ...grpc.CallOption) (*GetTransactionReceiptResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionReceiptResp)
	err := c.cc.Invoke(ctx, ChainRPC_GetTransactionReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) GetBlockHeight(ctx context.Context, in *GetBlockHeightReq, opts ...grpc.CallOption) (*GetBlockHeightResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockHeightResp)
	err := c.cc.Invoke(ctx, ChainRPC_GetBlockHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) GetBlock(ctx context.Context, in *GetBlockReq, opts ...grpc.CallOption) (*GetBlockResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockResp)
	err := c.cc.Invoke(ctx, ChainRPC_GetBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) GetNonce(ctx context.Context, in *GetNonceReq, opts ...grpc.CallOption) (*GetNonceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNonceResp)
	err := c.cc.Invoke(ctx, ChainRPC_GetNonce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) BuildTransaction(ctx context.Context, in *BuildTransactionReq, opts ...grpc.CallOption) (*BuildTransactionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildTransactionResp)
	err := c.cc.Invoke(ctx, ChainRPC_BuildTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) BuildTronTransaction(ctx context.Context, in *ChainRpcBuildTronTransactionReq, opts ...grpc.CallOption) (*ChainRpcBuildTronTransactionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChainRpcBuildTronTransactionResp)
	err := c.cc.Invoke(ctx, ChainRPC_BuildTronTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) GetTokenInfo(ctx context.Context, in *GetTokenInfoReq, opts ...grpc.CallOption) (*GetTokenInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenInfoResp)
	err := c.cc.Invoke(ctx, ChainRPC_GetTokenInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) GetTokenInfoBatch(ctx context.Context, in *GetTokenInfoBatchReq, opts ...grpc.CallOption) (*GetTokenInfoBatchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenInfoBatchResp)
	err := c.cc.Invoke(ctx, ChainRPC_GetTokenInfoBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) HealthCheck(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResp)
	err := c.cc.Invoke(ctx, ChainRPC_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) GetNodeStatus(ctx context.Context, in *GetNodeStatusReq, opts ...grpc.CallOption) (*GetNodeStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeStatusResp)
	err := c.cc.Invoke(ctx, ChainRPC_GetNodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) SwitchNode(ctx context.Context, in *SwitchNodeReq, opts ...grpc.CallOption) (*SwitchNodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwitchNodeResp)
	err := c.cc.Invoke(ctx, ChainRPC_SwitchNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainRPCClient) TestNode(ctx context.Context, in *TestNodeReq, opts ...grpc.CallOption) (*TestNodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestNodeResp)
	err := c.cc.Invoke(ctx, ChainRPC_TestNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainRPCServer is the server API for ChainRPC service.
// All implementations must embed UnimplementedChainRPCServer
// for forward compatibility.
//
// 链RPC服务 - 地址生成、转账交易、链上查询
type ChainRPCServer interface {
	// ==================== 转账交易 ====================
	// 主币转账交易
	NativeTransfer(context.Context, *NativeTransferReq) (*TransactionResp, error)
	// 代币转账交易
	TokenTransfer(context.Context, *TokenTransferReq) (*TransactionResp, error)
	// 批量转账交易（归集用）
	BatchTransfer(context.Context, *BatchTransferReq) (*BatchTransferResp, error)
	// 估算Gas费用
	EstimateGas(context.Context, *EstimateGasReq) (*EstimateGasResp, error)
	// 获取推荐Gas价格
	GetGasPrice(context.Context, *GetGasPriceReq) (*GetGasPriceResp, error)
	// ==================== TRON 资源/手续费 ====================
	// 估算 TRON 手续费（Bandwidth + Energy + 激活费）
	EstimateTronFee(context.Context, *EstimateTronFeeReq) (*EstimateTronFeeResp, error)
	// 查询 TRON 地址资源（Bandwidth/Energy/余额）
	GetTronAccountResources(context.Context, *GetTronAccountResourcesReq) (*GetTronAccountResourcesResp, error)
	// ==================== 交易广播 ====================
	// 广播已签名交易
	BroadcastTransaction(context.Context, *BroadcastTransactionReq) (*BroadcastTransactionResp, error)
	// 加速交易（Replace-By-Fee）
	SpeedUpTransaction(context.Context, *SpeedUpTransactionReq) (*SpeedUpTransactionResp, error)
	// 取消交易
	CancelTransaction(context.Context, *CancelTransactionReq) (*CancelTransactionResp, error)
	// ==================== 链上查询 ====================
	// 查询地址余额（主币）
	GetBalance(context.Context, *GetBalanceReq) (*GetBalanceResp, error)
	// 查询代币余额
	GetTokenBalance(context.Context, *GetTokenBalanceReq) (*GetTokenBalanceResp, error)
	// 查询多地址余额
	GetMultiBalance(context.Context, *GetMultiBalanceReq) (*GetMultiBalanceResp, error)
	// 查询交易详情
	GetTransaction(context.Context, *GetTransactionReq) (*GetTransactionResp, error)
	// 查询交易状态
	GetTransactionStatus(context.Context, *GetTransactionStatusReq) (*GetTransactionStatusResp, error)
	// 查询交易收据
	GetTransactionReceipt(context.Context, *GetTransactionReceiptReq) (*GetTransactionReceiptResp, error)
	// 查询区块高度
	GetBlockHeight(context.Context, *GetBlockHeightReq) (*GetBlockHeightResp, error)
	// 查询区块信息
	GetBlock(context.Context, *GetBlockReq) (*GetBlockResp, error)
	// 查询Nonce
	GetNonce(context.Context, *GetNonceReq) (*GetNonceResp, error)
	// 构建 EVM 交易（ETH/BSC，返回未签名 rawTx，供 Signer 签名）
	BuildTransaction(context.Context, *BuildTransactionReq) (*BuildTransactionResp, error)
	// 构建 TRON 交易（返回未签名的 rawData，供客户端签名）
	BuildTronTransaction(context.Context, *ChainRpcBuildTronTransactionReq) (*ChainRpcBuildTronTransactionResp, error)
	// ==================== 代币信息 ====================
	// 查询代币信息（symbol, decimals, totalSupply）
	GetTokenInfo(context.Context, *GetTokenInfoReq) (*GetTokenInfoResp, error)
	// 批量查询代币信息
	GetTokenInfoBatch(context.Context, *GetTokenInfoBatchReq) (*GetTokenInfoBatchResp, error)
	// ==================== 节点管理 ====================
	// 节点健康检查
	HealthCheck(context.Context, *HealthCheckReq) (*HealthCheckResp, error)
	// 获取节点状态
	GetNodeStatus(context.Context, *GetNodeStatusReq) (*GetNodeStatusResp, error)
	// 切换节点
	SwitchNode(context.Context, *SwitchNodeReq) (*SwitchNodeResp, error)
	// 测试节点连接
	TestNode(context.Context, *TestNodeReq) (*TestNodeResp, error)
	mustEmbedUnimplementedChainRPCServer()
}

// UnimplementedChainRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChainRPCServer struct{}

func (UnimplementedChainRPCServer) NativeTransfer(context.Context, *NativeTransferReq) (*TransactionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method NativeTransfer not implemented")
}
func (UnimplementedChainRPCServer) TokenTransfer(context.Context, *TokenTransferReq) (*TransactionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TokenTransfer not implemented")
}
func (UnimplementedChainRPCServer) BatchTransfer(context.Context, *BatchTransferReq) (*BatchTransferResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchTransfer not implemented")
}
func (UnimplementedChainRPCServer) EstimateGas(context.Context, *EstimateGasReq) (*EstimateGasResp, error) {
	return nil, status.Error(codes.Unimplemented, "method EstimateGas not implemented")
}
func (UnimplementedChainRPCServer) GetGasPrice(context.Context, *GetGasPriceReq) (*GetGasPriceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGasPrice not implemented")
}
func (UnimplementedChainRPCServer) EstimateTronFee(context.Context, *EstimateTronFeeReq) (*EstimateTronFeeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method EstimateTronFee not implemented")
}
func (UnimplementedChainRPCServer) GetTronAccountResources(context.Context, *GetTronAccountResourcesReq) (*GetTronAccountResourcesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTronAccountResources not implemented")
}
func (UnimplementedChainRPCServer) BroadcastTransaction(context.Context, *BroadcastTransactionReq) (*BroadcastTransactionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BroadcastTransaction not implemented")
}
func (UnimplementedChainRPCServer) SpeedUpTransaction(context.Context, *SpeedUpTransactionReq) (*SpeedUpTransactionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SpeedUpTransaction not implemented")
}
func (UnimplementedChainRPCServer) CancelTransaction(context.Context, *CancelTransactionReq) (*CancelTransactionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTransaction not implemented")
}
func (UnimplementedChainRPCServer) GetBalance(context.Context, *GetBalanceReq) (*GetBalanceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedChainRPCServer) GetTokenBalance(context.Context, *GetTokenBalanceReq) (*GetTokenBalanceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTokenBalance not implemented")
}
func (UnimplementedChainRPCServer) GetMultiBalance(context.Context, *GetMultiBalanceReq) (*GetMultiBalanceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMultiBalance not implemented")
}
func (UnimplementedChainRPCServer) GetTransaction(context.Context, *GetTransactionReq) (*GetTransactionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedChainRPCServer) GetTransactionStatus(context.Context, *GetTransactionStatusReq) (*GetTransactionStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionStatus not implemented")
}
func (UnimplementedChainRPCServer) GetTransactionReceipt(context.Context, *GetTransactionReceiptReq) (*GetTransactionReceiptResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionReceipt not implemented")
}
func (UnimplementedChainRPCServer) GetBlockHeight(context.Context, *GetBlockHeightReq) (*GetBlockHeightResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockHeight not implemented")
}
func (UnimplementedChainRPCServer) GetBlock(context.Context, *GetBlockReq) (*GetBlockResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedChainRPCServer) GetNonce(context.Context, *GetNonceReq) (*GetNonceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNonce not implemented")
}
func (UnimplementedChainRPCServer) BuildTransaction(context.Context, *BuildTransactionReq) (*BuildTransactionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildTransaction not implemented")
}
func (UnimplementedChainRPCServer) BuildTronTransaction(context.Context, *ChainRpcBuildTronTransactionReq) (*ChainRpcBuildTronTransactionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildTronTransaction not implemented")
}
func (UnimplementedChainRPCServer) GetTokenInfo(context.Context, *GetTokenInfoReq) (*GetTokenInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTokenInfo not implemented")
}
func (UnimplementedChainRPCServer) GetTokenInfoBatch(context.Context, *GetTokenInfoBatchReq) (*GetTokenInfoBatchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTokenInfoBatch not implemented")
}
func (UnimplementedChainRPCServer) HealthCheck(context.Context, *HealthCheckReq) (*HealthCheckResp, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedChainRPCServer) GetNodeStatus(context.Context, *GetNodeStatusReq) (*GetNodeStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeStatus not implemented")
}
func (UnimplementedChainRPCServer) SwitchNode(context.Context, *SwitchNodeReq) (*SwitchNodeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SwitchNode not implemented")
}
func (UnimplementedChainRPCServer) TestNode(context.Context, *TestNodeReq) (*TestNodeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TestNode not implemented")
}
func (UnimplementedChainRPCServer) mustEmbedUnimplementedChainRPCServer() {}
func (UnimplementedChainRPCServer) testEmbeddedByValue()                  {}

// UnsafeChainRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainRPCServer will
// result in compilation errors.
type UnsafeChainRPCServer interface {
	mustEmbedUnimplementedChainRPCServer()
}

func RegisterChainRPCServer(s grpc.ServiceRegistrar, srv ChainRPCServer) {
	// If the following call panics, it indicates UnimplementedChainRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChainRPC_ServiceDesc, srv)
}

func _ChainRPC_NativeTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NativeTransferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).NativeTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_NativeTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).NativeTransfer(ctx, req.(*NativeTransferReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_TokenTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenTransferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).TokenTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_TokenTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).TokenTransfer(ctx, req.(*TokenTransferReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_BatchTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchTransferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).BatchTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_BatchTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).BatchTransfer(ctx, req.(*BatchTransferReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_EstimateGas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateGasReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).EstimateGas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_EstimateGas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).EstimateGas(ctx, req.(*EstimateGasReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_GetGasPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGasPriceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).GetGasPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_GetGasPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).GetGasPrice(ctx, req.(*GetGasPriceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_EstimateTronFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateTronFeeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).EstimateTronFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_EstimateTronFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).EstimateTronFee(ctx, req.(*EstimateTronFeeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_GetTronAccountResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTronAccountResourcesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).GetTronAccountResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_GetTronAccountResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).GetTronAccountResources(ctx, req.(*GetTronAccountResourcesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_BroadcastTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastTransactionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).BroadcastTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_BroadcastTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).BroadcastTransaction(ctx, req.(*BroadcastTransactionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_SpeedUpTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpeedUpTransactionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).SpeedUpTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_SpeedUpTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).SpeedUpTransaction(ctx, req.(*SpeedUpTransactionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_CancelTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTransactionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).CancelTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_CancelTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).CancelTransaction(ctx, req.(*CancelTransactionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).GetBalance(ctx, req.(*GetBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_GetTokenBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).GetTokenBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_GetTokenBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).GetTokenBalance(ctx, req.(*GetTokenBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_GetMultiBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMultiBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).GetMultiBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_GetMultiBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).GetMultiBalance(ctx, req.(*GetMultiBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).GetTransaction(ctx, req.(*GetTransactionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_GetTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).GetTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_GetTransactionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).GetTransactionStatus(ctx, req.(*GetTransactionStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_GetTransactionReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionReceiptReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).GetTransactionReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_GetTransactionReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).GetTransactionReceipt(ctx, req.(*GetTransactionReceiptReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_GetBlockHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockHeightReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).GetBlockHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_GetBlockHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).GetBlockHeight(ctx, req.(*GetBlockHeightReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_GetBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).GetBlock(ctx, req.(*GetBlockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_GetNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNonceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).GetNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_GetNonce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).GetNonce(ctx, req.(*GetNonceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_BuildTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildTransactionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).BuildTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_BuildTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).BuildTransaction(ctx, req.(*BuildTransactionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_BuildTronTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainRpcBuildTronTransactionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).BuildTronTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_BuildTronTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).BuildTronTransaction(ctx, req.(*ChainRpcBuildTronTransactionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_GetTokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).GetTokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_GetTokenInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).GetTokenInfo(ctx, req.(*GetTokenInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_GetTokenInfoBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenInfoBatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).GetTokenInfoBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_GetTokenInfoBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).GetTokenInfoBatch(ctx, req.(*GetTokenInfoBatchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).HealthCheck(ctx, req.(*HealthCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_GetNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).GetNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_GetNodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).GetNodeStatus(ctx, req.(*GetNodeStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_SwitchNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchNodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).SwitchNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_SwitchNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).SwitchNode(ctx, req.(*SwitchNodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainRPC_TestNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestNodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainRPCServer).TestNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainRPC_TestNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainRPCServer).TestNode(ctx, req.(*TestNodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ChainRPC_ServiceDesc is the grpc.ServiceDesc for ChainRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChainRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chainrpc.ChainRPC",
	HandlerType: (*ChainRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NativeTransfer",
			Handler:    _ChainRPC_NativeTransfer_Handler,
		},
		{
			MethodName: "TokenTransfer",
			Handler:    _ChainRPC_TokenTransfer_Handler,
		},
		{
			MethodName: "BatchTransfer",
			Handler:    _ChainRPC_BatchTransfer_Handler,
		},
		{
			MethodName: "EstimateGas",
			Handler:    _ChainRPC_EstimateGas_Handler,
		},
		{
			MethodName: "GetGasPrice",
			Handler:    _ChainRPC_GetGasPrice_Handler,
		},
		{
			MethodName: "EstimateTronFee",
			Handler:    _ChainRPC_EstimateTronFee_Handler,
		},
		{
			MethodName: "GetTronAccountResources",
			Handler:    _ChainRPC_GetTronAccountResources_Handler,
		},
		{
			MethodName: "BroadcastTransaction",
			Handler:    _ChainRPC_BroadcastTransaction_Handler,
		},
		{
			MethodName: "SpeedUpTransaction",
			Handler:    _ChainRPC_SpeedUpTransaction_Handler,
		},
		{
			MethodName: "CancelTransaction",
			Handler:    _ChainRPC_CancelTransaction_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _ChainRPC_GetBalance_Handler,
		},
		{
			MethodName: "GetTokenBalance",
			Handler:    _ChainRPC_GetTokenBalance_Handler,
		},
		{
			MethodName: "GetMultiBalance",
			Handler:    _ChainRPC_GetMultiBalance_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _ChainRPC_GetTransaction_Handler,
		},
		{
			MethodName: "GetTransactionStatus",
			Handler:    _ChainRPC_GetTransactionStatus_Handler,
		},
		{
			MethodName: "GetTransactionReceipt",
			Handler:    _ChainRPC_GetTransactionReceipt_Handler,
		},
		{
			MethodName: "GetBlockHeight",
			Handler:    _ChainRPC_GetBlockHeight_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _ChainRPC_GetBlock_Handler,
		},
		{
			MethodName: "GetNonce",
			Handler:    _ChainRPC_GetNonce_Handler,
		},
		{
			MethodName: "BuildTransaction",
			Handler:    _ChainRPC_BuildTransaction_Handler,
		},
		{
			MethodName: "BuildTronTransaction",
			Handler:    _ChainRPC_BuildTronTransaction_Handler,
		},
		{
			MethodName: "GetTokenInfo",
			Handler:    _ChainRPC_GetTokenInfo_Handler,
		},
		{
			MethodName: "GetTokenInfoBatch",
			Handler:    _ChainRPC_GetTokenInfoBatch_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ChainRPC_HealthCheck_Handler,
		},
		{
			MethodName: "GetNodeStatus",
			Handler:    _ChainRPC_GetNodeStatus_Handler,
		},
		{
			MethodName: "SwitchNode",
			Handler:    _ChainRPC_SwitchNode_Handler,
		},
		{
			MethodName: "TestNode",
			Handler:    _ChainRPC_TestNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chainrpc.proto",
}
