// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: consolidation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsolidationTaskStatus int32

const (
	ConsolidationTaskStatus_CONSOLIDATION_TASK_STATUS_UNSPECIFIED      ConsolidationTaskStatus = 0
	ConsolidationTaskStatus_CONSOLIDATION_TASK_STATUS_PENDING          ConsolidationTaskStatus = 1
	ConsolidationTaskStatus_CONSOLIDATION_TASK_STATUS_NEED_ENERGY      ConsolidationTaskStatus = 2
	ConsolidationTaskStatus_CONSOLIDATION_TASK_STATUS_IN_PROGRESS      ConsolidationTaskStatus = 3
	ConsolidationTaskStatus_CONSOLIDATION_TASK_STATUS_CONFIRMED        ConsolidationTaskStatus = 4
	ConsolidationTaskStatus_CONSOLIDATION_TASK_STATUS_FAILED           ConsolidationTaskStatus = 5
	ConsolidationTaskStatus_CONSOLIDATION_TASK_STATUS_TIMEOUT          ConsolidationTaskStatus = 6
	ConsolidationTaskStatus_CONSOLIDATION_TASK_STATUS_NEED_GAS         ConsolidationTaskStatus = 7
	ConsolidationTaskStatus_CONSOLIDATION_TASK_STATUS_CANCELLED        ConsolidationTaskStatus = 8
	ConsolidationTaskStatus_CONSOLIDATION_TASK_STATUS_PERMANENT_FAILED ConsolidationTaskStatus = 9
	ConsolidationTaskStatus_CONSOLIDATION_TASK_STATUS_NEED_BANDWIDTH   ConsolidationTaskStatus = 10
)

// Enum value maps for ConsolidationTaskStatus.
var (
	ConsolidationTaskStatus_name = map[int32]string{
		0:  "CONSOLIDATION_TASK_STATUS_UNSPECIFIED",
		1:  "CONSOLIDATION_TASK_STATUS_PENDING",
		2:  "CONSOLIDATION_TASK_STATUS_NEED_ENERGY",
		3:  "CONSOLIDATION_TASK_STATUS_IN_PROGRESS",
		4:  "CONSOLIDATION_TASK_STATUS_CONFIRMED",
		5:  "CONSOLIDATION_TASK_STATUS_FAILED",
		6:  "CONSOLIDATION_TASK_STATUS_TIMEOUT",
		7:  "CONSOLIDATION_TASK_STATUS_NEED_GAS",
		8:  "CONSOLIDATION_TASK_STATUS_CANCELLED",
		9:  "CONSOLIDATION_TASK_STATUS_PERMANENT_FAILED",
		10: "CONSOLIDATION_TASK_STATUS_NEED_BANDWIDTH",
	}
	ConsolidationTaskStatus_value = map[string]int32{
		"CONSOLIDATION_TASK_STATUS_UNSPECIFIED":      0,
		"CONSOLIDATION_TASK_STATUS_PENDING":          1,
		"CONSOLIDATION_TASK_STATUS_NEED_ENERGY":      2,
		"CONSOLIDATION_TASK_STATUS_IN_PROGRESS":      3,
		"CONSOLIDATION_TASK_STATUS_CONFIRMED":        4,
		"CONSOLIDATION_TASK_STATUS_FAILED":           5,
		"CONSOLIDATION_TASK_STATUS_TIMEOUT":          6,
		"CONSOLIDATION_TASK_STATUS_NEED_GAS":         7,
		"CONSOLIDATION_TASK_STATUS_CANCELLED":        8,
		"CONSOLIDATION_TASK_STATUS_PERMANENT_FAILED": 9,
		"CONSOLIDATION_TASK_STATUS_NEED_BANDWIDTH":   10,
	}
)

func (x ConsolidationTaskStatus) Enum() *ConsolidationTaskStatus {
	p := new(ConsolidationTaskStatus)
	*p = x
	return p
}

func (x ConsolidationTaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsolidationTaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_consolidation_proto_enumTypes[0].Descriptor()
}

func (ConsolidationTaskStatus) Type() protoreflect.EnumType {
	return &file_consolidation_proto_enumTypes[0]
}

func (x ConsolidationTaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsolidationTaskStatus.Descriptor instead.
func (ConsolidationTaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{0}
}

type ConsolidationTopupStatus int32

const (
	ConsolidationTopupStatus_CONSOLIDATION_TOPUP_STATUS_UNSPECIFIED ConsolidationTopupStatus = 0
	ConsolidationTopupStatus_CONSOLIDATION_TOPUP_STATUS_PENDING     ConsolidationTopupStatus = 1
	ConsolidationTopupStatus_CONSOLIDATION_TOPUP_STATUS_SENT        ConsolidationTopupStatus = 2
	ConsolidationTopupStatus_CONSOLIDATION_TOPUP_STATUS_CONFIRMED   ConsolidationTopupStatus = 3
	ConsolidationTopupStatus_CONSOLIDATION_TOPUP_STATUS_FAILED      ConsolidationTopupStatus = 4
)

// Enum value maps for ConsolidationTopupStatus.
var (
	ConsolidationTopupStatus_name = map[int32]string{
		0: "CONSOLIDATION_TOPUP_STATUS_UNSPECIFIED",
		1: "CONSOLIDATION_TOPUP_STATUS_PENDING",
		2: "CONSOLIDATION_TOPUP_STATUS_SENT",
		3: "CONSOLIDATION_TOPUP_STATUS_CONFIRMED",
		4: "CONSOLIDATION_TOPUP_STATUS_FAILED",
	}
	ConsolidationTopupStatus_value = map[string]int32{
		"CONSOLIDATION_TOPUP_STATUS_UNSPECIFIED": 0,
		"CONSOLIDATION_TOPUP_STATUS_PENDING":     1,
		"CONSOLIDATION_TOPUP_STATUS_SENT":        2,
		"CONSOLIDATION_TOPUP_STATUS_CONFIRMED":   3,
		"CONSOLIDATION_TOPUP_STATUS_FAILED":      4,
	}
)

func (x ConsolidationTopupStatus) Enum() *ConsolidationTopupStatus {
	p := new(ConsolidationTopupStatus)
	*p = x
	return p
}

func (x ConsolidationTopupStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsolidationTopupStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_consolidation_proto_enumTypes[1].Descriptor()
}

func (ConsolidationTopupStatus) Type() protoreflect.EnumType {
	return &file_consolidation_proto_enumTypes[1]
}

func (x ConsolidationTopupStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsolidationTopupStatus.Descriptor instead.
func (ConsolidationTopupStatus) EnumDescriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{1}
}

type EnergyRentalStatus int32

const (
	EnergyRentalStatus_ENERGY_RENTAL_STATUS_UNSPECIFIED EnergyRentalStatus = 0
	EnergyRentalStatus_ENERGY_RENTAL_STATUS_PENDING     EnergyRentalStatus = 1
	EnergyRentalStatus_ENERGY_RENTAL_STATUS_CONFIRMED   EnergyRentalStatus = 2
	EnergyRentalStatus_ENERGY_RENTAL_STATUS_FAILED      EnergyRentalStatus = 3
	EnergyRentalStatus_ENERGY_RENTAL_STATUS_EXPIRED     EnergyRentalStatus = 4
)

// Enum value maps for EnergyRentalStatus.
var (
	EnergyRentalStatus_name = map[int32]string{
		0: "ENERGY_RENTAL_STATUS_UNSPECIFIED",
		1: "ENERGY_RENTAL_STATUS_PENDING",
		2: "ENERGY_RENTAL_STATUS_CONFIRMED",
		3: "ENERGY_RENTAL_STATUS_FAILED",
		4: "ENERGY_RENTAL_STATUS_EXPIRED",
	}
	EnergyRentalStatus_value = map[string]int32{
		"ENERGY_RENTAL_STATUS_UNSPECIFIED": 0,
		"ENERGY_RENTAL_STATUS_PENDING":     1,
		"ENERGY_RENTAL_STATUS_CONFIRMED":   2,
		"ENERGY_RENTAL_STATUS_FAILED":      3,
		"ENERGY_RENTAL_STATUS_EXPIRED":     4,
	}
)

func (x EnergyRentalStatus) Enum() *EnergyRentalStatus {
	p := new(EnergyRentalStatus)
	*p = x
	return p
}

func (x EnergyRentalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnergyRentalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_consolidation_proto_enumTypes[2].Descriptor()
}

func (EnergyRentalStatus) Type() protoreflect.EnumType {
	return &file_consolidation_proto_enumTypes[2]
}

func (x EnergyRentalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnergyRentalStatus.Descriptor instead.
func (EnergyRentalStatus) EnumDescriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{2}
}

type ConsolidationTask struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	TaskId             string                  `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Chain              string                  `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`                                      // TRON/ETH/BSC
	AssetSymbol        string                  `protobuf:"bytes,3,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`       // TRX/ETH/BNB/USDT/USDC
	TokenContract      string                  `protobuf:"bytes,4,opt,name=token_contract,json=tokenContract,proto3" json:"token_contract,omitempty"` // empty for native
	FromAddress        string                  `protobuf:"bytes,5,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress          string                  `protobuf:"bytes,6,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount             string                  `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"` // smallest unit
	EstimatedFee       string                  `protobuf:"bytes,8,opt,name=estimated_fee,json=estimatedFee,proto3" json:"estimated_fee,omitempty"`
	ActualFee          string                  `protobuf:"bytes,9,opt,name=actual_fee,json=actualFee,proto3" json:"actual_fee,omitempty"`
	Status             ConsolidationTaskStatus `protobuf:"varint,10,opt,name=status,proto3,enum=consolidation.ConsolidationTaskStatus" json:"status,omitempty"`
	TxHash             string                  `protobuf:"bytes,11,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	RetryCount         int32                   `protobuf:"varint,12,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	ErrorMessage       string                  `protobuf:"bytes,13,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt          int64                   `protobuf:"varint,14,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`                  // unix seconds
	ConfirmedAt        int64                   `protobuf:"varint,15,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`            // unix seconds
	CreatedAt          int64                   `protobuf:"varint,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                  // unix seconds
	UpdatedAt          int64                   `protobuf:"varint,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                  // unix seconds
	EnergyRentalId     int64                   `protobuf:"varint,18,opt,name=energy_rental_id,json=energyRentalId,proto3" json:"energy_rental_id,omitempty"` // energy_rental_records.id (0 if none)
	NextAttemptAt      int64                   `protobuf:"varint,19,opt,name=next_attempt_at,json=nextAttemptAt,proto3" json:"next_attempt_at,omitempty"`    // unix seconds
	ClaimedBy          string                  `protobuf:"bytes,20,opt,name=claimed_by,json=claimedBy,proto3" json:"claimed_by,omitempty"`
	ClaimedUntil       int64                   `protobuf:"varint,21,opt,name=claimed_until,json=claimedUntil,proto3" json:"claimed_until,omitempty"` // unix seconds
	EnergyOrderCount   int32                   `protobuf:"varint,22,opt,name=energy_order_count,json=energyOrderCount,proto3" json:"energy_order_count,omitempty"`
	EnergyTotalCostSun int64                   `protobuf:"varint,23,opt,name=energy_total_cost_sun,json=energyTotalCostSun,proto3" json:"energy_total_cost_sun,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConsolidationTask) Reset() {
	*x = ConsolidationTask{}
	mi := &file_consolidation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsolidationTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsolidationTask) ProtoMessage() {}

func (x *ConsolidationTask) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsolidationTask.ProtoReflect.Descriptor instead.
func (*ConsolidationTask) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{0}
}

func (x *ConsolidationTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ConsolidationTask) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *ConsolidationTask) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *ConsolidationTask) GetTokenContract() string {
	if x != nil {
		return x.TokenContract
	}
	return ""
}

func (x *ConsolidationTask) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *ConsolidationTask) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *ConsolidationTask) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ConsolidationTask) GetEstimatedFee() string {
	if x != nil {
		return x.EstimatedFee
	}
	return ""
}

func (x *ConsolidationTask) GetActualFee() string {
	if x != nil {
		return x.ActualFee
	}
	return ""
}

func (x *ConsolidationTask) GetStatus() ConsolidationTaskStatus {
	if x != nil {
		return x.Status
	}
	return ConsolidationTaskStatus_CONSOLIDATION_TASK_STATUS_UNSPECIFIED
}

func (x *ConsolidationTask) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ConsolidationTask) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *ConsolidationTask) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ConsolidationTask) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *ConsolidationTask) GetConfirmedAt() int64 {
	if x != nil {
		return x.ConfirmedAt
	}
	return 0
}

func (x *ConsolidationTask) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ConsolidationTask) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ConsolidationTask) GetEnergyRentalId() int64 {
	if x != nil {
		return x.EnergyRentalId
	}
	return 0
}

func (x *ConsolidationTask) GetNextAttemptAt() int64 {
	if x != nil {
		return x.NextAttemptAt
	}
	return 0
}

func (x *ConsolidationTask) GetClaimedBy() string {
	if x != nil {
		return x.ClaimedBy
	}
	return ""
}

func (x *ConsolidationTask) GetClaimedUntil() int64 {
	if x != nil {
		return x.ClaimedUntil
	}
	return 0
}

func (x *ConsolidationTask) GetEnergyOrderCount() int32 {
	if x != nil {
		return x.EnergyOrderCount
	}
	return 0
}

func (x *ConsolidationTask) GetEnergyTotalCostSun() int64 {
	if x != nil {
		return x.EnergyTotalCostSun
	}
	return 0
}

type TriggerConsolidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`                                // optional: TRON/ETH/BSC; empty=all enabled
	AssetSymbol   string                 `protobuf:"bytes,2,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"` // optional: empty=all configured
	FromAddress   string                 `protobuf:"bytes,3,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"` // optional: empty=all
	DryRun        bool                   `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`               // if true, only returns would-create tasks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerConsolidationRequest) Reset() {
	*x = TriggerConsolidationRequest{}
	mi := &file_consolidation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerConsolidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerConsolidationRequest) ProtoMessage() {}

func (x *TriggerConsolidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerConsolidationRequest.ProtoReflect.Descriptor instead.
func (*TriggerConsolidationRequest) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerConsolidationRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *TriggerConsolidationRequest) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *TriggerConsolidationRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *TriggerConsolidationRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type TriggerConsolidationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TotalCandidates   int64                  `protobuf:"varint,3,opt,name=total_candidates,json=totalCandidates,proto3" json:"total_candidates,omitempty"`
	TotalTasksCreated int64                  `protobuf:"varint,4,opt,name=total_tasks_created,json=totalTasksCreated,proto3" json:"total_tasks_created,omitempty"`
	Tasks             []*ConsolidationTask   `protobuf:"bytes,5,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TriggerConsolidationResponse) Reset() {
	*x = TriggerConsolidationResponse{}
	mi := &file_consolidation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerConsolidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerConsolidationResponse) ProtoMessage() {}

func (x *TriggerConsolidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerConsolidationResponse.ProtoReflect.Descriptor instead.
func (*TriggerConsolidationResponse) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{2}
}

func (x *TriggerConsolidationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerConsolidationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TriggerConsolidationResponse) GetTotalCandidates() int64 {
	if x != nil {
		return x.TotalCandidates
	}
	return 0
}

func (x *TriggerConsolidationResponse) GetTotalTasksCreated() int64 {
	if x != nil {
		return x.TotalTasksCreated
	}
	return 0
}

func (x *TriggerConsolidationResponse) GetTasks() []*ConsolidationTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetConsolidationTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsolidationTaskRequest) Reset() {
	*x = GetConsolidationTaskRequest{}
	mi := &file_consolidation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsolidationTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsolidationTaskRequest) ProtoMessage() {}

func (x *GetConsolidationTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsolidationTaskRequest.ProtoReflect.Descriptor instead.
func (*GetConsolidationTaskRequest) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{3}
}

func (x *GetConsolidationTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetConsolidationTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Task          *ConsolidationTask     `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsolidationTaskResponse) Reset() {
	*x = GetConsolidationTaskResponse{}
	mi := &file_consolidation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsolidationTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsolidationTaskResponse) ProtoMessage() {}

func (x *GetConsolidationTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsolidationTaskResponse.ProtoReflect.Descriptor instead.
func (*GetConsolidationTaskResponse) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{4}
}

func (x *GetConsolidationTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetConsolidationTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetConsolidationTaskResponse) GetTask() *ConsolidationTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListConsolidationTasksRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Page          int32                   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                   `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Chain         string                  `protobuf:"bytes,3,opt,name=chain,proto3" json:"chain,omitempty"`                                               // optional
	AssetSymbol   string                  `protobuf:"bytes,4,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`                // optional
	Status        ConsolidationTaskStatus `protobuf:"varint,5,opt,name=status,proto3,enum=consolidation.ConsolidationTaskStatus" json:"status,omitempty"` // optional
	CreatedAtFrom int64                   `protobuf:"varint,6,opt,name=created_at_from,json=createdAtFrom,proto3" json:"created_at_from,omitempty"`       // optional unix seconds
	CreatedAtTo   int64                   `protobuf:"varint,7,opt,name=created_at_to,json=createdAtTo,proto3" json:"created_at_to,omitempty"`             // optional unix seconds
	TaskId        string                  `protobuf:"bytes,8,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                               // optional
	FromAddress   string                  `protobuf:"bytes,9,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`                // optional
	ToAddress     string                  `protobuf:"bytes,10,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                     // optional
	TxHash        string                  `protobuf:"bytes,11,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                              // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsolidationTasksRequest) Reset() {
	*x = ListConsolidationTasksRequest{}
	mi := &file_consolidation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsolidationTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsolidationTasksRequest) ProtoMessage() {}

func (x *ListConsolidationTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsolidationTasksRequest.ProtoReflect.Descriptor instead.
func (*ListConsolidationTasksRequest) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{5}
}

func (x *ListConsolidationTasksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListConsolidationTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListConsolidationTasksRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *ListConsolidationTasksRequest) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *ListConsolidationTasksRequest) GetStatus() ConsolidationTaskStatus {
	if x != nil {
		return x.Status
	}
	return ConsolidationTaskStatus_CONSOLIDATION_TASK_STATUS_UNSPECIFIED
}

func (x *ListConsolidationTasksRequest) GetCreatedAtFrom() int64 {
	if x != nil {
		return x.CreatedAtFrom
	}
	return 0
}

func (x *ListConsolidationTasksRequest) GetCreatedAtTo() int64 {
	if x != nil {
		return x.CreatedAtTo
	}
	return 0
}

func (x *ListConsolidationTasksRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ListConsolidationTasksRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *ListConsolidationTasksRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *ListConsolidationTasksRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type ListConsolidationTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Tasks         []*ConsolidationTask   `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsolidationTasksResponse) Reset() {
	*x = ListConsolidationTasksResponse{}
	mi := &file_consolidation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsolidationTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsolidationTasksResponse) ProtoMessage() {}

func (x *ListConsolidationTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsolidationTasksResponse.ProtoReflect.Descriptor instead.
func (*ListConsolidationTasksResponse) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{6}
}

func (x *ListConsolidationTasksResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListConsolidationTasksResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListConsolidationTasksResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListConsolidationTasksResponse) GetTasks() []*ConsolidationTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetConsolidationStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`                                // optional
	AssetSymbol   string                 `protobuf:"bytes,2,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"` // optional
	FromTs        int64                  `protobuf:"varint,3,opt,name=from_ts,json=fromTs,proto3" json:"from_ts,omitempty"`               // optional unix seconds
	ToTs          int64                  `protobuf:"varint,4,opt,name=to_ts,json=toTs,proto3" json:"to_ts,omitempty"`                     // optional unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsolidationStatsRequest) Reset() {
	*x = GetConsolidationStatsRequest{}
	mi := &file_consolidation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsolidationStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsolidationStatsRequest) ProtoMessage() {}

func (x *GetConsolidationStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsolidationStatsRequest.ProtoReflect.Descriptor instead.
func (*GetConsolidationStatsRequest) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{7}
}

func (x *GetConsolidationStatsRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *GetConsolidationStatsRequest) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *GetConsolidationStatsRequest) GetFromTs() int64 {
	if x != nil {
		return x.FromTs
	}
	return 0
}

func (x *GetConsolidationStatsRequest) GetToTs() int64 {
	if x != nil {
		return x.ToTs
	}
	return 0
}

type ConsolidationStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Total             int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Confirmed         int64                  `protobuf:"varint,2,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Failed            int64                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	SuccessRate       float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	TotalAmount       string                 `protobuf:"bytes,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`                     // smallest unit (chain/asset specific)
	TotalEstimatedFee string                 `protobuf:"bytes,6,opt,name=total_estimated_fee,json=totalEstimatedFee,proto3" json:"total_estimated_fee,omitempty"` // smallest unit
	TotalActualFee    string                 `protobuf:"bytes,7,opt,name=total_actual_fee,json=totalActualFee,proto3" json:"total_actual_fee,omitempty"`          // smallest unit
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConsolidationStats) Reset() {
	*x = ConsolidationStats{}
	mi := &file_consolidation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsolidationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsolidationStats) ProtoMessage() {}

func (x *ConsolidationStats) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsolidationStats.ProtoReflect.Descriptor instead.
func (*ConsolidationStats) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{8}
}

func (x *ConsolidationStats) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ConsolidationStats) GetConfirmed() int64 {
	if x != nil {
		return x.Confirmed
	}
	return 0
}

func (x *ConsolidationStats) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *ConsolidationStats) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *ConsolidationStats) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *ConsolidationStats) GetTotalEstimatedFee() string {
	if x != nil {
		return x.TotalEstimatedFee
	}
	return ""
}

func (x *ConsolidationStats) GetTotalActualFee() string {
	if x != nil {
		return x.TotalActualFee
	}
	return ""
}

type GetConsolidationStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stats         *ConsolidationStats    `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsolidationStatsResponse) Reset() {
	*x = GetConsolidationStatsResponse{}
	mi := &file_consolidation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsolidationStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsolidationStatsResponse) ProtoMessage() {}

func (x *GetConsolidationStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsolidationStatsResponse.ProtoReflect.Descriptor instead.
func (*GetConsolidationStatsResponse) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{9}
}

func (x *GetConsolidationStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetConsolidationStatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetConsolidationStatsResponse) GetStats() *ConsolidationStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type CancelConsolidationTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelConsolidationTaskRequest) Reset() {
	*x = CancelConsolidationTaskRequest{}
	mi := &file_consolidation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelConsolidationTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelConsolidationTaskRequest) ProtoMessage() {}

func (x *CancelConsolidationTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelConsolidationTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelConsolidationTaskRequest) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{10}
}

func (x *CancelConsolidationTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelConsolidationTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelConsolidationTaskResponse) Reset() {
	*x = CancelConsolidationTaskResponse{}
	mi := &file_consolidation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelConsolidationTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelConsolidationTaskResponse) ProtoMessage() {}

func (x *CancelConsolidationTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelConsolidationTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelConsolidationTaskResponse) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{11}
}

func (x *CancelConsolidationTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelConsolidationTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RetryConsolidationTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryConsolidationTaskRequest) Reset() {
	*x = RetryConsolidationTaskRequest{}
	mi := &file_consolidation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryConsolidationTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryConsolidationTaskRequest) ProtoMessage() {}

func (x *RetryConsolidationTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryConsolidationTaskRequest.ProtoReflect.Descriptor instead.
func (*RetryConsolidationTaskRequest) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{12}
}

func (x *RetryConsolidationTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RetryConsolidationTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryConsolidationTaskResponse) Reset() {
	*x = RetryConsolidationTaskResponse{}
	mi := &file_consolidation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryConsolidationTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryConsolidationTaskResponse) ProtoMessage() {}

func (x *RetryConsolidationTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryConsolidationTaskResponse.ProtoReflect.Descriptor instead.
func (*RetryConsolidationTaskResponse) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{13}
}

func (x *RetryConsolidationTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RetryConsolidationTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConsolidationLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LogLevel      string                 `protobuf:"bytes,3,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"` // INFO/WARN/ERROR
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsolidationLog) Reset() {
	*x = ConsolidationLog{}
	mi := &file_consolidation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsolidationLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsolidationLog) ProtoMessage() {}

func (x *ConsolidationLog) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsolidationLog.ProtoReflect.Descriptor instead.
func (*ConsolidationLog) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{14}
}

func (x *ConsolidationLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConsolidationLog) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ConsolidationLog) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *ConsolidationLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConsolidationLog) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ConsolidationLog) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListConsolidationLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                         // optional
	LogLevel      string                 `protobuf:"bytes,4,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`                   // optional
	CreatedAtFrom int64                  `protobuf:"varint,5,opt,name=created_at_from,json=createdAtFrom,proto3" json:"created_at_from,omitempty"` // optional unix seconds
	CreatedAtTo   int64                  `protobuf:"varint,6,opt,name=created_at_to,json=createdAtTo,proto3" json:"created_at_to,omitempty"`       // optional unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsolidationLogsRequest) Reset() {
	*x = ListConsolidationLogsRequest{}
	mi := &file_consolidation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsolidationLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsolidationLogsRequest) ProtoMessage() {}

func (x *ListConsolidationLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsolidationLogsRequest.ProtoReflect.Descriptor instead.
func (*ListConsolidationLogsRequest) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{15}
}

func (x *ListConsolidationLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListConsolidationLogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListConsolidationLogsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ListConsolidationLogsRequest) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *ListConsolidationLogsRequest) GetCreatedAtFrom() int64 {
	if x != nil {
		return x.CreatedAtFrom
	}
	return 0
}

func (x *ListConsolidationLogsRequest) GetCreatedAtTo() int64 {
	if x != nil {
		return x.CreatedAtTo
	}
	return 0
}

type ListConsolidationLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Logs          []*ConsolidationLog    `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsolidationLogsResponse) Reset() {
	*x = ListConsolidationLogsResponse{}
	mi := &file_consolidation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsolidationLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsolidationLogsResponse) ProtoMessage() {}

func (x *ListConsolidationLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsolidationLogsResponse.ProtoReflect.Descriptor instead.
func (*ListConsolidationLogsResponse) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{16}
}

func (x *ListConsolidationLogsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListConsolidationLogsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListConsolidationLogsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListConsolidationLogsResponse) GetLogs() []*ConsolidationLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type ConsolidationTopupRecord struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            int64                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                   `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Chain         string                   `protobuf:"bytes,3,opt,name=chain,proto3" json:"chain,omitempty"`
	AssetSymbol   string                   `protobuf:"bytes,4,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	FromAddress   string                   `protobuf:"bytes,5,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress     string                   `protobuf:"bytes,6,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount        string                   `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Purpose       string                   `protobuf:"bytes,8,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Status        ConsolidationTopupStatus `protobuf:"varint,9,opt,name=status,proto3,enum=consolidation.ConsolidationTopupStatus" json:"status,omitempty"`
	TxHash        string                   `protobuf:"bytes,10,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	RetryCount    int32                    `protobuf:"varint,11,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	ErrorMessage  string                   `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ConfirmedAt   int64                    `protobuf:"varint,13,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"` // unix seconds
	CreatedAt     int64                    `protobuf:"varint,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`       // unix seconds
	UpdatedAt     int64                    `protobuf:"varint,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`       // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsolidationTopupRecord) Reset() {
	*x = ConsolidationTopupRecord{}
	mi := &file_consolidation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsolidationTopupRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsolidationTopupRecord) ProtoMessage() {}

func (x *ConsolidationTopupRecord) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsolidationTopupRecord.ProtoReflect.Descriptor instead.
func (*ConsolidationTopupRecord) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{17}
}

func (x *ConsolidationTopupRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConsolidationTopupRecord) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ConsolidationTopupRecord) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *ConsolidationTopupRecord) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *ConsolidationTopupRecord) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *ConsolidationTopupRecord) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *ConsolidationTopupRecord) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ConsolidationTopupRecord) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *ConsolidationTopupRecord) GetStatus() ConsolidationTopupStatus {
	if x != nil {
		return x.Status
	}
	return ConsolidationTopupStatus_CONSOLIDATION_TOPUP_STATUS_UNSPECIFIED
}

func (x *ConsolidationTopupRecord) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ConsolidationTopupRecord) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *ConsolidationTopupRecord) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ConsolidationTopupRecord) GetConfirmedAt() int64 {
	if x != nil {
		return x.ConfirmedAt
	}
	return 0
}

func (x *ConsolidationTopupRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ConsolidationTopupRecord) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListConsolidationTopupRecordsRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Page          int32                    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TaskId        string                   `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                // optional
	Chain         string                   `protobuf:"bytes,4,opt,name=chain,proto3" json:"chain,omitempty"`                                                // optional
	AssetSymbol   string                   `protobuf:"bytes,5,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`                 // optional
	Purpose       string                   `protobuf:"bytes,6,opt,name=purpose,proto3" json:"purpose,omitempty"`                                            // optional
	Status        ConsolidationTopupStatus `protobuf:"varint,7,opt,name=status,proto3,enum=consolidation.ConsolidationTopupStatus" json:"status,omitempty"` // optional
	ToAddress     string                   `protobuf:"bytes,8,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                       // optional
	TxHash        string                   `protobuf:"bytes,9,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`                                // optional
	CreatedAtFrom int64                    `protobuf:"varint,10,opt,name=created_at_from,json=createdAtFrom,proto3" json:"created_at_from,omitempty"`       // optional unix seconds
	CreatedAtTo   int64                    `protobuf:"varint,11,opt,name=created_at_to,json=createdAtTo,proto3" json:"created_at_to,omitempty"`             // optional unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsolidationTopupRecordsRequest) Reset() {
	*x = ListConsolidationTopupRecordsRequest{}
	mi := &file_consolidation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsolidationTopupRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsolidationTopupRecordsRequest) ProtoMessage() {}

func (x *ListConsolidationTopupRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsolidationTopupRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListConsolidationTopupRecordsRequest) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{18}
}

func (x *ListConsolidationTopupRecordsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListConsolidationTopupRecordsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListConsolidationTopupRecordsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ListConsolidationTopupRecordsRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *ListConsolidationTopupRecordsRequest) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *ListConsolidationTopupRecordsRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *ListConsolidationTopupRecordsRequest) GetStatus() ConsolidationTopupStatus {
	if x != nil {
		return x.Status
	}
	return ConsolidationTopupStatus_CONSOLIDATION_TOPUP_STATUS_UNSPECIFIED
}

func (x *ListConsolidationTopupRecordsRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *ListConsolidationTopupRecordsRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ListConsolidationTopupRecordsRequest) GetCreatedAtFrom() int64 {
	if x != nil {
		return x.CreatedAtFrom
	}
	return 0
}

func (x *ListConsolidationTopupRecordsRequest) GetCreatedAtTo() int64 {
	if x != nil {
		return x.CreatedAtTo
	}
	return 0
}

type ListConsolidationTopupRecordsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Success       bool                        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Total         int64                       `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Records       []*ConsolidationTopupRecord `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsolidationTopupRecordsResponse) Reset() {
	*x = ListConsolidationTopupRecordsResponse{}
	mi := &file_consolidation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsolidationTopupRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsolidationTopupRecordsResponse) ProtoMessage() {}

func (x *ListConsolidationTopupRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsolidationTopupRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListConsolidationTopupRecordsResponse) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{19}
}

func (x *ListConsolidationTopupRecordsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListConsolidationTopupRecordsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListConsolidationTopupRecordsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListConsolidationTopupRecordsResponse) GetRecords() []*ConsolidationTopupRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type EnergyRentalRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId          string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ReceiverAddress  string                 `protobuf:"bytes,3,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`
	EnergyAmount     int64                  `protobuf:"varint,4,opt,name=energy_amount,json=energyAmount,proto3" json:"energy_amount,omitempty"`
	RentalDuration   int32                  `protobuf:"varint,5,opt,name=rental_duration,json=rentalDuration,proto3" json:"rental_duration,omitempty"`
	PricePerEnergy   string                 `protobuf:"bytes,6,opt,name=price_per_energy,json=pricePerEnergy,proto3" json:"price_per_energy,omitempty"`
	TotalCost        string                 `protobuf:"bytes,7,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	Provider         string                 `protobuf:"bytes,8,opt,name=provider,proto3" json:"provider,omitempty"`
	Status           EnergyRentalStatus     `protobuf:"varint,9,opt,name=status,proto3,enum=consolidation.EnergyRentalStatus" json:"status,omitempty"`
	ProviderResponse *structpb.Struct       `protobuf:"bytes,10,opt,name=provider_response,json=providerResponse,proto3" json:"provider_response,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ConfirmedAt      int64                  `protobuf:"varint,12,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"` // unix seconds
	CreatedAt        int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`       // unix seconds
	UpdatedAt        int64                  `protobuf:"varint,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`       // unix seconds
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnergyRentalRecord) Reset() {
	*x = EnergyRentalRecord{}
	mi := &file_consolidation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnergyRentalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnergyRentalRecord) ProtoMessage() {}

func (x *EnergyRentalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnergyRentalRecord.ProtoReflect.Descriptor instead.
func (*EnergyRentalRecord) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{20}
}

func (x *EnergyRentalRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnergyRentalRecord) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *EnergyRentalRecord) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *EnergyRentalRecord) GetEnergyAmount() int64 {
	if x != nil {
		return x.EnergyAmount
	}
	return 0
}

func (x *EnergyRentalRecord) GetRentalDuration() int32 {
	if x != nil {
		return x.RentalDuration
	}
	return 0
}

func (x *EnergyRentalRecord) GetPricePerEnergy() string {
	if x != nil {
		return x.PricePerEnergy
	}
	return ""
}

func (x *EnergyRentalRecord) GetTotalCost() string {
	if x != nil {
		return x.TotalCost
	}
	return ""
}

func (x *EnergyRentalRecord) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *EnergyRentalRecord) GetStatus() EnergyRentalStatus {
	if x != nil {
		return x.Status
	}
	return EnergyRentalStatus_ENERGY_RENTAL_STATUS_UNSPECIFIED
}

func (x *EnergyRentalRecord) GetProviderResponse() *structpb.Struct {
	if x != nil {
		return x.ProviderResponse
	}
	return nil
}

func (x *EnergyRentalRecord) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *EnergyRentalRecord) GetConfirmedAt() int64 {
	if x != nil {
		return x.ConfirmedAt
	}
	return 0
}

func (x *EnergyRentalRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *EnergyRentalRecord) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ListEnergyRentalRecordsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Page            int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize        int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ReceiverAddress string                 `protobuf:"bytes,3,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"` // optional
	Provider        string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`                                      // optional
	Status          EnergyRentalStatus     `protobuf:"varint,5,opt,name=status,proto3,enum=consolidation.EnergyRentalStatus" json:"status,omitempty"`   // optional
	OrderId         string                 `protobuf:"bytes,6,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                         // optional
	CreatedAtFrom   int64                  `protobuf:"varint,7,opt,name=created_at_from,json=createdAtFrom,proto3" json:"created_at_from,omitempty"`    // optional unix seconds
	CreatedAtTo     int64                  `protobuf:"varint,8,opt,name=created_at_to,json=createdAtTo,proto3" json:"created_at_to,omitempty"`          // optional unix seconds
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListEnergyRentalRecordsRequest) Reset() {
	*x = ListEnergyRentalRecordsRequest{}
	mi := &file_consolidation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnergyRentalRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnergyRentalRecordsRequest) ProtoMessage() {}

func (x *ListEnergyRentalRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnergyRentalRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListEnergyRentalRecordsRequest) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{21}
}

func (x *ListEnergyRentalRecordsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEnergyRentalRecordsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEnergyRentalRecordsRequest) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *ListEnergyRentalRecordsRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ListEnergyRentalRecordsRequest) GetStatus() EnergyRentalStatus {
	if x != nil {
		return x.Status
	}
	return EnergyRentalStatus_ENERGY_RENTAL_STATUS_UNSPECIFIED
}

func (x *ListEnergyRentalRecordsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ListEnergyRentalRecordsRequest) GetCreatedAtFrom() int64 {
	if x != nil {
		return x.CreatedAtFrom
	}
	return 0
}

func (x *ListEnergyRentalRecordsRequest) GetCreatedAtTo() int64 {
	if x != nil {
		return x.CreatedAtTo
	}
	return 0
}

type ListEnergyRentalRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Records       []*EnergyRentalRecord  `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnergyRentalRecordsResponse) Reset() {
	*x = ListEnergyRentalRecordsResponse{}
	mi := &file_consolidation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnergyRentalRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnergyRentalRecordsResponse) ProtoMessage() {}

func (x *ListEnergyRentalRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnergyRentalRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListEnergyRentalRecordsResponse) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{22}
}

func (x *ListEnergyRentalRecordsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListEnergyRentalRecordsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListEnergyRentalRecordsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListEnergyRentalRecordsResponse) GetRecords() []*EnergyRentalRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type GetEnergyRentalRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnergyRentalRecordRequest) Reset() {
	*x = GetEnergyRentalRecordRequest{}
	mi := &file_consolidation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnergyRentalRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnergyRentalRecordRequest) ProtoMessage() {}

func (x *GetEnergyRentalRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnergyRentalRecordRequest.ProtoReflect.Descriptor instead.
func (*GetEnergyRentalRecordRequest) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{23}
}

func (x *GetEnergyRentalRecordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEnergyRentalRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Record        *EnergyRentalRecord    `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnergyRentalRecordResponse) Reset() {
	*x = GetEnergyRentalRecordResponse{}
	mi := &file_consolidation_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnergyRentalRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnergyRentalRecordResponse) ProtoMessage() {}

func (x *GetEnergyRentalRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consolidation_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnergyRentalRecordResponse.ProtoReflect.Descriptor instead.
func (*GetEnergyRentalRecordResponse) Descriptor() ([]byte, []int) {
	return file_consolidation_proto_rawDescGZIP(), []int{24}
}

func (x *GetEnergyRentalRecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetEnergyRentalRecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetEnergyRentalRecordResponse) GetRecord() *EnergyRentalRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

var File_consolidation_proto protoreflect.FileDescriptor

const file_consolidation_proto_rawDesc = "" +
	"\n" +
	"\x13consolidation.proto\x12\rconsolidation\x1a\x1cgoogle/protobuf/struct.proto\"\xc0\x06\n" +
	"\x11ConsolidationTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12!\n" +
	"\fasset_symbol\x18\x03 \x01(\tR\vassetSymbol\x12%\n" +
	"\x0etoken_contract\x18\x04 \x01(\tR\rtokenContract\x12!\n" +
	"\ffrom_address\x18\x05 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x06 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\a \x01(\tR\x06amount\x12#\n" +
	"\restimated_fee\x18\b \x01(\tR\festimatedFee\x12\x1d\n" +
	"\n" +
	"actual_fee\x18\t \x01(\tR\tactualFee\x12>\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2&.consolidation.ConsolidationTaskStatusR\x06status\x12\x17\n" +
	"\atx_hash\x18\v \x01(\tR\x06txHash\x12\x1f\n" +
	"\vretry_count\x18\f \x01(\x05R\n" +
	"retryCount\x12#\n" +
	"\rerror_message\x18\r \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"started_at\x18\x0e \x01(\x03R\tstartedAt\x12!\n" +
	"\fconfirmed_at\x18\x0f \x01(\x03R\vconfirmedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\x03R\tupdatedAt\x12(\n" +
	"\x10energy_rental_id\x18\x12 \x01(\x03R\x0eenergyRentalId\x12&\n" +
	"\x0fnext_attempt_at\x18\x13 \x01(\x03R\rnextAttemptAt\x12\x1d\n" +
	"\n" +
	"claimed_by\x18\x14 \x01(\tR\tclaimedBy\x12#\n" +
	"\rclaimed_until\x18\x15 \x01(\x03R\fclaimedUntil\x12,\n" +
	"\x12energy_order_count\x18\x16 \x01(\x05R\x10energyOrderCount\x121\n" +
	"\x15energy_total_cost_sun\x18\x17 \x01(\x03R\x12energyTotalCostSun\"\x92\x01\n" +
	"\x1bTriggerConsolidationRequest\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12!\n" +
	"\fasset_symbol\x18\x02 \x01(\tR\vassetSymbol\x12!\n" +
	"\ffrom_address\x18\x03 \x01(\tR\vfromAddress\x12\x17\n" +
	"\adry_run\x18\x04 \x01(\bR\x06dryRun\"\xe5\x01\n" +
	"\x1cTriggerConsolidationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10total_candidates\x18\x03 \x01(\x03R\x0ftotalCandidates\x12.\n" +
	"\x13total_tasks_created\x18\x04 \x01(\x03R\x11totalTasksCreated\x126\n" +
	"\x05tasks\x18\x05 \x03(\v2 .consolidation.ConsolidationTaskR\x05tasks\"6\n" +
	"\x1bGetConsolidationTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x88\x01\n" +
	"\x1cGetConsolidationTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x04task\x18\x03 \x01(\v2 .consolidation.ConsolidationTaskR\x04task\"\x89\x03\n" +
	"\x1dListConsolidationTasksRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05chain\x18\x03 \x01(\tR\x05chain\x12!\n" +
	"\fasset_symbol\x18\x04 \x01(\tR\vassetSymbol\x12>\n" +
	"\x06status\x18\x05 \x01(\x0e2&.consolidation.ConsolidationTaskStatusR\x06status\x12&\n" +
	"\x0fcreated_at_from\x18\x06 \x01(\x03R\rcreatedAtFrom\x12\"\n" +
	"\rcreated_at_to\x18\a \x01(\x03R\vcreatedAtTo\x12\x17\n" +
	"\atask_id\x18\b \x01(\tR\x06taskId\x12!\n" +
	"\ffrom_address\x18\t \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\n" +
	" \x01(\tR\ttoAddress\x12\x17\n" +
	"\atx_hash\x18\v \x01(\tR\x06txHash\"\xa2\x01\n" +
	"\x1eListConsolidationTasksResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x126\n" +
	"\x05tasks\x18\x04 \x03(\v2 .consolidation.ConsolidationTaskR\x05tasks\"\x85\x01\n" +
	"\x1cGetConsolidationStatsRequest\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12!\n" +
	"\fasset_symbol\x18\x02 \x01(\tR\vassetSymbol\x12\x17\n" +
	"\afrom_ts\x18\x03 \x01(\x03R\x06fromTs\x12\x13\n" +
	"\x05to_ts\x18\x04 \x01(\x03R\x04toTs\"\x80\x02\n" +
	"\x12ConsolidationStats\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1c\n" +
	"\tconfirmed\x18\x02 \x01(\x03R\tconfirmed\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x03R\x06failed\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\tR\vtotalAmount\x12.\n" +
	"\x13total_estimated_fee\x18\x06 \x01(\tR\x11totalEstimatedFee\x12(\n" +
	"\x10total_actual_fee\x18\a \x01(\tR\x0etotalActualFee\"\x8c\x01\n" +
	"\x1dGetConsolidationStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x05stats\x18\x03 \x01(\v2!.consolidation.ConsolidationStatsR\x05stats\"9\n" +
	"\x1eCancelConsolidationTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"U\n" +
	"\x1fCancelConsolidationTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"8\n" +
	"\x1dRetryConsolidationTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"T\n" +
	"\x1eRetryConsolidationTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc4\x01\n" +
	"\x10ConsolidationLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tlog_level\x18\x03 \x01(\tR\blogLevel\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x121\n" +
	"\adetails\x18\x05 \x01(\v2\x17.google.protobuf.StructR\adetails\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\xd1\x01\n" +
	"\x1cListConsolidationLogsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tlog_level\x18\x04 \x01(\tR\blogLevel\x12&\n" +
	"\x0fcreated_at_from\x18\x05 \x01(\x03R\rcreatedAtFrom\x12\"\n" +
	"\rcreated_at_to\x18\x06 \x01(\x03R\vcreatedAtTo\"\x9e\x01\n" +
	"\x1dListConsolidationLogsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x123\n" +
	"\x04logs\x18\x04 \x03(\v2\x1f.consolidation.ConsolidationLogR\x04logs\"\xf1\x03\n" +
	"\x18ConsolidationTopupRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05chain\x18\x03 \x01(\tR\x05chain\x12!\n" +
	"\fasset_symbol\x18\x04 \x01(\tR\vassetSymbol\x12!\n" +
	"\ffrom_address\x18\x05 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x06 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\a \x01(\tR\x06amount\x12\x18\n" +
	"\apurpose\x18\b \x01(\tR\apurpose\x12?\n" +
	"\x06status\x18\t \x01(\x0e2'.consolidation.ConsolidationTopupStatusR\x06status\x12\x17\n" +
	"\atx_hash\x18\n" +
	" \x01(\tR\x06txHash\x12\x1f\n" +
	"\vretry_count\x18\v \x01(\x05R\n" +
	"retryCount\x12#\n" +
	"\rerror_message\x18\f \x01(\tR\ferrorMessage\x12!\n" +
	"\fconfirmed_at\x18\r \x01(\x03R\vconfirmedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\x03R\tupdatedAt\"\x88\x03\n" +
	"$ListConsolidationTopupRecordsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05chain\x18\x04 \x01(\tR\x05chain\x12!\n" +
	"\fasset_symbol\x18\x05 \x01(\tR\vassetSymbol\x12\x18\n" +
	"\apurpose\x18\x06 \x01(\tR\apurpose\x12?\n" +
	"\x06status\x18\a \x01(\x0e2'.consolidation.ConsolidationTopupStatusR\x06status\x12\x1d\n" +
	"\n" +
	"to_address\x18\b \x01(\tR\ttoAddress\x12\x17\n" +
	"\atx_hash\x18\t \x01(\tR\x06txHash\x12&\n" +
	"\x0fcreated_at_from\x18\n" +
	" \x01(\x03R\rcreatedAtFrom\x12\"\n" +
	"\rcreated_at_to\x18\v \x01(\x03R\vcreatedAtTo\"\xb4\x01\n" +
	"%ListConsolidationTopupRecordsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12A\n" +
	"\arecords\x18\x04 \x03(\v2'.consolidation.ConsolidationTopupRecordR\arecords\"\xa4\x04\n" +
	"\x12EnergyRentalRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12)\n" +
	"\x10receiver_address\x18\x03 \x01(\tR\x0freceiverAddress\x12#\n" +
	"\renergy_amount\x18\x04 \x01(\x03R\fenergyAmount\x12'\n" +
	"\x0frental_duration\x18\x05 \x01(\x05R\x0erentalDuration\x12(\n" +
	"\x10price_per_energy\x18\x06 \x01(\tR\x0epricePerEnergy\x12\x1d\n" +
	"\n" +
	"total_cost\x18\a \x01(\tR\ttotalCost\x12\x1a\n" +
	"\bprovider\x18\b \x01(\tR\bprovider\x129\n" +
	"\x06status\x18\t \x01(\x0e2!.consolidation.EnergyRentalStatusR\x06status\x12D\n" +
	"\x11provider_response\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\x10providerResponse\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x12!\n" +
	"\fconfirmed_at\x18\f \x01(\x03R\vconfirmedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\x03R\tupdatedAt\"\xba\x02\n" +
	"\x1eListEnergyRentalRecordsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12)\n" +
	"\x10receiver_address\x18\x03 \x01(\tR\x0freceiverAddress\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x129\n" +
	"\x06status\x18\x05 \x01(\x0e2!.consolidation.EnergyRentalStatusR\x06status\x12\x19\n" +
	"\border_id\x18\x06 \x01(\tR\aorderId\x12&\n" +
	"\x0fcreated_at_from\x18\a \x01(\x03R\rcreatedAtFrom\x12\"\n" +
	"\rcreated_at_to\x18\b \x01(\x03R\vcreatedAtTo\"\xa8\x01\n" +
	"\x1fListEnergyRentalRecordsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12;\n" +
	"\arecords\x18\x04 \x03(\v2!.consolidation.EnergyRentalRecordR\arecords\".\n" +
	"\x1cGetEnergyRentalRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8e\x01\n" +
	"\x1dGetEnergyRentalRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x06record\x18\x03 \x01(\v2!.consolidation.EnergyRentalRecordR\x06record*\xe6\x03\n" +
	"\x17ConsolidationTaskStatus\x12)\n" +
	"%CONSOLIDATION_TASK_STATUS_UNSPECIFIED\x10\x00\x12%\n" +
	"!CONSOLIDATION_TASK_STATUS_PENDING\x10\x01\x12)\n" +
	"%CONSOLIDATION_TASK_STATUS_NEED_ENERGY\x10\x02\x12)\n" +
	"%CONSOLIDATION_TASK_STATUS_IN_PROGRESS\x10\x03\x12'\n" +
	"#CONSOLIDATION_TASK_STATUS_CONFIRMED\x10\x04\x12$\n" +
	" CONSOLIDATION_TASK_STATUS_FAILED\x10\x05\x12%\n" +
	"!CONSOLIDATION_TASK_STATUS_TIMEOUT\x10\x06\x12&\n" +
	"\"CONSOLIDATION_TASK_STATUS_NEED_GAS\x10\a\x12'\n" +
	"#CONSOLIDATION_TASK_STATUS_CANCELLED\x10\b\x12.\n" +
	"*CONSOLIDATION_TASK_STATUS_PERMANENT_FAILED\x10\t\x12,\n" +
	"(CONSOLIDATION_TASK_STATUS_NEED_BANDWIDTH\x10\n" +
	"*\xe4\x01\n" +
	"\x18ConsolidationTopupStatus\x12*\n" +
	"&CONSOLIDATION_TOPUP_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"CONSOLIDATION_TOPUP_STATUS_PENDING\x10\x01\x12#\n" +
	"\x1fCONSOLIDATION_TOPUP_STATUS_SENT\x10\x02\x12(\n" +
	"$CONSOLIDATION_TOPUP_STATUS_CONFIRMED\x10\x03\x12%\n" +
	"!CONSOLIDATION_TOPUP_STATUS_FAILED\x10\x04*\xc3\x01\n" +
	"\x12EnergyRentalStatus\x12$\n" +
	" ENERGY_RENTAL_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cENERGY_RENTAL_STATUS_PENDING\x10\x01\x12\"\n" +
	"\x1eENERGY_RENTAL_STATUS_CONFIRMED\x10\x02\x12\x1f\n" +
	"\x1bENERGY_RENTAL_STATUS_FAILED\x10\x03\x12 \n" +
	"\x1cENERGY_RENTAL_STATUS_EXPIRED\x10\x042\xbc\t\n" +
	"\rConsolidation\x12o\n" +
	"\x14TriggerConsolidation\x12*.consolidation.TriggerConsolidationRequest\x1a+.consolidation.TriggerConsolidationResponse\x12o\n" +
	"\x14GetConsolidationTask\x12*.consolidation.GetConsolidationTaskRequest\x1a+.consolidation.GetConsolidationTaskResponse\x12u\n" +
	"\x16ListConsolidationTasks\x12,.consolidation.ListConsolidationTasksRequest\x1a-.consolidation.ListConsolidationTasksResponse\x12r\n" +
	"\x15GetConsolidationStats\x12+.consolidation.GetConsolidationStatsRequest\x1a,.consolidation.GetConsolidationStatsResponse\x12x\n" +
	"\x17CancelConsolidationTask\x12-.consolidation.CancelConsolidationTaskRequest\x1a..consolidation.CancelConsolidationTaskResponse\x12u\n" +
	"\x16RetryConsolidationTask\x12,.consolidation.RetryConsolidationTaskRequest\x1a-.consolidation.RetryConsolidationTaskResponse\x12r\n" +
	"\x15ListConsolidationLogs\x12+.consolidation.ListConsolidationLogsRequest\x1a,.consolidation.ListConsolidationLogsResponse\x12\x8a\x01\n" +
	"\x1dListConsolidationTopupRecords\x123.consolidation.ListConsolidationTopupRecordsRequest\x1a4.consolidation.ListConsolidationTopupRecordsResponse\x12x\n" +
	"\x17ListEnergyRentalRecords\x12-.consolidation.ListEnergyRentalRecordsRequest\x1a..consolidation.ListEnergyRentalRecordsResponse\x12r\n" +
	"\x15GetEnergyRentalRecord\x12+.consolidation.GetEnergyRentalRecordRequest\x1a,.consolidation.GetEnergyRentalRecordResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_consolidation_proto_rawDescOnce sync.Once
	file_consolidation_proto_rawDescData []byte
)

func file_consolidation_proto_rawDescGZIP() []byte {
	file_consolidation_proto_rawDescOnce.Do(func() {
		file_consolidation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consolidation_proto_rawDesc), len(file_consolidation_proto_rawDesc)))
	})
	return file_consolidation_proto_rawDescData
}

var file_consolidation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_consolidation_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_consolidation_proto_goTypes = []any{
	(ConsolidationTaskStatus)(0),                  // 0: consolidation.ConsolidationTaskStatus
	(ConsolidationTopupStatus)(0),                 // 1: consolidation.ConsolidationTopupStatus
	(EnergyRentalStatus)(0),                       // 2: consolidation.EnergyRentalStatus
	(*ConsolidationTask)(nil),                     // 3: consolidation.ConsolidationTask
	(*TriggerConsolidationRequest)(nil),           // 4: consolidation.TriggerConsolidationRequest
	(*TriggerConsolidationResponse)(nil),          // 5: consolidation.TriggerConsolidationResponse
	(*GetConsolidationTaskRequest)(nil),           // 6: consolidation.GetConsolidationTaskRequest
	(*GetConsolidationTaskResponse)(nil),          // 7: consolidation.GetConsolidationTaskResponse
	(*ListConsolidationTasksRequest)(nil),         // 8: consolidation.ListConsolidationTasksRequest
	(*ListConsolidationTasksResponse)(nil),        // 9: consolidation.ListConsolidationTasksResponse
	(*GetConsolidationStatsRequest)(nil),          // 10: consolidation.GetConsolidationStatsRequest
	(*ConsolidationStats)(nil),                    // 11: consolidation.ConsolidationStats
	(*GetConsolidationStatsResponse)(nil),         // 12: consolidation.GetConsolidationStatsResponse
	(*CancelConsolidationTaskRequest)(nil),        // 13: consolidation.CancelConsolidationTaskRequest
	(*CancelConsolidationTaskResponse)(nil),       // 14: consolidation.CancelConsolidationTaskResponse
	(*RetryConsolidationTaskRequest)(nil),         // 15: consolidation.RetryConsolidationTaskRequest
	(*RetryConsolidationTaskResponse)(nil),        // 16: consolidation.RetryConsolidationTaskResponse
	(*ConsolidationLog)(nil),                      // 17: consolidation.ConsolidationLog
	(*ListConsolidationLogsRequest)(nil),          // 18: consolidation.ListConsolidationLogsRequest
	(*ListConsolidationLogsResponse)(nil),         // 19: consolidation.ListConsolidationLogsResponse
	(*ConsolidationTopupRecord)(nil),              // 20: consolidation.ConsolidationTopupRecord
	(*ListConsolidationTopupRecordsRequest)(nil),  // 21: consolidation.ListConsolidationTopupRecordsRequest
	(*ListConsolidationTopupRecordsResponse)(nil), // 22: consolidation.ListConsolidationTopupRecordsResponse
	(*EnergyRentalRecord)(nil),                    // 23: consolidation.EnergyRentalRecord
	(*ListEnergyRentalRecordsRequest)(nil),        // 24: consolidation.ListEnergyRentalRecordsRequest
	(*ListEnergyRentalRecordsResponse)(nil),       // 25: consolidation.ListEnergyRentalRecordsResponse
	(*GetEnergyRentalRecordRequest)(nil),          // 26: consolidation.GetEnergyRentalRecordRequest
	(*GetEnergyRentalRecordResponse)(nil),         // 27: consolidation.GetEnergyRentalRecordResponse
	(*structpb.Struct)(nil),                       // 28: google.protobuf.Struct
}
var file_consolidation_proto_depIdxs = []int32{
	0,  // 0: consolidation.ConsolidationTask.status:type_name -> consolidation.ConsolidationTaskStatus
	3,  // 1: consolidation.TriggerConsolidationResponse.tasks:type_name -> consolidation.ConsolidationTask
	3,  // 2: consolidation.GetConsolidationTaskResponse.task:type_name -> consolidation.ConsolidationTask
	0,  // 3: consolidation.ListConsolidationTasksRequest.status:type_name -> consolidation.ConsolidationTaskStatus
	3,  // 4: consolidation.ListConsolidationTasksResponse.tasks:type_name -> consolidation.ConsolidationTask
	11, // 5: consolidation.GetConsolidationStatsResponse.stats:type_name -> consolidation.ConsolidationStats
	28, // 6: consolidation.ConsolidationLog.details:type_name -> google.protobuf.Struct
	17, // 7: consolidation.ListConsolidationLogsResponse.logs:type_name -> consolidation.ConsolidationLog
	1,  // 8: consolidation.ConsolidationTopupRecord.status:type_name -> consolidation.ConsolidationTopupStatus
	1,  // 9: consolidation.ListConsolidationTopupRecordsRequest.status:type_name -> consolidation.ConsolidationTopupStatus
	20, // 10: consolidation.ListConsolidationTopupRecordsResponse.records:type_name -> consolidation.ConsolidationTopupRecord
	2,  // 11: consolidation.EnergyRentalRecord.status:type_name -> consolidation.EnergyRentalStatus
	28, // 12: consolidation.EnergyRentalRecord.provider_response:type_name -> google.protobuf.Struct
	2,  // 13: consolidation.ListEnergyRentalRecordsRequest.status:type_name -> consolidation.EnergyRentalStatus
	23, // 14: consolidation.ListEnergyRentalRecordsResponse.records:type_name -> consolidation.EnergyRentalRecord
	23, // 15: consolidation.GetEnergyRentalRecordResponse.record:type_name -> consolidation.EnergyRentalRecord
	4,  // 16: consolidation.Consolidation.TriggerConsolidation:input_type -> consolidation.TriggerConsolidationRequest
	6,  // 17: consolidation.Consolidation.GetConsolidationTask:input_type -> consolidation.GetConsolidationTaskRequest
	8,  // 18: consolidation.Consolidation.ListConsolidationTasks:input_type -> consolidation.ListConsolidationTasksRequest
	10, // 19: consolidation.Consolidation.GetConsolidationStats:input_type -> consolidation.GetConsolidationStatsRequest
	13, // 20: consolidation.Consolidation.CancelConsolidationTask:input_type -> consolidation.CancelConsolidationTaskRequest
	15, // 21: consolidation.Consolidation.RetryConsolidationTask:input_type -> consolidation.RetryConsolidationTaskRequest
	18, // 22: consolidation.Consolidation.ListConsolidationLogs:input_type -> consolidation.ListConsolidationLogsRequest
	21, // 23: consolidation.Consolidation.ListConsolidationTopupRecords:input_type -> consolidation.ListConsolidationTopupRecordsRequest
	24, // 24: consolidation.Consolidation.ListEnergyRentalRecords:input_type -> consolidation.ListEnergyRentalRecordsRequest
	26, // 25: consolidation.Consolidation.GetEnergyRentalRecord:input_type -> consolidation.GetEnergyRentalRecordRequest
	5,  // 26: consolidation.Consolidation.TriggerConsolidation:output_type -> consolidation.TriggerConsolidationResponse
	7,  // 27: consolidation.Consolidation.GetConsolidationTask:output_type -> consolidation.GetConsolidationTaskResponse
	9,  // 28: consolidation.Consolidation.ListConsolidationTasks:output_type -> consolidation.ListConsolidationTasksResponse
	12, // 29: consolidation.Consolidation.GetConsolidationStats:output_type -> consolidation.GetConsolidationStatsResponse
	14, // 30: consolidation.Consolidation.CancelConsolidationTask:output_type -> consolidation.CancelConsolidationTaskResponse
	16, // 31: consolidation.Consolidation.RetryConsolidationTask:output_type -> consolidation.RetryConsolidationTaskResponse
	19, // 32: consolidation.Consolidation.ListConsolidationLogs:output_type -> consolidation.ListConsolidationLogsResponse
	22, // 33: consolidation.Consolidation.ListConsolidationTopupRecords:output_type -> consolidation.ListConsolidationTopupRecordsResponse
	25, // 34: consolidation.Consolidation.ListEnergyRentalRecords:output_type -> consolidation.ListEnergyRentalRecordsResponse
	27, // 35: consolidation.Consolidation.GetEnergyRentalRecord:output_type -> consolidation.GetEnergyRentalRecordResponse
	26, // [26:36] is the sub-list for method output_type
	16, // [16:26] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_consolidation_proto_init() }
func file_consolidation_proto_init() {
	if File_consolidation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consolidation_proto_rawDesc), len(file_consolidation_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_consolidation_proto_goTypes,
		DependencyIndexes: file_consolidation_proto_depIdxs,
		EnumInfos:         file_consolidation_proto_enumTypes,
		MessageInfos:      file_consolidation_proto_msgTypes,
	}.Build()
	File_consolidation_proto = out.File
	file_consolidation_proto_goTypes = nil
	file_consolidation_proto_depIdxs = nil
}
