// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: accounting.proto

package accounting

import (
	"context"

	"internalwallet/proto/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AcctAccountType                         = pb.AcctAccountType
	AcctAccountTypeResponse                 = pb.AcctAccountTypeResponse
	AcctAsset                               = pb.AcctAsset
	AcctAssetOverviewResponse               = pb.AcctAssetOverviewResponse
	AcctAssetResponse                       = pb.AcctAssetResponse
	AdminAdjustRequest                      = pb.AdminAdjustRequest
	ConfirmDepositRequest                   = pb.ConfirmDepositRequest
	CreateAccountTypeRequest                = pb.CreateAccountTypeRequest
	CreateAssetRequest                      = pb.CreateAssetRequest
	DeleteAccountTypeRequest                = pb.DeleteAccountTypeRequest
	Empty                                   = pb.Empty
	EnsureSystemAccountsRequest             = pb.EnsureSystemAccountsRequest
	EnsureSystemAccountsResponse            = pb.EnsureSystemAccountsResponse
	EnsureUserAccountingSetupRequest        = pb.EnsureUserAccountingSetupRequest
	EnsureUserAccountingSetupResponse       = pb.EnsureUserAccountingSetupResponse
	FreezeUserAssetsRequest                 = pb.FreezeUserAssetsRequest
	FreezeWithdrawRequest                   = pb.FreezeWithdrawRequest
	FundSystemWalletRequest                 = pb.FundSystemWalletRequest
	GetAccountTypeRequest                   = pb.GetAccountTypeRequest
	GetAssetRequest                         = pb.GetAssetRequest
	GetLedgerTxDetailRequest                = pb.GetLedgerTxDetailRequest
	GetLedgerTxDetailResponse               = pb.GetLedgerTxDetailResponse
	GetUserBalancesRequest                  = pb.GetUserBalancesRequest
	GetUserBalancesResponse                 = pb.GetUserBalancesResponse
	GetUserTransactionRecordDetailRequest   = pb.GetUserTransactionRecordDetailRequest
	GetUserTransactionRecordDetailResponse  = pb.GetUserTransactionRecordDetailResponse
	LedgerPostingItem                       = pb.LedgerPostingItem
	LedgerTxItem                            = pb.LedgerTxItem
	LedgerTxResponse                        = pb.LedgerTxResponse
	ListAccountTypesRequest                 = pb.ListAccountTypesRequest
	ListAccountTypesResponse                = pb.ListAccountTypesResponse
	ListAssetsRequest                       = pb.ListAssetsRequest
	ListAssetsResponse                      = pb.ListAssetsResponse
	ListLedgerTxRequest                     = pb.ListLedgerTxRequest
	ListLedgerTxResponse                    = pb.ListLedgerTxResponse
	ListUserTransactionRecordsRequest       = pb.ListUserTransactionRecordsRequest
	ListUserTransactionRecordsResponse      = pb.ListUserTransactionRecordsResponse
	SetAccountTypeAssetsRequest             = pb.SetAccountTypeAssetsRequest
	SettleWithdrawRequest                   = pb.SettleWithdrawRequest
	TransferRequest                         = pb.TransferRequest
	UnfreezeUserAssetsRequest               = pb.UnfreezeUserAssetsRequest
	UnfreezeWithdrawRequest                 = pb.UnfreezeWithdrawRequest
	UpdateAccountTypeRequest                = pb.UpdateAccountTypeRequest
	UpdateAssetIconRequest                  = pb.UpdateAssetIconRequest
	UpdateAssetRequest                      = pb.UpdateAssetRequest
	UpdateAssetStatusRequest                = pb.UpdateAssetStatusRequest
	UpsertUserTransactionRecordMetaRequest  = pb.UpsertUserTransactionRecordMetaRequest
	UpsertUserTransactionRecordMetaResponse = pb.UpsertUserTransactionRecordMetaResponse
	UserBalanceItem                         = pb.UserBalanceItem
	UserTransactionRecordItem               = pb.UserTransactionRecordItem

	Accounting interface {
		// ==================== Setup ====================
		EnsureUserAccountingSetup(ctx context.Context, in *EnsureUserAccountingSetupRequest, opts ...grpc.CallOption) (*EnsureUserAccountingSetupResponse, error)
		EnsureSystemAccounts(ctx context.Context, in *EnsureSystemAccountsRequest, opts ...grpc.CallOption) (*EnsureSystemAccountsResponse, error)
		// ==================== Assets (source of truth) ====================
		GetAssetOverview(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AcctAssetOverviewResponse, error)
		ListAssets(ctx context.Context, in *ListAssetsRequest, opts ...grpc.CallOption) (*ListAssetsResponse, error)
		GetAsset(ctx context.Context, in *GetAssetRequest, opts ...grpc.CallOption) (*AcctAssetResponse, error)
		CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*AcctAssetResponse, error)
		UpdateAsset(ctx context.Context, in *UpdateAssetRequest, opts ...grpc.CallOption) (*AcctAssetResponse, error)
		UpdateAssetStatus(ctx context.Context, in *UpdateAssetStatusRequest, opts ...grpc.CallOption) (*AcctAssetResponse, error)
		UpdateAssetIcon(ctx context.Context, in *UpdateAssetIconRequest, opts ...grpc.CallOption) (*AcctAssetResponse, error)
		// ==================== Account Types ====================
		CreateAccountType(ctx context.Context, in *CreateAccountTypeRequest, opts ...grpc.CallOption) (*AcctAccountTypeResponse, error)
		UpdateAccountType(ctx context.Context, in *UpdateAccountTypeRequest, opts ...grpc.CallOption) (*AcctAccountTypeResponse, error)
		DeleteAccountType(ctx context.Context, in *DeleteAccountTypeRequest, opts ...grpc.CallOption) (*Empty, error)
		GetAccountType(ctx context.Context, in *GetAccountTypeRequest, opts ...grpc.CallOption) (*AcctAccountTypeResponse, error)
		ListAccountTypes(ctx context.Context, in *ListAccountTypesRequest, opts ...grpc.CallOption) (*ListAccountTypesResponse, error)
		SetAccountTypeAssets(ctx context.Context, in *SetAccountTypeAssetsRequest, opts ...grpc.CallOption) (*Empty, error)
		// ==================== Read APIs ====================
		GetUserBalances(ctx context.Context, in *GetUserBalancesRequest, opts ...grpc.CallOption) (*GetUserBalancesResponse, error)
		ListLedgerTx(ctx context.Context, in *ListLedgerTxRequest, opts ...grpc.CallOption) (*ListLedgerTxResponse, error)
		GetLedgerTxDetail(ctx context.Context, in *GetLedgerTxDetailRequest, opts ...grpc.CallOption) (*GetLedgerTxDetailResponse, error)
		ListUserTransactionRecords(ctx context.Context, in *ListUserTransactionRecordsRequest, opts ...grpc.CallOption) (*ListUserTransactionRecordsResponse, error)
		GetUserTransactionRecordDetail(ctx context.Context, in *GetUserTransactionRecordDetailRequest, opts ...grpc.CallOption) (*GetUserTransactionRecordDetailResponse, error)
		UpsertUserTransactionRecordMeta(ctx context.Context, in *UpsertUserTransactionRecordMetaRequest, opts ...grpc.CallOption) (*UpsertUserTransactionRecordMetaResponse, error)
		// ==================== Fixed double-entry templates ====================
		FreezeWithdraw(ctx context.Context, in *FreezeWithdrawRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error)
		UnfreezeWithdraw(ctx context.Context, in *UnfreezeWithdrawRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error)
		SettleWithdraw(ctx context.Context, in *SettleWithdrawRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error)
		ConfirmDeposit(ctx context.Context, in *ConfirmDepositRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error)
		AdminAdjust(ctx context.Context, in *AdminAdjustRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error)
		Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error)
		FundSystemWallet(ctx context.Context, in *FundSystemWalletRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error)
		FreezeUserAssets(ctx context.Context, in *FreezeUserAssetsRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error)
		UnfreezeUserAssets(ctx context.Context, in *UnfreezeUserAssetsRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error)
	}

	defaultAccounting struct {
		cli zrpc.Client
	}
)

func NewAccounting(cli zrpc.Client) Accounting {
	return &defaultAccounting{
		cli: cli,
	}
}

// ==================== Setup ====================
func (m *defaultAccounting) EnsureUserAccountingSetup(ctx context.Context, in *EnsureUserAccountingSetupRequest, opts ...grpc.CallOption) (*EnsureUserAccountingSetupResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.EnsureUserAccountingSetup(ctx, in, opts...)
}

func (m *defaultAccounting) EnsureSystemAccounts(ctx context.Context, in *EnsureSystemAccountsRequest, opts ...grpc.CallOption) (*EnsureSystemAccountsResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.EnsureSystemAccounts(ctx, in, opts...)
}

// ==================== Assets (source of truth) ====================
func (m *defaultAccounting) GetAssetOverview(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AcctAssetOverviewResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.GetAssetOverview(ctx, in, opts...)
}

func (m *defaultAccounting) ListAssets(ctx context.Context, in *ListAssetsRequest, opts ...grpc.CallOption) (*ListAssetsResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.ListAssets(ctx, in, opts...)
}

func (m *defaultAccounting) GetAsset(ctx context.Context, in *GetAssetRequest, opts ...grpc.CallOption) (*AcctAssetResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.GetAsset(ctx, in, opts...)
}

func (m *defaultAccounting) CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*AcctAssetResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.CreateAsset(ctx, in, opts...)
}

func (m *defaultAccounting) UpdateAsset(ctx context.Context, in *UpdateAssetRequest, opts ...grpc.CallOption) (*AcctAssetResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.UpdateAsset(ctx, in, opts...)
}

func (m *defaultAccounting) UpdateAssetStatus(ctx context.Context, in *UpdateAssetStatusRequest, opts ...grpc.CallOption) (*AcctAssetResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.UpdateAssetStatus(ctx, in, opts...)
}

func (m *defaultAccounting) UpdateAssetIcon(ctx context.Context, in *UpdateAssetIconRequest, opts ...grpc.CallOption) (*AcctAssetResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.UpdateAssetIcon(ctx, in, opts...)
}

// ==================== Account Types ====================
func (m *defaultAccounting) CreateAccountType(ctx context.Context, in *CreateAccountTypeRequest, opts ...grpc.CallOption) (*AcctAccountTypeResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.CreateAccountType(ctx, in, opts...)
}

func (m *defaultAccounting) UpdateAccountType(ctx context.Context, in *UpdateAccountTypeRequest, opts ...grpc.CallOption) (*AcctAccountTypeResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.UpdateAccountType(ctx, in, opts...)
}

func (m *defaultAccounting) DeleteAccountType(ctx context.Context, in *DeleteAccountTypeRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.DeleteAccountType(ctx, in, opts...)
}

func (m *defaultAccounting) GetAccountType(ctx context.Context, in *GetAccountTypeRequest, opts ...grpc.CallOption) (*AcctAccountTypeResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.GetAccountType(ctx, in, opts...)
}

func (m *defaultAccounting) ListAccountTypes(ctx context.Context, in *ListAccountTypesRequest, opts ...grpc.CallOption) (*ListAccountTypesResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.ListAccountTypes(ctx, in, opts...)
}

func (m *defaultAccounting) SetAccountTypeAssets(ctx context.Context, in *SetAccountTypeAssetsRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.SetAccountTypeAssets(ctx, in, opts...)
}

// ==================== Read APIs ====================
func (m *defaultAccounting) GetUserBalances(ctx context.Context, in *GetUserBalancesRequest, opts ...grpc.CallOption) (*GetUserBalancesResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.GetUserBalances(ctx, in, opts...)
}

func (m *defaultAccounting) ListLedgerTx(ctx context.Context, in *ListLedgerTxRequest, opts ...grpc.CallOption) (*ListLedgerTxResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.ListLedgerTx(ctx, in, opts...)
}

func (m *defaultAccounting) GetLedgerTxDetail(ctx context.Context, in *GetLedgerTxDetailRequest, opts ...grpc.CallOption) (*GetLedgerTxDetailResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.GetLedgerTxDetail(ctx, in, opts...)
}

func (m *defaultAccounting) ListUserTransactionRecords(ctx context.Context, in *ListUserTransactionRecordsRequest, opts ...grpc.CallOption) (*ListUserTransactionRecordsResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.ListUserTransactionRecords(ctx, in, opts...)
}

func (m *defaultAccounting) GetUserTransactionRecordDetail(ctx context.Context, in *GetUserTransactionRecordDetailRequest, opts ...grpc.CallOption) (*GetUserTransactionRecordDetailResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.GetUserTransactionRecordDetail(ctx, in, opts...)
}

func (m *defaultAccounting) UpsertUserTransactionRecordMeta(ctx context.Context, in *UpsertUserTransactionRecordMetaRequest, opts ...grpc.CallOption) (*UpsertUserTransactionRecordMetaResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.UpsertUserTransactionRecordMeta(ctx, in, opts...)
}

// ==================== Fixed double-entry templates ====================
func (m *defaultAccounting) FreezeWithdraw(ctx context.Context, in *FreezeWithdrawRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.FreezeWithdraw(ctx, in, opts...)
}

func (m *defaultAccounting) UnfreezeWithdraw(ctx context.Context, in *UnfreezeWithdrawRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.UnfreezeWithdraw(ctx, in, opts...)
}

func (m *defaultAccounting) SettleWithdraw(ctx context.Context, in *SettleWithdrawRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.SettleWithdraw(ctx, in, opts...)
}

func (m *defaultAccounting) ConfirmDeposit(ctx context.Context, in *ConfirmDepositRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.ConfirmDeposit(ctx, in, opts...)
}

func (m *defaultAccounting) AdminAdjust(ctx context.Context, in *AdminAdjustRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.AdminAdjust(ctx, in, opts...)
}

func (m *defaultAccounting) Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.Transfer(ctx, in, opts...)
}

func (m *defaultAccounting) FundSystemWallet(ctx context.Context, in *FundSystemWalletRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.FundSystemWallet(ctx, in, opts...)
}

func (m *defaultAccounting) FreezeUserAssets(ctx context.Context, in *FreezeUserAssetsRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.FreezeUserAssets(ctx, in, opts...)
}

func (m *defaultAccounting) UnfreezeUserAssets(ctx context.Context, in *UnfreezeUserAssetsRequest, opts ...grpc.CallOption) (*LedgerTxResponse, error) {
	client := pb.NewAccountingClient(m.cli.Conn())
	return client.UnfreezeUserAssets(ctx, in, opts...)
}
